USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS KMAT_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE KMAT_WH;

CREATE DATABASE IF NOT EXISTS KMAT_COST_MODEL_DB;

USE DATABASE KMAT_COST_MODEL_DB;

CREATE SCHEMA IF NOT EXISTS CORE_INPUT;
CREATE SCHEMA IF NOT EXISTS CORE_OUTPUT;
CREATE SCHEMA IF NOT EXISTS CORE_INTERNAL;

USE DATABASE KMAT_COST_MODEL_DB;
USE SCHEMA CORE_INPUT;

CREATE OR REPLACE TABLE CORE_INPUT.KMAT_PRODUCT_MASTER (
    KMAT_ID              VARCHAR,
    DESCRIPTION          VARCHAR,
    PRODUCT_FAMILY       VARCHAR,
    ACTIVE_FLAG          BOOLEAN,
    CREATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
select * from KMAT_PRODUCT_MASTER;

CREATE OR REPLACE TABLE CORE_INPUT.CHARACTERISTIC_MASTER (
    KMAT_ID              VARCHAR,
    CHARACTERISTIC_NAME  VARCHAR,
    ALLOWED_VALUE        VARCHAR,
    DISPLAY_ORDER        NUMBER,
    ACTIVE_FLAG          BOOLEAN
);

CREATE OR REPLACE TABLE CORE_INPUT.DEPENDENCY_RULES (
    RULE_ID              VARCHAR,
    RULE_JSON            VARIANT,
    RULE_DESCRIPTION     VARCHAR
);

CREATE OR REPLACE TABLE CORE_INPUT.KMAT_SUPER_BOM (
    KMAT_ID              VARCHAR,
    COMPONENT_ID         VARCHAR,
    COMPONENT_DESCRIPTION VARCHAR,
    QUANTITY             NUMBER(18,4),
    UOM                  VARCHAR,
    RULE_ID              VARCHAR,
    IS_BULK_MATERIAL     BOOLEAN,
    COST_COMPONENT_GROUP VARCHAR
);

CREATE OR REPLACE TABLE CORE_INPUT.MATERIAL_COSTS (
    ITEM_ID              VARCHAR,
    DESCRIPTION          VARCHAR,
    STANDARD_COST_USD    NUMBER(18,4),
    UOM                  VARCHAR,
    COST_SOURCE          VARCHAR
);

CREATE OR REPLACE TABLE CORE_INPUT.WORK_CENTER_RATES (
    WORK_CENTER_ID              VARCHAR,
    WORK_CENTER_DESCRIPTION     VARCHAR,
    LABOR_RATE_USD_PER_HOUR     NUMBER(18,4),
    MACHINE_RATE_USD_PER_HOUR   NUMBER(18,4)
);

CREATE OR REPLACE TABLE CORE_INPUT.KMAT_SUPER_ROUTING (
    KMAT_ID              VARCHAR,
    OPERATION_ID         VARCHAR,
    OPERATION_DESCRIPTION VARCHAR,
    WORK_CENTER_ID       VARCHAR,
    LABOR_HOURS          NUMBER(18,4),
    MACHINE_HOURS        NUMBER(18,4),
    RULE_ID              VARCHAR
);

CREATE OR REPLACE TABLE CORE_INPUT.OVERHEAD_RATES (
    KMAT_ID               VARCHAR,
    OVERHEAD_ID           VARCHAR,
    OVERHEAD_DESCRIPTION  VARCHAR,
    BASIS                 VARCHAR,
    RATE_VALUE            NUMBER(18,4),
    RULE_ID               VARCHAR
);

CREATE OR REPLACE TABLE CORE_INPUT.SIMULATION_HEADER (
    SIMULATION_ID         VARCHAR,
    KMAT_ID               VARCHAR,
    CUSTOMER_ID           VARCHAR,
    SCENARIO_NAME         VARCHAR,
    CREATED_AT            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CORE_INPUT.CHARACTERISTIC_VALUES (
    SIMULATION_ID         VARCHAR,
    KMAT_ID               VARCHAR,
    CHARACTERISTIC_NAME   VARCHAR,
    SELECTED_VALUE        VARCHAR
);

CREATE OR REPLACE TABLE CORE_INPUT.SIMULATION_PARAMETERS (
    SIMULATION_ID                 VARCHAR,
    MATERIAL_COST_MULTIPLIER      NUMBER(18,4),
    LABOR_RATE_MULTIPLIER         NUMBER(18,4),
    MACHINE_RATE_MULTIPLIER       NUMBER(18,4),
    OVERHEAD_MULTIPLIER           NUMBER(18,4),
    TARGET_MARGIN_PCT             NUMBER(18,4),
    FLOOR_MARKUP_PCT              NUMBER(18,4),
    CEILING_MARKUP_PCT            NUMBER(18,4)
);

--CORE OUTPUT TABLES
USE DATABASE KMAT_COST_MODEL_DB;
USE SCHEMA CORE_OUTPUT;

CREATE OR REPLACE TABLE CORE_OUTPUT.KMAT_CONFIGURED_COMPONENT_COSTS (
    SIMULATION_ID              VARCHAR,
    KMAT_ID                    VARCHAR,
    COMPONENT_ID               VARCHAR,
    COMPONENT_DESCRIPTION      VARCHAR,
    QUANTITY                   NUMBER(18,4),
    UOM                        VARCHAR,
    RULE_ID                    VARCHAR,
    IS_BULK_MATERIAL           BOOLEAN,
    COST_COMPONENT_GROUP       VARCHAR,
    STANDARD_COST_USD          NUMBER(18,4),
    LINE_MATERIAL_COST_USD     NUMBER(18,4),
    COST_MISSING_FLAG          BOOLEAN,
    CALCULATED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CORE_OUTPUT.KMAT_CONFIGURED_OPERATION_COSTS (
    SIMULATION_ID              VARCHAR,
    KMAT_ID                    VARCHAR,
    OPERATION_ID               VARCHAR,
    OPERATION_DESCRIPTION      VARCHAR,
    WORK_CENTER_ID             VARCHAR,
    LABOR_HOURS                NUMBER(18,4),
    MACHINE_HOURS              NUMBER(18,4),
    LABOR_RATE_USD_PER_HOUR    NUMBER(18,4),
    MACHINE_RATE_USD_PER_HOUR  NUMBER(18,4),
    LABOR_COST_USD             NUMBER(18,4),
    MACHINE_COST_USD           NUMBER(18,4),
    RULE_ID                    VARCHAR,
    CALCULATED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CORE_OUTPUT.KMAT_CONFIGURED_OVERHEAD_COSTS (
    SIMULATION_ID              VARCHAR,
    KMAT_ID                    VARCHAR,
    OVERHEAD_ID                VARCHAR,
    OVERHEAD_DESCRIPTION       VARCHAR,
    BASIS                      VARCHAR,
    RATE_VALUE                 NUMBER(18,4),
    OVERHEAD_COST_USD          NUMBER(18,4),
    RULE_ID                    VARCHAR,
    CALCULATED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE CORE_OUTPUT.KMAT_CONFIGURED_COST_SUMMARY (
    SIMULATION_ID              VARCHAR,
    KMAT_ID                    VARCHAR,
    MATERIAL_COST_USD          NUMBER(18,4),
    LABOR_COST_USD             NUMBER(18,4),
    MACHINE_COST_USD           NUMBER(18,4),
    OVERHEAD_COST_USD          NUMBER(18,4),
    TOTAL_CONFIGURED_COST_USD  NUMBER(18,4),
    FLOOR_PRICE_USD            NUMBER(18,4),
    TARGET_PRICE_USD           NUMBER(18,4),
    CEILING_PRICE_USD          NUMBER(18,4),
    CALCULATED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

--Insert KMAT Product Data
INSERT INTO CORE_INPUT.KMAT_PRODUCT_MASTER
(KMAT_ID, DESCRIPTION, PRODUCT_FAMILY, ACTIVE_FLAG)
VALUES
('KMAT_TRUCK_01', 'Configurable Truck Product', 'TRUCK', TRUE);

SELECT * FROM CORE_INPUT.KMAT_PRODUCT_MASTER;
DELETE FROM CORE_INPUT.KMAT_PRODUCT_MASTER
WHERE KMAT_ID = 'KMAT_TRUCK_01'
  AND CREATED_AT = '2026-06-15 04:38:19.885';
--Insert Characteristics and allowed value 
INSERT INTO CORE_INPUT.CHARACTERISTIC_MASTER
(KMAT_ID, CHARACTERISTIC_NAME, ALLOWED_VALUE, DISPLAY_ORDER, ACTIVE_FLAG)
VALUES
    ('KMAT_TRUCK_01', 'ENGINE', 'V6',       1, TRUE),
    ('KMAT_TRUCK_01', 'ENGINE', 'V8',       1, TRUE),
    
    ('KMAT_TRUCK_01', 'CAB',    'STANDARD', 2, TRUE),
    ('KMAT_TRUCK_01', 'CAB',    'PREMIUM',  2, TRUE),
    
    ('KMAT_TRUCK_01', 'WHEEL',  'STANDARD', 3, TRUE),
    ('KMAT_TRUCK_01', 'WHEEL',  'OFFROAD',  3, TRUE),
    
    ('KMAT_TRUCK_01', 'COLOR',  'RED',      4, TRUE),
    ('KMAT_TRUCK_01', 'COLOR',  'BLUE',     4, TRUE);

SELECT * FROM CORE_INPUT.CHARACTERISTIC_MASTER
ORDER BY DISPLAY_ORDER, CHARACTERISTIC_NAME, ALLOWED_VALUE;

--Insert Dependency based on JSOn
INSERT INTO CORE_INPUT.DEPENDENCY_RULES
(RULE_ID, RULE_JSON, RULE_DESCRIPTION)
SELECT
    COLUMN1,
    PARSE_JSON(COLUMN2),
    COLUMN3
FROM VALUES
    ('DEFAULT', '{"type":"DEFAULT"}', 'Always selected'),
    ('R001', '{"characteristic":"ENGINE","operator":"=","value":"V6"}', 'Select component when ENGINE = V6'),
    ('R002', '{"characteristic":"ENGINE","operator":"=","value":"V8"}', 'Select component when ENGINE = V8'),
    ('R003', '{"characteristic":"CAB","operator":"=","value":"STANDARD"}', 'Select component when CAB = STANDARD'),
    ('R004', '{"characteristic":"CAB","operator":"=","value":"PREMIUM"}', 'Select component when CAB = PREMIUM'),
    ('R005', '{"characteristic":"WHEEL","operator":"=","value":"OFFROAD"}', 'Select component when WHEEL = OFFROAD'),
    ('R006', '{"characteristic":"COLOR","operator":"=","value":"RED"}', 'Select component when COLOR = RED'),
    ('R007', '{"characteristic":"COLOR","operator":"=","value":"BLUE"}', 'Select component when COLOR = BLUE'),
    ('R008', '{"characteristic":"WHEEL","operator":"=","value":"STANDARD"}', 'Select component when WHEEL = STANDARD');

DESC TABLE CORE_INPUT.DEPENDENCY_RULES;
SELECT
    RULE_ID,
    RULE_JSON,
    RULE_DESCRIPTION
FROM CORE_INPUT.DEPENDENCY_RULES
ORDER BY RULE_ID;

--Super BOM Data
INSERT INTO CORE_INPUT.KMAT_SUPER_BOM
(KMAT_ID, COMPONENT_ID, COMPONENT_DESCRIPTION, QUANTITY, UOM, RULE_ID, IS_BULK_MATERIAL, COST_COMPONENT_GROUP)
VALUES
('KMAT_TRUCK_01', 'PART_ENG_V6',        'V6 Engine',             1, 'EA', 'R001',    FALSE, 'ENGINE'),
('KMAT_TRUCK_01', 'PART_ENG_V8',        'V8 Engine',             1, 'EA', 'R002',    FALSE, 'ENGINE'),

('KMAT_TRUCK_01', 'CAB_STANDARD',       'Standard Cab',          1, 'EA', 'R003',    FALSE, 'CAB'),
('KMAT_TRUCK_01', 'CAB_PREMIUM',        'Premium Cab',           1, 'EA', 'R004',    FALSE, 'CAB'),

('KMAT_TRUCK_01', 'WHEEL_STANDARD',     'Standard Wheel',        4, 'EA', 'R008',    FALSE, 'WHEEL'),
('KMAT_TRUCK_01', 'WHEEL_OFFROAD',      'Offroad Wheel',         4, 'EA', 'R005',    FALSE, 'WHEEL'),

('KMAT_TRUCK_01', 'PAINT_RED',          'Red Paint Package',     1, 'EA', 'R006',    FALSE, 'PAINT'),
('KMAT_TRUCK_01', 'PAINT_BLUE',         'Blue Paint Package',    1, 'EA', 'R007',    FALSE, 'PAINT'),

('KMAT_TRUCK_01', 'BULK_FASTENER_KIT',  'Bulk Fastener Kit',     1, 'EA', 'DEFAULT', TRUE,  'BULK'),
('KMAT_TRUCK_01', 'SHOP_SUPPLIES_BULK', 'Shop Supplies Bulk',    1, 'EA', 'DEFAULT', TRUE,  'BULK');

SELECT * FROM CORE_INPUT.KMAT_SUPER_BOM
ORDER BY COST_COMPONENT_GROUP, COMPONENT_ID;

--Insert material costs
INSERT INTO CORE_INPUT.MATERIAL_COSTS
(ITEM_ID, DESCRIPTION, STANDARD_COST_USD, UOM, COST_SOURCE)
VALUES
('PART_ENG_V6',       'V6 Engine',             8000,  'EA', 'SAMPLE_STANDARD_COST'),
('PART_ENG_V8',       'V8 Engine',             12000, 'EA', 'SAMPLE_STANDARD_COST'),

('CAB_STANDARD',      'Standard Cab',          3000,  'EA', 'SAMPLE_STANDARD_COST'),
('CAB_PREMIUM',       'Premium Cab',           6200,  'EA', 'SAMPLE_STANDARD_COST'),

('WHEEL_STANDARD',    'Standard Wheel',        250,   'EA', 'SAMPLE_STANDARD_COST'),
('WHEEL_OFFROAD',     'Offroad Wheel',         450,   'EA', 'SAMPLE_STANDARD_COST'),

('PAINT_RED',         'Red Paint Package',     200,   'EA', 'SAMPLE_STANDARD_COST'),
('PAINT_BLUE',        'Blue Paint Package',    180,   'EA', 'SAMPLE_STANDARD_COST'),

('BULK_FASTENER_KIT', 'Bulk Fastener Kit',     50,    'EA', 'SAMPLE_STANDARD_COST');

SELECT * FROM CORE_INPUT.MATERIAL_COSTS
ORDER BY ITEM_ID;

--Insert Machine and labour rate data
INSERT INTO CORE_INPUT.WORK_CENTER_RATES
(WORK_CENTER_ID, WORK_CENTER_DESCRIPTION, LABOR_RATE_USD_PER_HOUR, MACHINE_RATE_USD_PER_HOUR)
VALUES
    ('WC_ASSEMBLY', 'Truck Assembly Work Center', 70, 40),
    ('WC_PAINT',    'Paint Booth Work Center',    65, 55),
    ('WC_QA',       'Quality Inspection Center',  75, 20);

SELECT * FROM CORE_INPUT.WORK_CENTER_RATES;

--Insert Super Routing data
INSERT INTO CORE_INPUT.KMAT_SUPER_ROUTING
(KMAT_ID, OPERATION_ID, OPERATION_DESCRIPTION, WORK_CENTER_ID, LABOR_HOURS, MACHINE_HOURS, RULE_ID)
VALUES
('KMAT_TRUCK_01', 'OP_BASE_ASSEMBLY',      'Base Truck Assembly',          'WC_ASSEMBLY', 6.0, 2.0, 'DEFAULT'),
('KMAT_TRUCK_01', 'OP_BASE_QA',            'Base Quality Inspection',      'WC_QA',       1.0, 0.2, 'DEFAULT'),

('KMAT_TRUCK_01', 'OP_V6_ENGINE_INSTALL',  'V6 Engine Installation',       'WC_ASSEMBLY', 1.0, 0.4, 'R001'),
('KMAT_TRUCK_01', 'OP_V8_ENGINE_INSTALL',  'V8 Engine Installation',       'WC_ASSEMBLY', 1.5, 0.5, 'R002'),

('KMAT_TRUCK_01', 'OP_STANDARD_CAB_FIT',   'Standard Cab Fitting',         'WC_ASSEMBLY', 1.0, 0.3, 'R003'),
('KMAT_TRUCK_01', 'OP_PREMIUM_CAB_FIT',    'Premium Cab Fitting',          'WC_ASSEMBLY', 2.0, 0.7, 'R004'),

('KMAT_TRUCK_01', 'OP_OFFROAD_WHEEL_FIT',  'Offroad Wheel Fitting',        'WC_ASSEMBLY', 0.8, 0.2, 'R005'),

('KMAT_TRUCK_01', 'OP_RED_PAINT',          'Red Paint Application',        'WC_PAINT',    1.0, 0.6, 'R006'),
('KMAT_TRUCK_01', 'OP_BLUE_PAINT',         'Blue Paint Application',       'WC_PAINT',    0.8, 0.5, 'R007');

SELECT * FROM CORE_INPUT.KMAT_SUPER_ROUTING
ORDER BY OPERATION_ID;

--Insert Overhead rules 
INSERT INTO CORE_INPUT.OVERHEAD_RATES
(KMAT_ID, OVERHEAD_ID, OVERHEAD_DESCRIPTION, BASIS, RATE_VALUE, RULE_ID)
VALUES
('KMAT_TRUCK_01', 'OH_MATERIAL_HANDLING', 'Material Handling Overhead', 'MATERIAL_PERCENT', 0.08, 'DEFAULT'),
('KMAT_TRUCK_01', 'OH_FACTORY_FIXED',     'Fixed Factory Overhead',     'FIXED',            400,  'DEFAULT'),
('KMAT_TRUCK_01', 'OH_PREMIUM_QA',        'Premium QA Overhead',        'FIXED',            150,  'R004');

SELECT * FROM CORE_INPUT.OVERHEAD_RATES;

--INSERT SAMPLE SIMULATION DATA
INSERT INTO CORE_INPUT.SIMULATION_HEADER
(SIMULATION_ID, KMAT_ID, CUSTOMER_ID, SCENARIO_NAME)
VALUES
('SIM_001', 'KMAT_TRUCK_01', 'CUST_001', 'V8 Premium Offroad Red Truck Baseline');

INSERT INTO CORE_INPUT.CHARACTERISTIC_VALUES
(SIMULATION_ID, KMAT_ID, CHARACTERISTIC_NAME, SELECTED_VALUE)
VALUES
('SIM_001', 'KMAT_TRUCK_01', 'ENGINE', 'V8'),
('SIM_001', 'KMAT_TRUCK_01', 'CAB',    'PREMIUM'),
('SIM_001', 'KMAT_TRUCK_01', 'WHEEL',  'OFFROAD'),
('SIM_001', 'KMAT_TRUCK_01', 'COLOR',  'RED');

INSERT INTO CORE_INPUT.SIMULATION_PARAMETERS
(SIMULATION_ID, MATERIAL_COST_MULTIPLIER, LABOR_RATE_MULTIPLIER, MACHINE_RATE_MULTIPLIER, OVERHEAD_MULTIPLIER, TARGET_MARGIN_PCT, FLOOR_MARKUP_PCT, CEILING_MARKUP_PCT)
VALUES
('SIM_001', 1.00, 1.00, 1.00, 1.00, 0.35, 0.10, 0.60);

SELECT * FROM CORE_INPUT.CHARACTERISTIC_VALUES
WHERE SIMULATION_ID = 'SIM_001'
ORDER BY CHARACTERISTIC_NAME;

--RULE EVALUATION
WITH RULE_EVALUATION AS (
    SELECT
        h.SIMULATION_ID,
        bom.KMAT_ID,
        bom.COMPONENT_ID,
        bom.COMPONENT_DESCRIPTION,
        bom.QUANTITY,
        bom.UOM,
        bom.RULE_ID,
        bom.IS_BULK_MATERIAL,
        bom.COST_COMPONENT_GROUP,
        COALESCE(mc.STANDARD_COST_USD, 0) AS STANDARD_COST_USD,
        bom.QUANTITY * COALESCE(mc.STANDARD_COST_USD, 0) AS LINE_MATERIAL_COST_USD,
        IFF(mc.ITEM_ID IS NULL OR mc.STANDARD_COST_USD IS NULL, TRUE, FALSE) AS COST_MISSING_FLAG,
        CASE
            WHEN dr.RULE_JSON:type::STRING = 'DEFAULT'
                THEN TRUE
            WHEN cv.SELECTED_VALUE = dr.RULE_JSON:value::STRING
                THEN TRUE
            ELSE FALSE
        END AS IS_SELECTED
    FROM CORE_INPUT.SIMULATION_HEADER h
    JOIN CORE_INPUT.KMAT_SUPER_BOM bom
        ON h.KMAT_ID = bom.KMAT_ID
    JOIN CORE_INPUT.DEPENDENCY_RULES dr
        ON bom.RULE_ID = dr.RULE_ID
    LEFT JOIN CORE_INPUT.CHARACTERISTIC_VALUES cv
        ON cv.SIMULATION_ID = h.SIMULATION_ID
       AND cv.KMAT_ID = bom.KMAT_ID
       AND cv.CHARACTERISTIC_NAME = dr.RULE_JSON:characteristic::STRING
    LEFT JOIN CORE_INPUT.MATERIAL_COSTS mc
        ON bom.COMPONENT_ID = mc.ITEM_ID
    WHERE h.SIMULATION_ID = 'SIM_001'
)
SELECT
    SIMULATION_ID,
    KMAT_ID,
    COMPONENT_ID,
    COMPONENT_DESCRIPTION,
    QUANTITY,
    UOM,
    RULE_ID,
    IS_BULK_MATERIAL,
    COST_COMPONENT_GROUP,
    STANDARD_COST_USD,
    LINE_MATERIAL_COST_USD,
    COST_MISSING_FLAG
FROM RULE_EVALUATION
WHERE IS_SELECTED = TRUE
ORDER BY COST_COMPONENT_GROUP, COMPONENT_ID;

--VALIDATE MATERIAL COST
WITH RULE_EVALUATION AS (
    SELECT
        h.SIMULATION_ID,
        bom.KMAT_ID,
        bom.COMPONENT_ID,
        bom.QUANTITY,
        COALESCE(mc.STANDARD_COST_USD, 0) AS STANDARD_COST_USD,
        bom.QUANTITY * COALESCE(mc.STANDARD_COST_USD, 0) AS LINE_MATERIAL_COST_USD,
        CASE
            WHEN dr.RULE_JSON:type::STRING = 'DEFAULT'
                THEN TRUE
            WHEN cv.SELECTED_VALUE = dr.RULE_JSON:value::STRING
                THEN TRUE
            ELSE FALSE
        END AS IS_SELECTED
    FROM CORE_INPUT.SIMULATION_HEADER h
    JOIN CORE_INPUT.KMAT_SUPER_BOM bom
        ON h.KMAT_ID = bom.KMAT_ID
    JOIN CORE_INPUT.DEPENDENCY_RULES dr
        ON bom.RULE_ID = dr.RULE_ID
    LEFT JOIN CORE_INPUT.CHARACTERISTIC_VALUES cv
        ON cv.SIMULATION_ID = h.SIMULATION_ID
       AND cv.KMAT_ID = bom.KMAT_ID
       AND cv.CHARACTERISTIC_NAME = dr.RULE_JSON:characteristic::STRING
    LEFT JOIN CORE_INPUT.MATERIAL_COSTS mc
        ON bom.COMPONENT_ID = mc.ITEM_ID
    WHERE h.SIMULATION_ID = 'SIM_001'
)
SELECT
    SIMULATION_ID,
    KMAT_ID,
    SUM(LINE_MATERIAL_COST_USD) AS TOTAL_MATERIAL_COST_USD
FROM RULE_EVALUATION
WHERE IS_SELECTED = TRUE
GROUP BY SIMULATION_ID, KMAT_ID;

---VALIDATING SELECTED ROUTING OPERATIONS
WITH ROUTING_RULE_EVALUATION AS (
    SELECT
        h.SIMULATION_ID,
        rt.KMAT_ID,
        rt.OPERATION_ID,
        rt.OPERATION_DESCRIPTION,
        rt.WORK_CENTER_ID,
        rt.LABOR_HOURS,
        rt.MACHINE_HOURS,
        wr.LABOR_RATE_USD_PER_HOUR,
        wr.MACHINE_RATE_USD_PER_HOUR,
        rt.LABOR_HOURS * wr.LABOR_RATE_USD_PER_HOUR AS LABOR_COST_USD,
        rt.MACHINE_HOURS * wr.MACHINE_RATE_USD_PER_HOUR AS MACHINE_COST_USD,
        rt.RULE_ID,
        CASE
            WHEN dr.RULE_JSON:type::STRING = 'DEFAULT'
                THEN TRUE
            WHEN cv.SELECTED_VALUE = dr.RULE_JSON:value::STRING
                THEN TRUE
            ELSE FALSE
        END AS IS_SELECTED
    FROM CORE_INPUT.SIMULATION_HEADER h
    JOIN CORE_INPUT.KMAT_SUPER_ROUTING rt
        ON h.KMAT_ID = rt.KMAT_ID
    JOIN CORE_INPUT.DEPENDENCY_RULES dr
        ON rt.RULE_ID = dr.RULE_ID
    LEFT JOIN CORE_INPUT.CHARACTERISTIC_VALUES cv
        ON cv.SIMULATION_ID = h.SIMULATION_ID
       AND cv.KMAT_ID = rt.KMAT_ID
       AND cv.CHARACTERISTIC_NAME = dr.RULE_JSON:characteristic::STRING
    JOIN CORE_INPUT.WORK_CENTER_RATES wr
        ON rt.WORK_CENTER_ID = wr.WORK_CENTER_ID
    WHERE h.SIMULATION_ID = 'SIM_001'
)
SELECT
    SIMULATION_ID,
    KMAT_ID,
    OPERATION_ID,
    OPERATION_DESCRIPTION,
    WORK_CENTER_ID,
    LABOR_HOURS,
    MACHINE_HOURS,
    LABOR_COST_USD,
    MACHINE_COST_USD,
    RULE_ID
FROM ROUTING_RULE_EVALUATION
WHERE IS_SELECTED = TRUE
ORDER BY OPERATION_ID;

--VALIDATE MAACHINE AND LABOR COSTS
WITH ROUTING_RULE_EVALUATION AS (
    SELECT
        h.SIMULATION_ID,
        rt.KMAT_ID,
        rt.LABOR_HOURS * wr.LABOR_RATE_USD_PER_HOUR AS LABOR_COST_USD,
        rt.MACHINE_HOURS * wr.MACHINE_RATE_USD_PER_HOUR AS MACHINE_COST_USD,
        CASE
            WHEN dr.RULE_JSON:type::STRING = 'DEFAULT'
                THEN TRUE
            WHEN cv.SELECTED_VALUE = dr.RULE_JSON:value::STRING
                THEN TRUE
            ELSE FALSE
        END AS IS_SELECTED
    FROM CORE_INPUT.SIMULATION_HEADER h
    JOIN CORE_INPUT.KMAT_SUPER_ROUTING rt
        ON h.KMAT_ID = rt.KMAT_ID
    JOIN CORE_INPUT.DEPENDENCY_RULES dr
        ON rt.RULE_ID = dr.RULE_ID
    LEFT JOIN CORE_INPUT.CHARACTERISTIC_VALUES cv
        ON cv.SIMULATION_ID = h.SIMULATION_ID
       AND cv.KMAT_ID = rt.KMAT_ID
       AND cv.CHARACTERISTIC_NAME = dr.RULE_JSON:characteristic::STRING
    JOIN CORE_INPUT.WORK_CENTER_RATES wr
        ON rt.WORK_CENTER_ID = wr.WORK_CENTER_ID
    WHERE h.SIMULATION_ID = 'SIM_001'
)
SELECT
    SIMULATION_ID,
    KMAT_ID,
    SUM(LABOR_COST_USD) AS TOTAL_LABOR_COST_USD,
    SUM(MACHINE_COST_USD) AS TOTAL_MACHINE_COST_USD
FROM ROUTING_RULE_EVALUATION
WHERE IS_SELECTED = TRUE
GROUP BY SIMULATION_ID, KMAT_ID;

--VALIDATE OVERHEAD RULES
WITH MATERIAL_TOTAL AS (
    SELECT
        h.SIMULATION_ID,
        bom.KMAT_ID,
        SUM(bom.QUANTITY * COALESCE(mc.STANDARD_COST_USD, 0)) AS MATERIAL_COST_USD
    FROM CORE_INPUT.SIMULATION_HEADER h
    JOIN CORE_INPUT.KMAT_SUPER_BOM bom
        ON h.KMAT_ID = bom.KMAT_ID
    JOIN CORE_INPUT.DEPENDENCY_RULES dr
        ON bom.RULE_ID = dr.RULE_ID
    LEFT JOIN CORE_INPUT.CHARACTERISTIC_VALUES cv
        ON cv.SIMULATION_ID = h.SIMULATION_ID
       AND cv.KMAT_ID = bom.KMAT_ID
       AND cv.CHARACTERISTIC_NAME = dr.RULE_JSON:characteristic::STRING
    LEFT JOIN CORE_INPUT.MATERIAL_COSTS mc
        ON bom.COMPONENT_ID = mc.ITEM_ID
    WHERE h.SIMULATION_ID = 'SIM_001'
      AND (
            dr.RULE_JSON:type::STRING = 'DEFAULT'
            OR cv.SELECTED_VALUE = dr.RULE_JSON:value::STRING
          )
    GROUP BY h.SIMULATION_ID, bom.KMAT_ID
),
OVERHEAD_RULE_EVALUATION AS (
    SELECT
        h.SIMULATION_ID,
        oh.KMAT_ID,
        oh.OVERHEAD_ID,
        oh.OVERHEAD_DESCRIPTION,
        oh.BASIS,
        oh.RATE_VALUE,
        CASE
            WHEN oh.BASIS = 'MATERIAL_PERCENT'
                THEN mt.MATERIAL_COST_USD * oh.RATE_VALUE
            WHEN oh.BASIS = 'FIXED'
                THEN oh.RATE_VALUE
            ELSE 0
        END AS OVERHEAD_COST_USD,
        CASE
            WHEN dr.RULE_JSON:type::STRING = 'DEFAULT'
                THEN TRUE
            WHEN cv.SELECTED_VALUE = dr.RULE_JSON:value::STRING
                THEN TRUE
            ELSE FALSE
        END AS IS_SELECTED
    FROM CORE_INPUT.SIMULATION_HEADER h
    JOIN CORE_INPUT.OVERHEAD_RATES oh
        ON h.KMAT_ID = oh.KMAT_ID
    JOIN CORE_INPUT.DEPENDENCY_RULES dr
        ON oh.RULE_ID = dr.RULE_ID
    LEFT JOIN CORE_INPUT.CHARACTERISTIC_VALUES cv
        ON cv.SIMULATION_ID = h.SIMULATION_ID
       AND cv.KMAT_ID = oh.KMAT_ID
       AND cv.CHARACTERISTIC_NAME = dr.RULE_JSON:characteristic::STRING
    JOIN MATERIAL_TOTAL mt
        ON h.SIMULATION_ID = mt.SIMULATION_ID
       AND h.KMAT_ID = mt.KMAT_ID
    WHERE h.SIMULATION_ID = 'SIM_001'
)
SELECT
    SIMULATION_ID,
    KMAT_ID,
    OVERHEAD_ID,
    OVERHEAD_DESCRIPTION,
    BASIS,
    RATE_VALUE,
    OVERHEAD_COST_USD
FROM OVERHEAD_RULE_EVALUATION
WHERE IS_SELECTED = TRUE
ORDER BY OVERHEAD_ID;



SELECT * FROM CORE_OUTPUT.KMAT_CONFIGURED_COMPONENT_COSTS