USE ROLE SYSADMIN;
USE WAREHOUSE KMAT_WH;
USE DATABASE KMAT_COST_MODEL_DB;
USE SCHEMA CORE_ML;

CREATE TABLE IF NOT EXISTS ML_DECISION_POLICY_V1 (
    POLICY_ID VARCHAR NOT NULL,
    MODEL_DOMAIN VARCHAR NOT NULL,
    POLICY_VERSION VARCHAR NOT NULL,
    POLICY_STATUS VARCHAR NOT NULL,
    DEPLOYMENT_MODE VARCHAR NOT NULL,
    DECISION_TYPE VARCHAR NOT NULL,
    RAW_ML_OUTPUT_NAME VARCHAR NOT NULL,
    RECOMMENDED_OUTPUT_NAME VARCHAR,
    FINAL_OUTPUT_NAME VARCHAR,
    OUTPUT_UNIT VARCHAR NOT NULL,
    RAW_OUTPUT_MIN_VALUE FLOAT,
    RAW_OUTPUT_MAX_VALUE FLOAT,
    FINAL_VALUE_MIN FLOAT,
    FINAL_VALUE_MAX FLOAT,
    MAX_ABS_DEVIATION_FROM_RULE FLOAT,
    MAX_PCT_DEVIATION_FROM_RULE FLOAT,
    MAX_ESTIMATED_COST_IMPACT_PCT FLOAT,
    QUALITY_PASS_REQUIRED_FLAG BOOLEAN NOT NULL,
    OOD_USE_ALLOWED_FLAG BOOLEAN NOT NULL,
    ENGINEER_APPROVAL_REQUIRED_FLAG BOOLEAN NOT NULL,
    AUTO_USE_ALLOWED_FLAG BOOLEAN NOT NULL,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG BOOLEAN NOT NULL,
    BUSINESS_DECISION_ALLOWED_FLAG BOOLEAN NOT NULL,
    FALLBACK_SOURCE VARCHAR NOT NULL,
    FALLBACK_FIELD_NAME VARCHAR,
    POLICY_CONFIG VARIANT,
    EFFECTIVE_FROM TIMESTAMP_NTZ,
    EFFECTIVE_TO TIMESTAMP_NTZ,
    APPROVED_BY VARCHAR,
    APPROVED_AT TIMESTAMP_NTZ,
    CREATED_BY VARCHAR DEFAULT CURRENT_USER(),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    COMMENTS VARCHAR
);

MERGE INTO ML_DECISION_POLICY_V1 target
USING (
    SELECT POLICY_ID,MODEL_DOMAIN,POLICY_VERSION,POLICY_STATUS,DEPLOYMENT_MODE,DECISION_TYPE,RAW_ML_OUTPUT_NAME,RECOMMENDED_OUTPUT_NAME,FINAL_OUTPUT_NAME,OUTPUT_UNIT,RAW_OUTPUT_MIN_VALUE,RAW_OUTPUT_MAX_VALUE,FINAL_VALUE_MIN,FINAL_VALUE_MAX,MAX_ABS_DEVIATION_FROM_RULE,MAX_PCT_DEVIATION_FROM_RULE,MAX_ESTIMATED_COST_IMPACT_PCT,QUALITY_PASS_REQUIRED_FLAG,OOD_USE_ALLOWED_FLAG,ENGINEER_APPROVAL_REQUIRED_FLAG,AUTO_USE_ALLOWED_FLAG,OFFICIAL_COST_IMPACT_ALLOWED_FLAG,BUSINESS_DECISION_ALLOWED_FLAG,FALLBACK_SOURCE,FALLBACK_FIELD_NAME,PARSE_JSON(POLICY_CONFIG) AS POLICY_CONFIG,EFFECTIVE_FROM,EFFECTIVE_TO,APPROVED_BY,APPROVED_AT,COMMENTS
    FROM VALUES
    ('CSS_SHADOW_V1','CSS','SHADOW_V1','ACTIVE','SHADOW','SCRAP_RATE','HIGH_SCRAP_PROBABILITY','RECOMMENDED_SCRAP_RATE','FINAL_SCRAP_RATE','RATE',0.0::FLOAT,1.0::FLOAT,NULL::FLOAT,NULL::FLOAT,NULL::FLOAT,NULL::FLOAT,NULL::FLOAT,TRUE,FALSE,TRUE,FALSE,FALSE,FALSE,'DETERMINISTIC_RULE','RULE_SCRAP_RATE','{"mapping_status":"NOT_APPROVED","ml_use":"DISPLAY_ONLY"}',CURRENT_TIMESTAMP(),NULL::TIMESTAMP_NTZ,'SYSTEM_PHASE9A',CURRENT_TIMESTAMP(),'CSS remains shadow-only. The deterministic scrap rule remains official.'),
    ('FMIS_SHADOW_V1','FMIS','SHADOW_V1','ACTIVE','SHADOW','MATERIAL_MULTIPLIER','FORECAST_MATERIAL_INDEX','RECOMMENDED_FMIS_MULTIPLIER','FINAL_FMIS_MULTIPLIER','MULTIPLIER',0.0::FLOAT,NULL::FLOAT,NULL::FLOAT,NULL::FLOAT,NULL::FLOAT,NULL::FLOAT,NULL::FLOAT,TRUE,FALSE,TRUE,FALSE,FALSE,FALSE,'DETERMINISTIC_RULE','RULE_FMIS_MULTIPLIER','{"mapping_status":"NOT_APPROVED","ml_use":"DISPLAY_ONLY"}',CURRENT_TIMESTAMP(),NULL::TIMESTAMP_NTZ,'SYSTEM_PHASE9A',CURRENT_TIMESTAMP(),'FMIS remains shadow-only. The deterministic multiplier remains official.'),
    ('TDS_SHADOW_V1','TDS','SHADOW_V1','ACTIVE','SHADOW','TOOLING_FACTOR','PREDICTED_TDS_FACTOR','RECOMMENDED_TDS_FACTOR','FINAL_TDS_FACTOR','FACTOR',1.0::FLOAT,3.5::FLOAT,NULL::FLOAT,NULL::FLOAT,NULL::FLOAT,NULL::FLOAT,NULL::FLOAT,TRUE,FALSE,TRUE,FALSE,FALSE,FALSE,'DETERMINISTIC_RULE','RULE_TDS_FACTOR','{"mapping_status":"NOT_APPROVED","ml_use":"DISPLAY_ONLY"}',CURRENT_TIMESTAMP(),NULL::TIMESTAMP_NTZ,'SYSTEM_PHASE9A',CURRENT_TIMESTAMP(),'TDS remains shadow-only. The deterministic factor remains official.'),
    ('BMCS_SHADOW_V1','BMCS','SHADOW_V1','ACTIVE','SHADOW','TRUST_GATE','CALIBRATED_CORRECT_MAPPING_PROBABILITY','ML_BMCS_SCORE','OFFICIAL_REVIEW_STATUS','SCORE',0.0::FLOAT,1.0::FLOAT,0.0::FLOAT,100.0::FLOAT,NULL::FLOAT,NULL::FLOAT,NULL::FLOAT,TRUE,FALSE,TRUE,FALSE,FALSE,FALSE,'PHASE7_RULE_CORTEX_HYBRID','BOM_MATCH_CONFIDENCE_SCORE','{"low_advisory_threshold":0.485,"high_advisory_threshold":0.945,"automatic_action_allowed":false}',CURRENT_TIMESTAMP(),NULL::TIMESTAMP_NTZ,'SYSTEM_PHASE9A',CURRENT_TIMESTAMP(),'BMCS remains a review gate only and never directly changes cost.')
    AS v(POLICY_ID,MODEL_DOMAIN,POLICY_VERSION,POLICY_STATUS,DEPLOYMENT_MODE,DECISION_TYPE,RAW_ML_OUTPUT_NAME,RECOMMENDED_OUTPUT_NAME,FINAL_OUTPUT_NAME,OUTPUT_UNIT,RAW_OUTPUT_MIN_VALUE,RAW_OUTPUT_MAX_VALUE,FINAL_VALUE_MIN,FINAL_VALUE_MAX,MAX_ABS_DEVIATION_FROM_RULE,MAX_PCT_DEVIATION_FROM_RULE,MAX_ESTIMATED_COST_IMPACT_PCT,QUALITY_PASS_REQUIRED_FLAG,OOD_USE_ALLOWED_FLAG,ENGINEER_APPROVAL_REQUIRED_FLAG,AUTO_USE_ALLOWED_FLAG,OFFICIAL_COST_IMPACT_ALLOWED_FLAG,BUSINESS_DECISION_ALLOWED_FLAG,FALLBACK_SOURCE,FALLBACK_FIELD_NAME,POLICY_CONFIG,EFFECTIVE_FROM,EFFECTIVE_TO,APPROVED_BY,APPROVED_AT,COMMENTS)
) source
ON target.POLICY_ID = source.POLICY_ID
WHEN NOT MATCHED THEN INSERT (
    POLICY_ID,MODEL_DOMAIN,POLICY_VERSION,POLICY_STATUS,DEPLOYMENT_MODE,DECISION_TYPE,
    RAW_ML_OUTPUT_NAME,RECOMMENDED_OUTPUT_NAME,FINAL_OUTPUT_NAME,OUTPUT_UNIT,
    RAW_OUTPUT_MIN_VALUE,RAW_OUTPUT_MAX_VALUE,FINAL_VALUE_MIN,FINAL_VALUE_MAX,
    MAX_ABS_DEVIATION_FROM_RULE,MAX_PCT_DEVIATION_FROM_RULE,MAX_ESTIMATED_COST_IMPACT_PCT,
    QUALITY_PASS_REQUIRED_FLAG,OOD_USE_ALLOWED_FLAG,ENGINEER_APPROVAL_REQUIRED_FLAG,
    AUTO_USE_ALLOWED_FLAG,OFFICIAL_COST_IMPACT_ALLOWED_FLAG,BUSINESS_DECISION_ALLOWED_FLAG,
    FALLBACK_SOURCE,FALLBACK_FIELD_NAME,POLICY_CONFIG,EFFECTIVE_FROM,EFFECTIVE_TO,
    APPROVED_BY,APPROVED_AT,COMMENTS
) VALUES (
    source.POLICY_ID,source.MODEL_DOMAIN,source.POLICY_VERSION,source.POLICY_STATUS,
    source.DEPLOYMENT_MODE,source.DECISION_TYPE,source.RAW_ML_OUTPUT_NAME,
    source.RECOMMENDED_OUTPUT_NAME,source.FINAL_OUTPUT_NAME,source.OUTPUT_UNIT,
    source.RAW_OUTPUT_MIN_VALUE,source.RAW_OUTPUT_MAX_VALUE,source.FINAL_VALUE_MIN,
    source.FINAL_VALUE_MAX,source.MAX_ABS_DEVIATION_FROM_RULE,
    source.MAX_PCT_DEVIATION_FROM_RULE,source.MAX_ESTIMATED_COST_IMPACT_PCT,
    source.QUALITY_PASS_REQUIRED_FLAG,source.OOD_USE_ALLOWED_FLAG,
    source.ENGINEER_APPROVAL_REQUIRED_FLAG,source.AUTO_USE_ALLOWED_FLAG,
    source.OFFICIAL_COST_IMPACT_ALLOWED_FLAG,source.BUSINESS_DECISION_ALLOWED_FLAG,
    source.FALLBACK_SOURCE,source.FALLBACK_FIELD_NAME,source.POLICY_CONFIG,
    source.EFFECTIVE_FROM,source.EFFECTIVE_TO,source.APPROVED_BY,source.APPROVED_AT,
    source.COMMENTS
);

CREATE OR REPLACE VIEW VW_ML_DECISION_POLICY_CURRENT_V1 AS
SELECT *
FROM ML_DECISION_POLICY_V1
WHERE POLICY_STATUS = 'ACTIVE'
  AND EFFECTIVE_FROM <= CURRENT_TIMESTAMP()
  AND (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO > CURRENT_TIMESTAMP())
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY MODEL_DOMAIN
    ORDER BY EFFECTIVE_FROM DESC, CREATED_AT DESC
) = 1;

CREATE OR REPLACE PROCEDURE ACTIVATE_ML_DECISION_POLICY_V1(
    P_MODEL_DOMAIN VARCHAR,
    P_POLICY_VERSION VARCHAR,
    P_APPROVED_BY VARCHAR
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    V_POLICY_COUNT NUMBER DEFAULT 0;
    V_DEPLOYMENT_MODE VARCHAR;
    V_AUTO_USE_ALLOWED BOOLEAN;
    V_COST_IMPACT_ALLOWED BOOLEAN;
    V_BUSINESS_DECISION_ALLOWED BOOLEAN;
BEGIN
    IF (P_MODEL_DOMAIN IS NULL OR LENGTH(TRIM(P_MODEL_DOMAIN)) = 0) THEN
        RETURN OBJECT_CONSTRUCT(''status'',''ERROR'',''message'',''P_MODEL_DOMAIN is required.'');
    END IF;

    IF (P_POLICY_VERSION IS NULL OR LENGTH(TRIM(P_POLICY_VERSION)) = 0) THEN
        RETURN OBJECT_CONSTRUCT(''status'',''ERROR'',''message'',''P_POLICY_VERSION is required.'');
    END IF;

    IF (P_APPROVED_BY IS NULL OR LENGTH(TRIM(P_APPROVED_BY)) = 0) THEN
        RETURN OBJECT_CONSTRUCT(''status'',''ERROR'',''message'',''P_APPROVED_BY is required.'');
    END IF;

    SELECT COUNT(*), MAX(DEPLOYMENT_MODE), MAX(AUTO_USE_ALLOWED_FLAG),
           MAX(OFFICIAL_COST_IMPACT_ALLOWED_FLAG), MAX(BUSINESS_DECISION_ALLOWED_FLAG)
    INTO :V_POLICY_COUNT, :V_DEPLOYMENT_MODE, :V_AUTO_USE_ALLOWED,
         :V_COST_IMPACT_ALLOWED, :V_BUSINESS_DECISION_ALLOWED
    FROM ML_DECISION_POLICY_V1
    WHERE MODEL_DOMAIN = UPPER(:P_MODEL_DOMAIN)
      AND POLICY_VERSION = :P_POLICY_VERSION
      AND POLICY_STATUS = ''DRAFT'';

    IF (V_POLICY_COUNT <> 1) THEN
        RETURN OBJECT_CONSTRUCT(''status'',''ERROR'',''message'',''Exactly one DRAFT policy must exist.'');
    END IF;

    IF (V_DEPLOYMENT_MODE = ''SHADOW'' AND
        (V_AUTO_USE_ALLOWED OR V_COST_IMPACT_ALLOWED OR V_BUSINESS_DECISION_ALLOWED)) THEN
        RETURN OBJECT_CONSTRUCT(''status'',''ERROR'',''message'',''SHADOW policies cannot allow automatic use, cost impact, or business decisions.'');
    END IF;

    IF (UPPER(P_MODEL_DOMAIN) = ''BMCS'' AND V_COST_IMPACT_ALLOWED) THEN
        RETURN OBJECT_CONSTRUCT(''status'',''ERROR'',''message'',''BMCS can never directly affect cost.'');
    END IF;

    IF (V_AUTO_USE_ALLOWED AND NOT V_BUSINESS_DECISION_ALLOWED) THEN
        RETURN OBJECT_CONSTRUCT(''status'',''ERROR'',''message'',''Automatic use requires business-decision permission.'');
    END IF;

    UPDATE ML_DECISION_POLICY_V1
    SET POLICY_STATUS = ''RETIRED'', EFFECTIVE_TO = CURRENT_TIMESTAMP(), UPDATED_AT = CURRENT_TIMESTAMP()
    WHERE MODEL_DOMAIN = UPPER(:P_MODEL_DOMAIN)
      AND POLICY_STATUS = ''ACTIVE'';

    UPDATE ML_DECISION_POLICY_V1
    SET POLICY_STATUS = ''ACTIVE'', EFFECTIVE_FROM = CURRENT_TIMESTAMP(), EFFECTIVE_TO = NULL,
        APPROVED_BY = :P_APPROVED_BY, APPROVED_AT = CURRENT_TIMESTAMP(), UPDATED_AT = CURRENT_TIMESTAMP()
    WHERE MODEL_DOMAIN = UPPER(:P_MODEL_DOMAIN)
      AND POLICY_VERSION = :P_POLICY_VERSION
      AND POLICY_STATUS = ''DRAFT'';

    RETURN OBJECT_CONSTRUCT(
        ''status'',''SUCCESS'',
        ''model_domain'',UPPER(P_MODEL_DOMAIN),
        ''policy_version'',P_POLICY_VERSION,
        ''deployment_mode'',V_DEPLOYMENT_MODE,
        ''approved_by'',P_APPROVED_BY
    );
END;
';

SELECT * FROM VW_ML_DECISION_POLICY_CURRENT_V1 ORDER BY MODEL_DOMAIN;

SELECT
    MODEL_DOMAIN,
    POLICY_VERSION,
    POLICY_STATUS,
    DEPLOYMENT_MODE,
    DECISION_TYPE,
    RAW_ML_OUTPUT_NAME,
    FINAL_OUTPUT_NAME,
    FALLBACK_SOURCE,
    QUALITY_PASS_REQUIRED_FLAG,
    OOD_USE_ALLOWED_FLAG,
    AUTO_USE_ALLOWED_FLAG,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG,
    POLICY_CONFIG
FROM VW_ML_DECISION_POLICY_CURRENT_V1
ORDER BY MODEL_DOMAIN;

SELECT
    MODEL_DOMAIN,
    COUNT_IF(POLICY_STATUS = 'ACTIVE') AS ACTIVE_POLICY_COUNT
FROM ML_DECISION_POLICY_V1
GROUP BY MODEL_DOMAIN
HAVING COUNT_IF(POLICY_STATUS = 'ACTIVE') <> 1;

SELECT
    COUNT_IF(
        DEPLOYMENT_MODE = 'SHADOW'
        AND (
            AUTO_USE_ALLOWED_FLAG = TRUE
            OR OFFICIAL_COST_IMPACT_ALLOWED_FLAG = TRUE
            OR BUSINESS_DECISION_ALLOWED_FLAG = TRUE
        )
    ) AS INVALID_SHADOW_POLICY_ROWS,
    COUNT_IF(
        MODEL_DOMAIN = 'BMCS'
        AND OFFICIAL_COST_IMPACT_ALLOWED_FLAG = TRUE
    ) AS INVALID_BMCS_COST_POLICY_ROWS
FROM ML_DECISION_POLICY_V1
WHERE POLICY_STATUS = 'ACTIVE';

-- ============================================================
-- PHASE 9B — UNIFIED DECISION PROCEDURE
--
-- Resolves CSS, FMIS, TDS and BMCS through the active Phase 9A
-- policy. Current SHADOW policies always preserve the existing
-- deterministic or Phase 7 official result.
-- ============================================================

