USE ROLE SYSADMIN;
USE WAREHOUSE KMAT_WH;
USE DATABASE KMAT_COST_MODEL_DB;
USE SCHEMA CORE_ML;

-- ============================================================
-- PHASE 8E.1-8E.3
-- BMCS V2 evidence validation, reviewed labels and
-- leakage-safe feature dataset.
--
-- Upload bmcs_v2_engineer_reviewed_data.csv to:
-- @KMAT_COST_MODEL_DB.CORE_ML.ML_SYNTHETIC_STAGE/
-- ============================================================


CREATE OR REPLACE TABLE BMCS_SYNTHETIC_RAW_V2 (
    RFQ_CONFIG_VERSION_ID VARCHAR,
    RFQ_ID VARCHAR,
    FEATURE_AS_OF_TIMESTAMP TIMESTAMP_NTZ,
    REVIEWED_AT TIMESTAMP_NTZ,

    SOURCE_LANGUAGE VARCHAR,
    DOCUMENT_LENGTH_CHARS NUMBER,
    PAGE_COUNT NUMBER,
    OCR_QUALITY_SCORE FLOAT,
    DOCUMENT_COMPLEXITY_SCORE FLOAT,

    AMBIGUITY_TERM_COUNT NUMBER,
    CONFLICTING_PHRASE_COUNT NUMBER,
    UNSUPPORTED_VALUE_COUNT NUMBER,
    SYNONYM_MATCH_STRENGTH FLOAT,

    TRANSLATION_USED_FLAG NUMBER,
    TRANSLATION_QUALITY_SCORE FLOAT,
    SOURCE_TEXT_PRESENT_FLAG NUMBER,

    EXTRACTED_ENGINE VARCHAR,
    EXTRACTED_CAB VARCHAR,
    EXTRACTED_WHEEL VARCHAR,
    EXTRACTED_COLOR VARCHAR,

    ENGINE_EXTRACTION_CONFIDENCE FLOAT,
    CAB_EXTRACTION_CONFIDENCE FLOAT,
    WHEEL_EXTRACTION_CONFIDENCE FLOAT,
    COLOR_EXTRACTION_CONFIDENCE FLOAT,

    ENGINE_TEXT_EVIDENCE_FLAG NUMBER,
    CAB_TEXT_EVIDENCE_FLAG NUMBER,
    WHEEL_TEXT_EVIDENCE_FLAG NUMBER,
    COLOR_TEXT_EVIDENCE_FLAG NUMBER,

    VALID_EXTRACTED_VALUE_COUNT NUMBER,
    TEXT_SUPPORTED_VALUE_COUNT NUMBER,
    MISSING_REQUIREMENT_COUNT NUMBER,
    EXACT_PHRASE_MATCH_COUNT NUMBER,
    SYNONYM_MATCH_COUNT NUMBER,
    RULE_VALIDATION_PASS_COUNT NUMBER,

    CORTEX_EXTRACTION_STATUS VARCHAR,
    CORTEX_REASONING_AVAILABLE_FLAG NUMBER,

    RULE_BMCS_SCORE FLOAT,
    CORTEX_CONFIDENCE_SCORE FLOAT,
    DEVELOPMENT_HYBRID_BMCS_SCORE FLOAT,

    ENGINEER_FINAL_ENGINE VARCHAR,
    ENGINEER_FINAL_CAB VARCHAR,
    ENGINEER_FINAL_WHEEL VARCHAR,
    ENGINEER_FINAL_COLOR VARCHAR,

    ENGINEER_CORRECTION_COUNT NUMBER,
    ENGINEER_ACCEPTED_WITHOUT_CHANGE_FLAG NUMBER,
    FINAL_REVIEW_OUTCOME VARCHAR,
    REVIEWER_ROLE VARCHAR,

    CORRECT_MAPPING_FLAG NUMBER
);


TRUNCATE TABLE BMCS_SYNTHETIC_RAW_V2;


COPY INTO BMCS_SYNTHETIC_RAW_V2
FROM @KMAT_COST_MODEL_DB.CORE_ML.ML_SYNTHETIC_STAGE/bmcs_v2_engineer_reviewed_data.csv
FILE_FORMAT = (
    FORMAT_NAME =
        KMAT_COST_MODEL_DB.CORE_ML.PHASE8_CSV_FORMAT
)
ON_ERROR = 'ABORT_STATEMENT'
FORCE = TRUE;


-- Chronological split based only on the pre-review timestamp.
CREATE OR REPLACE VIEW BMCS_SYNTHETIC_SPLIT_V2 AS
SELECT
    raw.*,

    CASE
        WHEN FEATURE_AS_OF_TIMESTAMP
             < TO_TIMESTAMP_NTZ('2025-01-01 00:00:00')
            THEN 'TRAIN'

        WHEN FEATURE_AS_OF_TIMESTAMP
             < TO_TIMESTAMP_NTZ('2025-07-01 00:00:00')
            THEN 'VALIDATION'

        WHEN FEATURE_AS_OF_TIMESTAMP
             < TO_TIMESTAMP_NTZ('2026-01-01 00:00:00')
            THEN 'TEST'

        ELSE 'EXCLUDED'
    END AS DATA_SPLIT,

    'BMCS_SPLIT_V2' AS SPLIT_VERSION

FROM BMCS_SYNTHETIC_RAW_V2 raw;


-- Engineer-reviewed labels remain in a separate governed object.
CREATE OR REPLACE VIEW BMCS_LABEL_DATASET_V2 AS
SELECT
    RFQ_CONFIG_VERSION_ID AS ENTITY_ID,
    RFQ_ID,
    REVIEWED_AT,

    ENGINEER_FINAL_ENGINE,
    ENGINEER_FINAL_CAB,
    ENGINEER_FINAL_WHEEL,
    ENGINEER_FINAL_COLOR,

    ENGINEER_CORRECTION_COUNT,
    ENGINEER_ACCEPTED_WITHOUT_CHANGE_FLAG,
    FINAL_REVIEW_OUTCOME,
    REVIEWER_ROLE,

    CORRECT_MAPPING_FLAG AS TARGET_CORRECT_MAPPING_FLAG,

    'ENGINEER_REVIEWED_SYNTHETIC'
        AS LABEL_SOURCE,

    'BMCS_LABELS_V2'
        AS LABEL_VERSION

FROM BMCS_SYNTHETIC_SPLIT_V2;


-- Prediction-time evidence only.
CREATE OR REPLACE VIEW BMCS_FEATURE_DATASET_V2 AS
SELECT
    RFQ_CONFIG_VERSION_ID AS ENTITY_ID,
    RFQ_ID,

    FEATURE_AS_OF_TIMESTAMP,
    TO_DATE(FEATURE_AS_OF_TIMESTAMP)
        AS FEATURE_AS_OF_DATE,

    DATA_SPLIT,

    'BMCS_FEATURES_V2'
        AS FEATURE_SET_VERSION,

    'SYNTHETIC'
        AS SOURCE_DATA_CLASS,

    SOURCE_LANGUAGE,
    DOCUMENT_LENGTH_CHARS,
    PAGE_COUNT,
    OCR_QUALITY_SCORE,
    DOCUMENT_COMPLEXITY_SCORE,

    AMBIGUITY_TERM_COUNT,
    CONFLICTING_PHRASE_COUNT,
    UNSUPPORTED_VALUE_COUNT,
    SYNONYM_MATCH_STRENGTH,

    TRANSLATION_USED_FLAG,
    TRANSLATION_QUALITY_SCORE,
    SOURCE_TEXT_PRESENT_FLAG,

    EXTRACTED_ENGINE,
    EXTRACTED_CAB,
    EXTRACTED_WHEEL,
    EXTRACTED_COLOR,

    ENGINE_EXTRACTION_CONFIDENCE,
    CAB_EXTRACTION_CONFIDENCE,
    WHEEL_EXTRACTION_CONFIDENCE,
    COLOR_EXTRACTION_CONFIDENCE,

    ENGINE_TEXT_EVIDENCE_FLAG,
    CAB_TEXT_EVIDENCE_FLAG,
    WHEEL_TEXT_EVIDENCE_FLAG,
    COLOR_TEXT_EVIDENCE_FLAG,

    VALID_EXTRACTED_VALUE_COUNT,
    TEXT_SUPPORTED_VALUE_COUNT,
    MISSING_REQUIREMENT_COUNT,
    EXACT_PHRASE_MATCH_COUNT,
    SYNONYM_MATCH_COUNT,
    RULE_VALIDATION_PASS_COUNT,

    CORTEX_EXTRACTION_STATUS,
    CORTEX_REASONING_AVAILABLE_FLAG,

    RULE_BMCS_SCORE,
    CORTEX_CONFIDENCE_SCORE,
    DEVELOPMENT_HYBRID_BMCS_SCORE,

    IFF(
        SOURCE_TEXT_PRESENT_FLAG = 1
        AND OCR_QUALITY_SCORE BETWEEN 0 AND 1
        AND SYNONYM_MATCH_STRENGTH BETWEEN 0 AND 1
        AND TRANSLATION_QUALITY_SCORE BETWEEN 0 AND 1
        AND ENGINE_EXTRACTION_CONFIDENCE BETWEEN 0 AND 1
        AND CAB_EXTRACTION_CONFIDENCE BETWEEN 0 AND 1
        AND WHEEL_EXTRACTION_CONFIDENCE BETWEEN 0 AND 1
        AND COLOR_EXTRACTION_CONFIDENCE BETWEEN 0 AND 1
        AND VALID_EXTRACTED_VALUE_COUNT BETWEEN 0 AND 4
        AND TEXT_SUPPORTED_VALUE_COUNT BETWEEN 0 AND 4
        AND MISSING_REQUIREMENT_COUNT BETWEEN 0 AND 4,
        TRUE,
        FALSE
    ) AS FEATURE_QUALITY_PASS_FLAG

FROM BMCS_SYNTHETIC_SPLIT_V2;


-- Final model-ready object.
-- Engineer-final fields and review outcomes are excluded.
CREATE OR REPLACE VIEW BMCS_MODEL_DATASET_V2 AS
SELECT
    feature.ENTITY_ID,
    feature.RFQ_ID,
    feature.FEATURE_AS_OF_TIMESTAMP,
    feature.FEATURE_AS_OF_DATE,
    feature.DATA_SPLIT,

    feature.SOURCE_LANGUAGE,
    feature.DOCUMENT_LENGTH_CHARS,
    feature.PAGE_COUNT,
    feature.OCR_QUALITY_SCORE,
    feature.DOCUMENT_COMPLEXITY_SCORE,

    feature.AMBIGUITY_TERM_COUNT,
    feature.CONFLICTING_PHRASE_COUNT,
    feature.UNSUPPORTED_VALUE_COUNT,
    feature.SYNONYM_MATCH_STRENGTH,

    feature.TRANSLATION_USED_FLAG,
    feature.TRANSLATION_QUALITY_SCORE,
    feature.SOURCE_TEXT_PRESENT_FLAG,

    feature.EXTRACTED_ENGINE,
    feature.EXTRACTED_CAB,
    feature.EXTRACTED_WHEEL,
    feature.EXTRACTED_COLOR,

    feature.ENGINE_EXTRACTION_CONFIDENCE,
    feature.CAB_EXTRACTION_CONFIDENCE,
    feature.WHEEL_EXTRACTION_CONFIDENCE,
    feature.COLOR_EXTRACTION_CONFIDENCE,

    feature.ENGINE_TEXT_EVIDENCE_FLAG,
    feature.CAB_TEXT_EVIDENCE_FLAG,
    feature.WHEEL_TEXT_EVIDENCE_FLAG,
    feature.COLOR_TEXT_EVIDENCE_FLAG,

    feature.VALID_EXTRACTED_VALUE_COUNT,
    feature.TEXT_SUPPORTED_VALUE_COUNT,
    feature.MISSING_REQUIREMENT_COUNT,
    feature.EXACT_PHRASE_MATCH_COUNT,
    feature.SYNONYM_MATCH_COUNT,
    feature.RULE_VALIDATION_PASS_COUNT,

    feature.CORTEX_EXTRACTION_STATUS,
    feature.CORTEX_REASONING_AVAILABLE_FLAG,

    feature.RULE_BMCS_SCORE,
    feature.CORTEX_CONFIDENCE_SCORE,
    feature.DEVELOPMENT_HYBRID_BMCS_SCORE,

    label.TARGET_CORRECT_MAPPING_FLAG

FROM BMCS_FEATURE_DATASET_V2 feature
JOIN BMCS_LABEL_DATASET_V2 label
  ON feature.ENTITY_ID = label.ENTITY_ID

WHERE feature.FEATURE_QUALITY_PASS_FLAG = TRUE
  AND feature.DATA_SPLIT IN (
      'TRAIN',
      'VALIDATION',
      'TEST'
  );


-- ============================================================
-- FEATURE-SET REGISTRY
-- ============================================================

MERGE INTO FEATURE_SET_REGISTRY target
USING (
    SELECT
        'BMCS_FEATURES' AS FEATURE_SET_NAME,
        'V2' AS FEATURE_SET_VERSION,
        'BINARY_CLASSIFICATION' AS PREDICTION_TYPE,
        'ONE_RFQ_CONFIGURATION_VERSION' AS ENTITY_GRAIN,
        'TARGET_CORRECT_MAPPING_FLAG'
            AS TARGET_COLUMN_NAME,
        'CORE_ML.BMCS_MODEL_DATASET_V2'
            AS SOURCE_OBJECT_NAME,
        'DEVELOPMENT'
            AS STATUS,
        'Synthetic BMCS point-in-time evidence with separate engineer-reviewed labels. Engineer-final fields and review outcomes are excluded from model inputs.'
            AS NOTES
) source

ON target.FEATURE_SET_NAME =
    source.FEATURE_SET_NAME
AND target.FEATURE_SET_VERSION =
    source.FEATURE_SET_VERSION

WHEN MATCHED THEN UPDATE SET
    PREDICTION_TYPE =
        source.PREDICTION_TYPE,
    ENTITY_GRAIN =
        source.ENTITY_GRAIN,
    TARGET_COLUMN_NAME =
        source.TARGET_COLUMN_NAME,
    SOURCE_OBJECT_NAME =
        source.SOURCE_OBJECT_NAME,
    STATUS =
        source.STATUS,
    NOTES =
        source.NOTES

WHEN NOT MATCHED THEN INSERT (
    FEATURE_SET_NAME,
    FEATURE_SET_VERSION,
    PREDICTION_TYPE,
    ENTITY_GRAIN,
    TARGET_COLUMN_NAME,
    SOURCE_OBJECT_NAME,
    STATUS,
    NOTES
)
VALUES (
    source.FEATURE_SET_NAME,
    source.FEATURE_SET_VERSION,
    source.PREDICTION_TYPE,
    source.ENTITY_GRAIN,
    source.TARGET_COLUMN_NAME,
    source.SOURCE_OBJECT_NAME,
    source.STATUS,
    source.NOTES
);


-- ============================================================
-- VALIDATION GATES
-- ============================================================

-- Expected:
-- TOTAL_RAW_ROWS = 24000
-- DISTINCT_ENTITIES = 24000
-- NULL_LABELS = 0
SELECT
    COUNT(*) AS TOTAL_RAW_ROWS,
    COUNT(DISTINCT RFQ_CONFIG_VERSION_ID)
        AS DISTINCT_ENTITIES,
    COUNT_IF(CORRECT_MAPPING_FLAG IS NULL)
        AS NULL_LABELS,
    MIN(FEATURE_AS_OF_TIMESTAMP)
        AS MIN_FEATURE_TIMESTAMP,
    MAX(FEATURE_AS_OF_TIMESTAMP)
        AS MAX_FEATURE_TIMESTAMP
FROM BMCS_SYNTHETIC_RAW_V2;


-- Expected zero rows.
SELECT
    RFQ_CONFIG_VERSION_ID,
    COUNT(*) AS DUPLICATE_COUNT
FROM BMCS_SYNTHETIC_RAW_V2
GROUP BY RFQ_CONFIG_VERSION_ID
HAVING COUNT(*) > 1;


-- Expected zero invalid chronology rows.
SELECT
    COUNT_IF(
        REVIEWED_AT <= FEATURE_AS_OF_TIMESTAMP
    ) AS INVALID_REVIEW_CHRONOLOGY_ROWS
FROM BMCS_SYNTHETIC_RAW_V2;


-- Review chronological split and label balance.
SELECT
    DATA_SPLIT,
    COUNT(*) AS ROW_COUNT,

    MIN(FEATURE_AS_OF_TIMESTAMP)
        AS MIN_FEATURE_TIMESTAMP,

    MAX(FEATURE_AS_OF_TIMESTAMP)
        AS MAX_FEATURE_TIMESTAMP,

    COUNT_IF(CORRECT_MAPPING_FLAG = 1)
        AS CORRECT_MAPPING_ROWS,

    COUNT_IF(CORRECT_MAPPING_FLAG = 0)
        AS INCORRECT_MAPPING_ROWS,

    ROUND(
        100.0
        * COUNT_IF(CORRECT_MAPPING_FLAG = 1)
        / COUNT(*),
        3
    ) AS CORRECT_MAPPING_PCT

FROM BMCS_SYNTHETIC_SPLIT_V2
GROUP BY DATA_SPLIT
ORDER BY
    CASE DATA_SPLIT
        WHEN 'TRAIN' THEN 1
        WHEN 'VALIDATION' THEN 2
        WHEN 'TEST' THEN 3
        ELSE 4
    END;


-- Expected zero inconsistent label rows.
SELECT
    COUNT_IF(
        CORRECT_MAPPING_FLAG = 1
        AND ENGINEER_CORRECTION_COUNT <> 0
    ) AS INCORRECT_POSITIVE_LABEL_ROWS,

    COUNT_IF(
        CORRECT_MAPPING_FLAG = 0
        AND ENGINEER_CORRECTION_COUNT = 0
    ) AS INCORRECT_NEGATIVE_LABEL_ROWS,

    COUNT_IF(
        ENGINEER_ACCEPTED_WITHOUT_CHANGE_FLAG = 1
        AND CORRECT_MAPPING_FLAG <> 1
    ) AS INVALID_ACCEPTED_ROWS

FROM BMCS_SYNTHETIC_RAW_V2;


-- Expected all null counts = 0 in the model-ready dataset.
SELECT
    COUNT_IF(SOURCE_LANGUAGE IS NULL)
        AS NULL_LANGUAGE,

    COUNT_IF(OCR_QUALITY_SCORE IS NULL)
        AS NULL_OCR_QUALITY,

    COUNT_IF(EXTRACTED_ENGINE IS NULL)
        AS NULL_ENGINE,

    COUNT_IF(EXTRACTED_CAB IS NULL)
        AS NULL_CAB,

    COUNT_IF(EXTRACTED_WHEEL IS NULL)
        AS NULL_WHEEL,

    COUNT_IF(EXTRACTED_COLOR IS NULL)
        AS NULL_COLOR,

    COUNT_IF(RULE_BMCS_SCORE IS NULL)
        AS NULL_RULE_SCORE,

    COUNT_IF(CORTEX_CONFIDENCE_SCORE IS NULL)
        AS NULL_CORTEX_SCORE,

    COUNT_IF(TARGET_CORRECT_MAPPING_FLAG IS NULL)
        AS NULL_TARGET

FROM BMCS_MODEL_DATASET_V2;


-- Leakage check: expected zero rows.
SELECT
    COLUMN_NAME
FROM KMAT_COST_MODEL_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE_ML'
  AND TABLE_NAME = 'BMCS_MODEL_DATASET_V2'
  AND COLUMN_NAME IN (
      'REVIEWED_AT',
      'ENGINEER_FINAL_ENGINE',
      'ENGINEER_FINAL_CAB',
      'ENGINEER_FINAL_WHEEL',
      'ENGINEER_FINAL_COLOR',
      'ENGINEER_CORRECTION_COUNT',
      'ENGINEER_ACCEPTED_WITHOUT_CHANGE_FLAG',
      'FINAL_REVIEW_OUTCOME',
      'REVIEWER_ROLE'
  );


-- Evidence and language coverage review.
SELECT
    SOURCE_LANGUAGE,
    DATA_SPLIT,
    COUNT(*) AS ROW_COUNT,
    AVG(OCR_QUALITY_SCORE) AS AVG_OCR_QUALITY,
    AVG(TARGET_CORRECT_MAPPING_FLAG)
        AS CORRECT_MAPPING_RATE,
    AVG(MISSING_REQUIREMENT_COUNT)
        AS AVG_MISSING_REQUIREMENTS,
    AVG(AMBIGUITY_TERM_COUNT)
        AS AVG_AMBIGUITY_COUNT
FROM BMCS_MODEL_DATASET_V2
GROUP BY SOURCE_LANGUAGE, DATA_SPLIT
ORDER BY SOURCE_LANGUAGE, DATA_SPLIT;


-- Development benchmark diagnostics.
-- Thresholds are exploratory only and are not Phase 9 policy.
SELECT
    DATA_SPLIT,

    COUNT(*) AS ROW_COUNT,

    AVG(
        IFF(
            DEVELOPMENT_HYBRID_BMCS_SCORE >= 75,
            1,
            0
        )
    ) AS DEVELOPMENT_AUTO_APPROVAL_RATE,

    AVG(
        IFF(
            DEVELOPMENT_HYBRID_BMCS_SCORE >= 75
            AND TARGET_CORRECT_MAPPING_FLAG = 0,
            1,
            0
        )
    ) AS INCORRECT_AUTO_APPROVAL_RATE,

    AVG(
        IFF(
            DEVELOPMENT_HYBRID_BMCS_SCORE < 75
            AND TARGET_CORRECT_MAPPING_FLAG = 1,
            1,
            0
        )
    ) AS CORRECT_MAPPING_REVIEW_RATE

FROM BMCS_MODEL_DATASET_V2
GROUP BY DATA_SPLIT
ORDER BY
    CASE DATA_SPLIT
        WHEN 'TRAIN' THEN 1
        WHEN 'VALIDATION' THEN 2
        WHEN 'TEST' THEN 3
        ELSE 4
    END;
