USE ROLE SYSADMIN;
USE WAREHOUSE KMAT_WH;
USE DATABASE KMAT_COST_MODEL_DB;
USE SCHEMA CORE_ML;

-- ============================================================
-- PHASE 8E.4–8E.7 REVIEW QUERIES
-- ============================================================

SELECT *
FROM BMCS_ML_RUN_LOG_V2
ORDER BY CREATED_AT DESC;


SELECT
    MODEL_NAME,
    MODEL_TYPE,
    ROW_COUNT,
    ROC_AUC,
    PR_AUC,
    BRIER_SCORE,
    LOG_LOSS,
    ECE_10_BIN,
    PRECISION_AT_050,
    RECALL_AT_050,
    HYBRID_PR_AUC_GATE_FLAG,
    HYBRID_BRIER_GATE_FLAG,
    SELECTION_ELIGIBLE_FLAG,
    SELECTION_SCORE,
    SELECTED_MODEL_FLAG
FROM BMCS_VALIDATION_MODEL_METRICS_V2
ORDER BY
    SELECTED_MODEL_FLAG DESC,
    SELECTION_SCORE;


SELECT
    MODEL_NAME,
    CALIBRATION_METHOD,
    ROW_COUNT,
    ROC_AUC,
    PR_AUC,
    BRIER_SCORE,
    LOG_LOSS,
    ECE_10_BIN,
    CALIBRATION_SELECTION_SCORE,
    SELECTED_CALIBRATION_FLAG
FROM BMCS_CALIBRATION_METRICS_V2
ORDER BY
    SELECTED_CALIBRATION_FLAG DESC,
    CALIBRATION_SELECTION_SCORE;


SELECT *
FROM BMCS_SELECTED_MODEL_POLICY_V2;


SELECT *
FROM BMCS_TEST_EVALUATION_V2;


SELECT
    SEGMENT_TYPE,
    SEGMENT_VALUE,
    ROW_COUNT,
    CORRECT_MAPPING_RATE,
    ROC_AUC,
    PR_AUC,
    BRIER_SCORE,
    ECE_10_BIN,
    AUTO_APPROVAL_RATE,
    INCORRECT_AUTO_APPROVAL_RATE,
    AUTO_REJECTION_RATE,
    CORRECT_MAPPING_REJECTION_RATE,
    ENGINEERING_REVIEW_RATE
FROM BMCS_TEST_SEGMENT_METRICS_V2
ORDER BY
    SEGMENT_TYPE,
    BRIER_SCORE DESC;


SELECT
    IMPORTANCE_RANK,
    FEATURE_NAME,
    IMPORTANCE_SCORE
FROM BMCS_FEATURE_IMPORTANCE_V2
WHERE IMPORTANCE_RANK <= 25
ORDER BY IMPORTANCE_RANK;


SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT ENTITY_ID)
        AS DISTINCT_ENTITIES,

    COUNT_IF(
        CALIBRATED_CORRECT_MAPPING_PROBABILITY
        IS NULL
    ) AS NULL_PROBABILITIES,

    COUNT_IF(
        CALIBRATED_CORRECT_MAPPING_PROBABILITY
            < 0
        OR
        CALIBRATED_CORRECT_MAPPING_PROBABILITY
            > 1
    ) AS INVALID_PROBABILITY_ROWS,

    COUNT_IF(
        ML_BMCS_SCORE < 0
        OR ML_BMCS_SCORE > 100
    ) AS INVALID_BMCS_SCORE_ROWS,

    COUNT_IF(
        DEPLOYMENT_MODE <> 'SHADOW'
        OR ML_ADVISORY_ONLY_FLAG <> TRUE
        OR OFFICIAL_COST_IMPACT_ALLOWED_FLAG
            <> FALSE
        OR BUSINESS_DECISION_ALLOWED_FLAG
            <> FALSE
    ) AS INVALID_AUTHORITY_ROWS

FROM BMCS_TEST_PREDICTIONS_V2;

SELECT *
FROM KMAT_COST_MODEL_DB.CORE_ML.BMCS_ML_RUN_LOG_V2
ORDER BY CREATED_AT DESC;

SELECT *
FROM KMAT_COST_MODEL_DB.CORE_ML.BMCS_TEST_EVALUATION_V2;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT ENTITY_ID) AS DISTINCT_ENTITIES,

    COUNT_IF(
        CALIBRATED_CORRECT_MAPPING_PROBABILITY IS NULL
    ) AS NULL_PROBABILITIES,

    COUNT_IF(
        CALIBRATED_CORRECT_MAPPING_PROBABILITY < 0
        OR CALIBRATED_CORRECT_MAPPING_PROBABILITY > 1
    ) AS INVALID_PROBABILITY_ROWS,

    COUNT_IF(
        ML_BMCS_SCORE < 0
        OR ML_BMCS_SCORE > 100
    ) AS INVALID_BMCS_SCORE_ROWS,

    COUNT_IF(
        DEPLOYMENT_MODE <> 'SHADOW'
        OR ML_ADVISORY_ONLY_FLAG <> TRUE
        OR OFFICIAL_COST_IMPACT_ALLOWED_FLAG <> FALSE
        OR BUSINESS_DECISION_ALLOWED_FLAG <> FALSE
    ) AS INVALID_AUTHORITY_ROWS

FROM KMAT_COST_MODEL_DB.CORE_ML.BMCS_TEST_PREDICTIONS_V2;


-- BMCS SHADOW REVIEW SCRIPT

USE DATABASE KMAT_COST_MODEL_DB;
USE SCHEMA CORE_ML;

CREATE OR REPLACE TABLE KMAT_COST_MODEL_DB.CORE_ML.BMCS_THRESHOLD_POLICY_DECISION_V2 AS
SELECT
    MODEL_NAME,
    MODEL_VERSION,
    CALIBRATION_METHOD,
    LOW_THRESHOLD,
    HIGH_THRESHOLD,
    0.02 AS APPROVED_AUTO_APPROVAL_ERROR_LIMIT,
    INCORRECT_AUTO_APPROVAL_RATE
        AS OBSERVED_AUTO_APPROVAL_ERROR_RATE,
    0.05 AS APPROVED_AUTO_REJECTION_ERROR_LIMIT,
    CORRECT_MAPPING_REJECTION_RATE
        AS OBSERVED_AUTO_REJECTION_ERROR_RATE,
    AUTO_APPROVAL_ROWS,
    AUTO_REJECTION_ROWS,
    ENGINEERING_REVIEW_ROWS,
    CASE
        WHEN INCORRECT_AUTO_APPROVAL_RATE <= 0.02
         AND CORRECT_MAPPING_REJECTION_RATE <= 0.05
            THEN 'ACCEPTED_FOR_SHADOW_AUTOMATION'
        ELSE 'REJECTED_ON_TEST'
    END AS THRESHOLD_POLICY_STATUS,
    'The calibrated probability model is retained for shadow advisory scoring. Automatic approval and rejection are disabled because the locked test thresholds exceeded approved error limits.'
        AS DECISION_REASON,
    'SHADOW' AS DEPLOYMENT_MODE,
    FALSE AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    FALSE AS BUSINESS_DECISION_ALLOWED_FLAG,
    CURRENT_TIMESTAMP() AS DECIDED_AT
FROM KMAT_COST_MODEL_DB.CORE_ML.BMCS_TEST_EVALUATION_V2;

CREATE OR REPLACE VIEW BMCS_FINAL_TEST_SHADOW_OUTPUT_V2 AS
SELECT
    feature.ENTITY_ID,
    feature.RFQ_ID,
    feature.FEATURE_AS_OF_TIMESTAMP,
    feature.FEATURE_AS_OF_DATE,
    feature.SOURCE_LANGUAGE,
    feature.FEATURE_QUALITY_PASS_FLAG,
    feature.CORTEX_EXTRACTION_STATUS,
    feature.EXTRACTED_ENGINE,
    feature.EXTRACTED_CAB,
    feature.EXTRACTED_WHEEL,
    feature.EXTRACTED_COLOR,
    feature.RULE_BMCS_SCORE,
    feature.CORTEX_CONFIDENCE_SCORE,
    feature.DEVELOPMENT_HYBRID_BMCS_SCORE,
    prediction.RAW_ML_CORRECT_MAPPING_PROBABILITY,
    prediction.CALIBRATED_CORRECT_MAPPING_PROBABILITY,
    prediction.ML_BMCS_SCORE,
    IFF(
        prediction.ENTITY_ID IS NOT NULL,
        TRUE,
        FALSE
    ) AS ML_SCORING_COMPLETED_FLAG,
    CASE
        WHEN feature.FEATURE_QUALITY_PASS_FLAG = FALSE
            THEN 'FEATURE_QUALITY_GATE_FAILED'
        WHEN prediction.ENTITY_ID IS NULL
            THEN 'ML_PREDICTION_NOT_AVAILABLE'
        ELSE NULL
    END AS ML_FALLBACK_REASON,
    CASE
        WHEN prediction.ENTITY_ID IS NULL
            THEN 'DATA_QUALITY_FALLBACK'
        WHEN prediction.CALIBRATED_CORRECT_MAPPING_PROBABILITY
             >= 0.945
            THEN 'HIGH_CONFIDENCE_ADVISORY'
        WHEN prediction.CALIBRATED_CORRECT_MAPPING_PROBABILITY
             <= 0.485
            THEN 'LOW_CONFIDENCE_ADVISORY'
        ELSE 'MEDIUM_CONFIDENCE_ADVISORY'
    END AS ML_ADVISORY_TRUST_BAND,
    'ENGINEERING_REVIEW_REQUIRED'
        AS SHADOW_REVIEW_ACTION,
    'REJECTED_ON_TEST_FOR_AUTOMATION'
        AS THRESHOLD_POLICY_STATUS,
    'PHASE7_RULE_CORTEX_HYBRID'
        AS OFFICIAL_TRUST_SOURCE,
    'XGB_V1_BALANCED'
        AS EXPERIMENT_MODEL_NAME,
    'V2'
        AS EXPERIMENT_MODEL_VERSION,
    'ISOTONIC'
        AS CALIBRATION_METHOD,
    'BMCS_FEATURES_V2'
        AS FEATURE_SET_VERSION,
    'SYNTHETIC'
        AS TRAINING_DATA_CLASS,
    label.TARGET_CORRECT_MAPPING_FLAG,
    TRUE AS ML_ADVISORY_ONLY_FLAG,
    'SHADOW' AS DEPLOYMENT_MODE,
    FALSE AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    FALSE AS BUSINESS_DECISION_ALLOWED_FLAG,
    CURRENT_TIMESTAMP() AS CREATED_AT
FROM BMCS_FEATURE_DATASET_V2 feature
LEFT JOIN BMCS_TEST_PREDICTIONS_V2 prediction
  ON feature.ENTITY_ID = prediction.ENTITY_ID
LEFT JOIN BMCS_LABEL_DATASET_V2 label
  ON feature.ENTITY_ID = label.ENTITY_ID
WHERE feature.DATA_SPLIT = 'TEST';

CREATE OR REPLACE TABLE BMCS_FINAL_TEST_EVALUATION_V2 AS
SELECT
    evaluation.MODEL_NAME,
    evaluation.MODEL_VERSION,
    evaluation.DATA_SPLIT,
    evaluation.CALIBRATION_METHOD,
    evaluation.ROW_COUNT
        AS ML_SCORED_ROW_COUNT,
    coverage.TOTAL_TEST_ROWS,
    coverage.FALLBACK_ROW_COUNT,
    evaluation.CORRECT_MAPPING_RATE,
    evaluation.ROC_AUC,
    evaluation.PR_AUC,
    evaluation.BRIER_SCORE,
    evaluation.LOG_LOSS,
    evaluation.ECE_10_BIN,
    evaluation.ACCURACY_AT_050,
    evaluation.PRECISION_AT_050,
    evaluation.RECALL_AT_050,
    evaluation.F1_AT_050,
    evaluation.RULE_BASELINE_PR_AUC,
    evaluation.RULE_BASELINE_BRIER_SCORE,
    evaluation.HYBRID_BASELINE_PR_AUC,
    evaluation.HYBRID_BASELINE_BRIER_SCORE,
    evaluation.PR_AUC_IMPROVEMENT_VS_HYBRID,
    evaluation.BRIER_IMPROVEMENT_VS_HYBRID,
    evaluation.LOW_THRESHOLD,
    evaluation.HIGH_THRESHOLD,
    evaluation.AUTO_APPROVAL_ROWS,
    evaluation.AUTO_APPROVAL_RATE,
    evaluation.INCORRECT_AUTO_APPROVAL_ROWS,
    evaluation.INCORRECT_AUTO_APPROVAL_RATE,
    evaluation.AUTO_REJECTION_ROWS,
    evaluation.AUTO_REJECTION_RATE,
    evaluation.CORRECT_MAPPING_REJECTION_ROWS,
    evaluation.CORRECT_MAPPING_REJECTION_RATE,
    evaluation.ENGINEERING_REVIEW_ROWS,
    evaluation.ENGINEERING_REVIEW_RATE,
    'ACCEPTED_FOR_SHADOW_PROBABILITY_SCORING'
        AS MODEL_PROBABILITY_STATUS,
    'REJECTED_ON_TEST'
        AS AUTOMATION_POLICY_STATUS,
    'ACCEPTED_FOR_SHADOW_WITH_REVIEW_ONLY'
        AS FINAL_VALIDATION_STATUS,
    'The probability model materially outperformed the Phase 7 development hybrid benchmark. Locked automation thresholds did not meet the approved error constraints; therefore all BMCS ML outputs remain advisory and every RFQ remains subject to governed review.'
        AS DECISION_REASON,
    'SYNTHETIC' AS TRAINING_DATA_CLASS,
    'SHADOW' AS DEPLOYMENT_MODE,
    FALSE AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    FALSE AS BUSINESS_DECISION_ALLOWED_FLAG,
    CURRENT_TIMESTAMP() AS FINALIZED_AT
FROM BMCS_TEST_EVALUATION_V2 evaluation
CROSS JOIN (
    SELECT
        COUNT(*) AS TOTAL_TEST_ROWS,
        COUNT_IF(
            ML_SCORING_COMPLETED_FLAG = FALSE
        ) AS FALLBACK_ROW_COUNT
    FROM BMCS_FINAL_TEST_SHADOW_OUTPUT_V2
) coverage;

CREATE TABLE IF NOT EXISTS BMCS_MODEL_GOVERNANCE (
    EXPERIMENT_MODEL_NAME VARCHAR NOT NULL,
    EXPERIMENT_MODEL_VERSION VARCHAR NOT NULL,
    FEATURE_SET_VERSION VARCHAR NOT NULL,
    CALIBRATION_METHOD VARCHAR NOT NULL,
    TRAINING_DATA_CLASS VARCHAR NOT NULL,
    MODEL_PROBABILITY_STATUS VARCHAR NOT NULL,
    AUTOMATION_POLICY_STATUS VARCHAR NOT NULL,
    DEPLOYMENT_MODE VARCHAR NOT NULL,
    ML_ADVISORY_ONLY_FLAG BOOLEAN NOT NULL,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG BOOLEAN NOT NULL,
    BUSINESS_DECISION_ALLOWED_FLAG BOOLEAN NOT NULL,
    METRICS_JSON VARIANT,
    DECISION_REASON VARCHAR,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

MERGE INTO BMCS_MODEL_GOVERNANCE target
USING (
    SELECT
        MODEL_NAME AS EXPERIMENT_MODEL_NAME,
        MODEL_VERSION AS EXPERIMENT_MODEL_VERSION,
        'BMCS_FEATURES_V2' AS FEATURE_SET_VERSION,
        CALIBRATION_METHOD,
        TRAINING_DATA_CLASS,
        MODEL_PROBABILITY_STATUS,
        AUTOMATION_POLICY_STATUS,
        DEPLOYMENT_MODE,
        TRUE AS ML_ADVISORY_ONLY_FLAG,
        OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
        BUSINESS_DECISION_ALLOWED_FLAG,
        OBJECT_CONSTRUCT_KEEP_NULL(
            'ml_scored_rows', ML_SCORED_ROW_COUNT,
            'total_test_rows', TOTAL_TEST_ROWS,
            'fallback_rows', FALLBACK_ROW_COUNT,
            'roc_auc', ROC_AUC,
            'pr_auc', PR_AUC,
            'brier_score', BRIER_SCORE,
            'log_loss', LOG_LOSS,
            'ece_10_bin', ECE_10_BIN,
            'f1_at_050', F1_AT_050,
            'hybrid_baseline_pr_auc',
                HYBRID_BASELINE_PR_AUC,
            'hybrid_baseline_brier_score',
                HYBRID_BASELINE_BRIER_SCORE,
            'pr_auc_improvement_vs_hybrid',
                PR_AUC_IMPROVEMENT_VS_HYBRID,
            'brier_improvement_vs_hybrid',
                BRIER_IMPROVEMENT_VS_HYBRID,
            'locked_low_threshold',
                LOW_THRESHOLD,
            'locked_high_threshold',
                HIGH_THRESHOLD,
            'incorrect_auto_approval_rate',
                INCORRECT_AUTO_APPROVAL_RATE,
            'correct_mapping_rejection_rate',
                CORRECT_MAPPING_REJECTION_RATE
        ) AS METRICS_JSON,
        DECISION_REASON
    FROM BMCS_FINAL_TEST_EVALUATION_V2
) source
ON target.EXPERIMENT_MODEL_NAME =
    source.EXPERIMENT_MODEL_NAME
AND target.EXPERIMENT_MODEL_VERSION =
    source.EXPERIMENT_MODEL_VERSION
WHEN MATCHED THEN UPDATE SET
    FEATURE_SET_VERSION =
        source.FEATURE_SET_VERSION,
    CALIBRATION_METHOD =
        source.CALIBRATION_METHOD,
    TRAINING_DATA_CLASS =
        source.TRAINING_DATA_CLASS,
    MODEL_PROBABILITY_STATUS =
        source.MODEL_PROBABILITY_STATUS,
    AUTOMATION_POLICY_STATUS =
        source.AUTOMATION_POLICY_STATUS,
    DEPLOYMENT_MODE =
        source.DEPLOYMENT_MODE,
    ML_ADVISORY_ONLY_FLAG =
        source.ML_ADVISORY_ONLY_FLAG,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG =
        source.OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG =
        source.BUSINESS_DECISION_ALLOWED_FLAG,
    METRICS_JSON =
        source.METRICS_JSON,
    DECISION_REASON =
        source.DECISION_REASON,
    UPDATED_AT =
        CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    EXPERIMENT_MODEL_NAME,
    EXPERIMENT_MODEL_VERSION,
    FEATURE_SET_VERSION,
    CALIBRATION_METHOD,
    TRAINING_DATA_CLASS,
    MODEL_PROBABILITY_STATUS,
    AUTOMATION_POLICY_STATUS,
    DEPLOYMENT_MODE,
    ML_ADVISORY_ONLY_FLAG,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG,
    METRICS_JSON,
    DECISION_REASON
)
VALUES (
    source.EXPERIMENT_MODEL_NAME,
    source.EXPERIMENT_MODEL_VERSION,
    source.FEATURE_SET_VERSION,
    source.CALIBRATION_METHOD,
    source.TRAINING_DATA_CLASS,
    source.MODEL_PROBABILITY_STATUS,
    source.AUTOMATION_POLICY_STATUS,
    source.DEPLOYMENT_MODE,
    source.ML_ADVISORY_ONLY_FLAG,
    source.OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    source.BUSINESS_DECISION_ALLOWED_FLAG,
    source.METRICS_JSON,
    source.DECISION_REASON
);

SELECT *
FROM BMCS_THRESHOLD_POLICY_DECISION_V2;

SELECT *
FROM BMCS_FINAL_TEST_EVALUATION_V2;

SELECT
    COUNT(*) AS TOTAL_TEST_ROWS,
    COUNT_IF(
        ML_SCORING_COMPLETED_FLAG = TRUE
    ) AS ML_SCORED_ROWS,
    COUNT_IF(
        ML_SCORING_COMPLETED_FLAG = FALSE
    ) AS FALLBACK_ROWS,
    COUNT_IF(
        DEPLOYMENT_MODE <> 'SHADOW'
        OR ML_ADVISORY_ONLY_FLAG <> TRUE
        OR OFFICIAL_COST_IMPACT_ALLOWED_FLAG <> FALSE
        OR BUSINESS_DECISION_ALLOWED_FLAG <> FALSE
    ) AS INVALID_AUTHORITY_ROWS,
    COUNT_IF(
        SHADOW_REVIEW_ACTION
        <> 'ENGINEERING_REVIEW_REQUIRED'
    ) AS NON_REVIEW_ACTION_ROWS
FROM BMCS_FINAL_TEST_SHADOW_OUTPUT_V2;

SELECT *
FROM BMCS_MODEL_GOVERNANCE
WHERE EXPERIMENT_MODEL_NAME = 'XGB_V1_BALANCED'
  AND EXPERIMENT_MODEL_VERSION = 'V2';


USE DATABASE KMAT_COST_MODEL_DB;
USE SCHEMA CORE_ML;

CREATE TABLE IF NOT EXISTS BMCS_PHASE7_SCORING_INPUT_V2 (
    SCORING_BATCH_ID VARCHAR,
    ENTITY_ID VARCHAR,
    RFQ_ID VARCHAR,
    FEATURE_AS_OF_TIMESTAMP TIMESTAMP_NTZ,
    SOURCE_LANGUAGE VARCHAR,
    DOCUMENT_LENGTH_CHARS NUMBER,
    PAGE_COUNT NUMBER,
    OCR_QUALITY_SCORE FLOAT,
    DOCUMENT_COMPLEXITY_SCORE FLOAT,
    AMBIGUITY_TERM_COUNT NUMBER,
    CONFLICTING_PHRASE_COUNT NUMBER,
    UNSUPPORTED_VALUE_COUNT NUMBER,
    SYNONYM_MATCH_STRENGTH FLOAT,
    TRANSLATION_USED_FLAG NUMBER,
    TRANSLATION_QUALITY_SCORE FLOAT,
    SOURCE_TEXT_PRESENT_FLAG NUMBER,
    EXTRACTED_ENGINE VARCHAR,
    EXTRACTED_CAB VARCHAR,
    EXTRACTED_WHEEL VARCHAR,
    EXTRACTED_COLOR VARCHAR,
    ENGINE_EXTRACTION_CONFIDENCE FLOAT,
    CAB_EXTRACTION_CONFIDENCE FLOAT,
    WHEEL_EXTRACTION_CONFIDENCE FLOAT,
    COLOR_EXTRACTION_CONFIDENCE FLOAT,
    ENGINE_TEXT_EVIDENCE_FLAG NUMBER,
    CAB_TEXT_EVIDENCE_FLAG NUMBER,
    WHEEL_TEXT_EVIDENCE_FLAG NUMBER,
    COLOR_TEXT_EVIDENCE_FLAG NUMBER,
    VALID_EXTRACTED_VALUE_COUNT NUMBER,
    TEXT_SUPPORTED_VALUE_COUNT NUMBER,
    MISSING_REQUIREMENT_COUNT NUMBER,
    EXACT_PHRASE_MATCH_COUNT NUMBER,
    SYNONYM_MATCH_COUNT NUMBER,
    RULE_VALIDATION_PASS_COUNT NUMBER,
    CORTEX_EXTRACTION_STATUS VARCHAR,
    CORTEX_REASONING_AVAILABLE_FLAG NUMBER,
    RULE_BMCS_SCORE FLOAT,
    CORTEX_CONFIDENCE_SCORE FLOAT,
    DEVELOPMENT_HYBRID_BMCS_SCORE FLOAT,
    FEATURE_QUALITY_PASS_FLAG BOOLEAN,
    INPUT_STATUS VARCHAR DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS BMCS_PHASE7_SHADOW_SCORE_V2 (
    SCORING_BATCH_ID VARCHAR,
    ENTITY_ID VARCHAR,
    RFQ_ID VARCHAR,
    RAW_ML_PROBABILITY FLOAT,
    CALIBRATED_ML_PROBABILITY FLOAT,
    ML_BMCS_SCORE FLOAT,
    ML_ADVISORY_TRUST_BAND VARCHAR,
    ML_FALLBACK_REASON VARCHAR,
    SHADOW_REVIEW_ACTION VARCHAR,
    OFFICIAL_TRUST_SOURCE VARCHAR,
    PHYSICAL_MODEL_NAME VARCHAR,
    PHYSICAL_MODEL_VERSION VARCHAR,
    DEPLOYMENT_MODE VARCHAR,
    ML_ADVISORY_ONLY_FLAG BOOLEAN,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG BOOLEAN,
    BUSINESS_DECISION_ALLOWED_FLAG BOOLEAN,
    SCORED_AT TIMESTAMP_NTZ
);

SHOW MODELS LIKE 'BMCS_CALIBRATED_CLASSIFIER'
IN SCHEMA KMAT_COST_MODEL_DB.CORE_ML;

SHOW VERSIONS
IN MODEL KMAT_COST_MODEL_DB.CORE_ML.BMCS_CALIBRATED_CLASSIFIER;

SHOW FUNCTIONS
IN MODEL KMAT_COST_MODEL_DB.CORE_ML.BMCS_CALIBRATED_CLASSIFIER
VERSION V2_SHADOW_1;

USE DATABASE KMAT_COST_MODEL_DB;
USE SCHEMA CORE_ML;

-- The newest version must be the default version.
SHOW VERSIONS
IN MODEL
KMAT_COST_MODEL_DB.CORE_ML.BMCS_CALIBRATED_CLASSIFIER;

-- V2_SHADOW_2 must expose one PREDICT method.
SHOW FUNCTIONS
IN MODEL
KMAT_COST_MODEL_DB.CORE_ML.BMCS_CALIBRATED_CLASSIFIER
VERSION V2_SHADOW_2;

SELECT *
FROM BMCS_COMPOSITE_REGISTRATION_LOG_V2
ORDER BY CREATED_AT DESC;

-- Expected:
-- V2_SHADOW_1 remains preserved as audit history.
-- V2_SHADOW_2 is_default_version = TRUE.
-- V2_SHADOW_2 functions includes PREDICT.

USE DATABASE KMAT_COST_MODEL_DB;

-- ============================================================
-- PHASE 8E.9 PRE-INTEGRATION SCHEMA CAPTURE
--
-- This is not a new model phase.
-- It captures the exact Phase 7 RFQ/BMCS/Cortex contracts
-- required to build the production shadow-scoring adapter.
-- ============================================================


-- ------------------------------------------------------------
-- 1. Relevant objects currently available
-- ------------------------------------------------------------

SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    TABLE_TYPE
FROM KMAT_COST_MODEL_DB.INFORMATION_SCHEMA.TABLES
WHERE
       TABLE_NAME ILIKE '%RFQ%'
    OR TABLE_NAME ILIKE '%BMCS%'
    OR TABLE_NAME ILIKE '%CORTEX%'
ORDER BY
    TABLE_SCHEMA,
    TABLE_NAME;


-- ------------------------------------------------------------
-- 2. Exact columns of the primary Phase 7 status view
-- ------------------------------------------------------------

SELECT
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE
FROM KMAT_COST_MODEL_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE_INPUT'
  AND TABLE_NAME = 'VW_RFQ_BMCS_STATUS'
ORDER BY ORDINAL_POSITION;


-- ------------------------------------------------------------
-- 3. Exact columns of the RFQ source table
-- ------------------------------------------------------------

SELECT
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE
FROM KMAT_COST_MODEL_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE_INPUT'
  AND TABLE_NAME = 'RFQ_HEADER'
ORDER BY ORDINAL_POSITION;


-- ------------------------------------------------------------
-- 4. Exact columns of the rule-evidence detail table
-- ------------------------------------------------------------

SELECT
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE
FROM KMAT_COST_MODEL_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE_INPUT'
  AND TABLE_NAME = 'BMCS_SCORING_DETAIL'
ORDER BY ORDINAL_POSITION;


-- ------------------------------------------------------------
-- 5. Sample Phase 7 status rows
--
-- This reveals the real data types and JSON structures used by
-- Cortex extraction and BMCS scoring.
-- ------------------------------------------------------------

SELECT
    RFQ_ID,
    CUSTOMER_ID,
    CUSTOMER_NAME,

    SOURCE_DOCUMENT_NAME,
    SOURCE_DOCUMENT_TYPE,
    SOURCE_DOCUMENT_TEXT,
    DOCUMENT_STATUS,
    CORTEX_PROCESSING_STATUS,

    TEXT_EXTRACTION_METHOD,
    TRANSLATION_METHOD,
    RFQ_SUMMARY,
    RFQ_COMPLEXITY_CATEGORY,
    RFQ_COMPLEXITY_REASON,

    SIMULATION_ID,
    CONFIGURATION_VERSION,

    ENGINE,
    CAB,
    WHEEL,
    COLOR,

    EXTRACTION_METHOD,
    EXTRACTION_MODEL_NAME,

    CORTEX_EXTRACTION_SCORES,
    CORTEX_EXTRACTION_REASONING,

    RULE_BASED_BMCS_SCORE,
    CORTEX_BMCS_SCORE,
    BOM_MATCH_CONFIDENCE_SCORE,

    CORTEX_BMCS_REVIEW_STATUS,
    REVIEW_STATUS,
    REVIEW_REQUIRED_FLAG,
    FINAL_TRUSTED_COST_ALLOWED_FLAG,

    FINAL_BMCS_METHOD,
    CORTEX_BMCS_REASONING,

    BMCS_RISK_LEVEL,
    RULE_VALIDATION_STATUS,
    ASSESSMENT_METHOD,
    ASSESSMENT_VERSION,
    ASSESSMENT_NOTES

FROM KMAT_COST_MODEL_DB.CORE_INPUT.VW_RFQ_BMCS_STATUS
ORDER BY RFQ_ID DESC
LIMIT 5;


-- ------------------------------------------------------------
-- 6. Inspect Cortex extraction-score structure
-- ------------------------------------------------------------

SELECT
    RFQ_ID,

    TYPEOF(CORTEX_EXTRACTION_SCORES)
        AS EXTRACTION_SCORES_DATA_TYPE,

    TO_JSON(CORTEX_EXTRACTION_SCORES)
        AS EXTRACTION_SCORES_JSON,

    'TEXT' AS EXTRACTION_REASONING_DATA_TYPE,

    CORTEX_EXTRACTION_REASONING
        AS EXTRACTION_REASONING_JSON,

    'TEXT' AS BMCS_REASONING_DATA_TYPE,

    CORTEX_BMCS_REASONING
        AS BMCS_REASONING_JSON

FROM KMAT_COST_MODEL_DB.CORE_INPUT.VW_RFQ_BMCS_STATUS
WHERE CORTEX_EXTRACTION_SCORES IS NOT NULL
ORDER BY RFQ_ID DESC
LIMIT 5;


-- ------------------------------------------------------------
-- 7. Characteristic-level rule evidence
-- ------------------------------------------------------------

SELECT
    RFQ_ID,
    SIMULATION_ID,
    CHARACTERISTIC_NAME,
    EXTRACTED_VALUE,
    VALID_VALUE_FLAG,
    MATCHED_SIGNAL_FLAG,
    MATCHED_SIGNAL_PHRASES,
    'TEXT' AS MATCHED_PHRASES_DATA_TYPE,
    CHARACTERISTIC_SCORE_NOTES,
    CREATED_AT
FROM KMAT_COST_MODEL_DB.CORE_INPUT.BMCS_SCORING_DETAIL
ORDER BY CREATED_AT DESC, RFQ_ID, CHARACTERISTIC_NAME
LIMIT 40;


-- ------------------------------------------------------------
-- 8. RFQ source metadata required for feature timestamps,
--    language and document-quality derivation
-- ------------------------------------------------------------

SELECT
    RFQ_ID,
    KMAT_ID,
    CUSTOMER_ID,
    CUSTOMER_NAME,

    SOURCE_DOCUMENT_NAME,
    SOURCE_DOCUMENT_TYPE,

    SOURCE_LANGUAGE_CODE,
    DOCUMENT_STATUS,

    SOURCE_STAGE_NAME,
    SOURCE_STAGE_RELATIVE_PATH,

    LENGTH(SOURCE_DOCUMENT_TEXT)
        AS DOCUMENT_LENGTH_CHARS,

    LENGTH(ORIGINAL_DOCUMENT_TEXT)
        AS ORIGINAL_DOCUMENT_LENGTH_CHARS,

    RFQ_RECEIVED_AT,
    CREATED_AT,
    UPDATED_AT

FROM KMAT_COST_MODEL_DB.CORE_INPUT.RFQ_HEADER
ORDER BY RFQ_RECEIVED_AT DESC
LIMIT 10;


-- ------------------------------------------------------------
-- 9. Registered final atomic model verification
-- ------------------------------------------------------------

SHOW VERSIONS
IN MODEL
KMAT_COST_MODEL_DB.CORE_ML.BMCS_CALIBRATED_CLASSIFIER;


SHOW FUNCTIONS
IN MODEL
KMAT_COST_MODEL_DB.CORE_ML.BMCS_CALIBRATED_CLASSIFIER
VERSION V2_SHADOW_2;


-- ------------------------------------------------------------
-- 10. Registration audit
-- ------------------------------------------------------------

SELECT
    RUN_ID,
    MODEL_NAME,
    MODEL_VERSION,
    RUN_STATUS,
    MESSAGE,
    CREATED_AT
FROM KMAT_COST_MODEL_DB.CORE_ML.
     BMCS_COMPOSITE_REGISTRATION_LOG_V2
ORDER BY CREATED_AT DESC;

SELECT
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
    IS_NULLABLE
FROM KMAT_COST_MODEL_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE_INPUT'
  AND TABLE_NAME = 'VW_RFQ_BMCS_STATUS'
ORDER BY ORDINAL_POSITION;

SELECT
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
    IS_NULLABLE
FROM KMAT_COST_MODEL_DB.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE_INPUT'
  AND TABLE_NAME = 'BMCS_SCORING_DETAIL'
ORDER BY ORDINAL_POSITION;

SELECT
    RFQ_ID,
    SIMULATION_ID,

    TYPEOF(CORTEX_EXTRACTION_SCORES)
        AS EXTRACTION_SCORES_TYPE,

    TO_VARCHAR(CORTEX_EXTRACTION_SCORES)
        AS EXTRACTION_SCORES_CONTENT,

    TYPEOF(TRY_PARSE_JSON(CORTEX_EXTRACTION_REASONING))
        AS EXTRACTION_REASONING_TYPE,

    CORTEX_EXTRACTION_REASONING
        AS EXTRACTION_REASONING_CONTENT,

    TYPEOF(TRY_PARSE_JSON(CORTEX_BMCS_REASONING))
        AS BMCS_REASONING_TYPE,

    CORTEX_BMCS_REASONING
        AS BMCS_REASONING_CONTENT

FROM KMAT_COST_MODEL_DB.CORE_INPUT.VW_RFQ_BMCS_STATUS
WHERE
       CORTEX_EXTRACTION_SCORES IS NOT NULL
    OR CORTEX_EXTRACTION_REASONING IS NOT NULL
    OR CORTEX_BMCS_REASONING IS NOT NULL
ORDER BY RFQ_ID DESC
LIMIT 10;

SELECT
    RFQ_ID,
    KMAT_ID,
    CUSTOMER_ID,
    CUSTOMER_NAME,

    SOURCE_DOCUMENT_NAME,
    SOURCE_DOCUMENT_TYPE,
    SOURCE_LANGUAGE_CODE,
    DOCUMENT_STATUS,

    SOURCE_STAGE_NAME,
    SOURCE_STAGE_RELATIVE_PATH,

    LENGTH(SOURCE_DOCUMENT_TEXT)
        AS DOCUMENT_LENGTH_CHARS,

    LENGTH(ORIGINAL_DOCUMENT_TEXT)
        AS ORIGINAL_DOCUMENT_LENGTH_CHARS,

    RFQ_RECEIVED_AT,
    CREATED_AT,
    UPDATED_AT

FROM KMAT_COST_MODEL_DB.CORE_INPUT.RFQ_HEADER
ORDER BY
    RFQ_RECEIVED_AT DESC,
    CREATED_AT DESC
LIMIT 10;

SELECT
    RFQ_ID,
    SIMULATION_ID,
    CHARACTERISTIC_NAME,
    EXTRACTED_VALUE,

    VALID_VALUE_FLAG,
    MATCHED_SIGNAL_FLAG,

    TYPEOF(TRY_PARSE_JSON(MATCHED_SIGNAL_PHRASES))
        AS MATCHED_PHRASES_TYPE,

    MATCHED_SIGNAL_PHRASES
        AS MATCHED_SIGNAL_PHRASES_CONTENT,

    CHARACTERISTIC_SCORE_NOTES,
    CREATED_AT

FROM KMAT_COST_MODEL_DB.CORE_INPUT.BMCS_SCORING_DETAIL
ORDER BY
    CREATED_AT DESC,
    RFQ_ID,
    CHARACTERISTIC_NAME
LIMIT 50;

SELECT
    status.RFQ_ID,
    status.SIMULATION_ID,

    COUNT(detail.CHARACTERISTIC_NAME)
        AS DETAIL_ROW_COUNT,

    COUNT_IF(detail.VALID_VALUE_FLAG = TRUE)
        AS VALID_CHARACTERISTIC_COUNT,

    COUNT_IF(detail.MATCHED_SIGNAL_FLAG = TRUE)
        AS EVIDENCE_CHARACTERISTIC_COUNT,

    status.RULE_BASED_BMCS_SCORE,
    status.CORTEX_BMCS_SCORE,
    status.BOM_MATCH_CONFIDENCE_SCORE,
    status.REVIEW_STATUS

FROM KMAT_COST_MODEL_DB.CORE_INPUT.VW_RFQ_BMCS_STATUS status

LEFT JOIN KMAT_COST_MODEL_DB.CORE_INPUT.BMCS_SCORING_DETAIL detail
    ON status.RFQ_ID = detail.RFQ_ID
   AND (
        status.SIMULATION_ID = detail.SIMULATION_ID
        OR (
            status.SIMULATION_ID IS NULL
            AND detail.SIMULATION_ID IS NULL
        )
   )

GROUP BY
    status.RFQ_ID,
    status.SIMULATION_ID,
    status.RULE_BASED_BMCS_SCORE,
    status.CORTEX_BMCS_SCORE,
    status.BOM_MATCH_CONFIDENCE_SCORE,
    status.REVIEW_STATUS

ORDER BY status.RFQ_ID DESC
LIMIT 20;

USE DATABASE KMAT_COST_MODEL_DB;
USE SCHEMA CORE_ML;

-- ============================================================
-- PHASE 8E.9–8E.10 FINAL
-- Real Phase 7 RFQ -> BMCS V2 shadow feature adapter
-- ============================================================

CREATE OR REPLACE VIEW
KMAT_COST_MODEL_DB.CORE_ML.VW_BMCS_SCORING_DETAIL_LATEST_V2 AS
SELECT
    RFQ_ID,
    SIMULATION_ID,
    KMAT_ID,
    CONFIGURATION_VERSION,
    UPPER(TRIM(CHARACTERISTIC_NAME)) AS CHARACTERISTIC_NAME,
    UPPER(TRIM(EXTRACTED_VALUE)) AS EXTRACTED_VALUE,
    VALID_VALUE_FLAG,
    MATCHED_SIGNAL_FLAG,
    MATCHED_SIGNAL_PHRASES,
    CHARACTERISTIC_SCORE_NOTES,
    CREATED_AT
FROM KMAT_COST_MODEL_DB.CORE_INPUT.BMCS_SCORING_DETAIL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY
        RFQ_ID,
        COALESCE(SIMULATION_ID, '__NO_SIMULATION__'),
        UPPER(TRIM(CHARACTERISTIC_NAME))
    ORDER BY CREATED_AT DESC, CONFIGURATION_VERSION DESC NULLS LAST
) = 1;


CREATE OR REPLACE VIEW
KMAT_COST_MODEL_DB.CORE_ML.VW_BMCS_SCORING_DETAIL_AGG_V2 AS
SELECT
    RFQ_ID,
    SIMULATION_ID,
    COUNT(*) AS CHARACTERISTIC_ROW_COUNT,
    COUNT_IF(VALID_VALUE_FLAG = TRUE) AS VALID_EXTRACTED_VALUE_COUNT,
    COUNT_IF(MATCHED_SIGNAL_FLAG = TRUE) AS TEXT_SUPPORTED_VALUE_COUNT,
    COUNT_IF(VALID_VALUE_FLAG = FALSE) AS UNSUPPORTED_VALUE_COUNT,

    MAX(IFF(CHARACTERISTIC_NAME='ENGINE', IFF(MATCHED_SIGNAL_FLAG,1,0), NULL)) AS ENGINE_TEXT_EVIDENCE_FLAG,
    MAX(IFF(CHARACTERISTIC_NAME='CAB', IFF(MATCHED_SIGNAL_FLAG,1,0), NULL)) AS CAB_TEXT_EVIDENCE_FLAG,
    MAX(IFF(CHARACTERISTIC_NAME='WHEEL', IFF(MATCHED_SIGNAL_FLAG,1,0), NULL)) AS WHEEL_TEXT_EVIDENCE_FLAG,
    MAX(IFF(CHARACTERISTIC_NAME='COLOR', IFF(MATCHED_SIGNAL_FLAG,1,0), NULL)) AS COLOR_TEXT_EVIDENCE_FLAG,

    MAX(IFF(CHARACTERISTIC_NAME='ENGINE', MATCHED_SIGNAL_PHRASES, NULL)) AS ENGINE_MATCHED_SIGNAL_PHRASES,
    MAX(IFF(CHARACTERISTIC_NAME='CAB', MATCHED_SIGNAL_PHRASES, NULL)) AS CAB_MATCHED_SIGNAL_PHRASES,
    MAX(IFF(CHARACTERISTIC_NAME='WHEEL', MATCHED_SIGNAL_PHRASES, NULL)) AS WHEEL_MATCHED_SIGNAL_PHRASES,
    MAX(IFF(CHARACTERISTIC_NAME='COLOR', MATCHED_SIGNAL_PHRASES, NULL)) AS COLOR_MATCHED_SIGNAL_PHRASES,

    MAX(CREATED_AT) AS LATEST_DETAIL_CREATED_AT
FROM KMAT_COST_MODEL_DB.CORE_ML.VW_BMCS_SCORING_DETAIL_LATEST_V2
GROUP BY RFQ_ID, SIMULATION_ID;

CREATE OR REPLACE VIEW
KMAT_COST_MODEL_DB.CORE_ML.VW_RFQ_BMCS_STATUS_LATEST_V2 AS
SELECT *
FROM KMAT_COST_MODEL_DB.CORE_INPUT.VW_RFQ_BMCS_STATUS
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY
        RFQ_ID,
        COALESCE(SIMULATION_ID, '__NO_SIMULATION__'),
        COALESCE(CONFIGURATION_VERSION, -1)
    ORDER BY CORTEX_PROCESSED_AT DESC NULLS LAST, REVIEWED_AT DESC NULLS LAST
) = 1;

CREATE OR REPLACE VIEW
KMAT_COST_MODEL_DB.CORE_ML.BMCS_PHASE7_FEATURE_ADAPTER_FINAL_V2 AS
WITH B AS (
    SELECT
        s.RFQ_ID,
        s.SIMULATION_ID,
        s.KMAT_ID,
        s.CONFIGURATION_VERSION,
        s.CUSTOMER_ID,
        s.CUSTOMER_NAME,
        s.SOURCE_DOCUMENT_NAME,
        s.SOURCE_DOCUMENT_TYPE,
        s.DOCUMENT_STATUS,
        s.CORTEX_PROCESSING_STATUS,
        s.TEXT_EXTRACTION_METHOD,
        s.TRANSLATION_METHOD,
        s.RFQ_COMPLEXITY_CATEGORY,
        s.RFQ_COMPLEXITY_REASON,
        s.CORTEX_PROCESSED_AT,
        s.PROCESSING_TEXT_EN,
        s.SOURCE_DOCUMENT_TEXT,
        s.ORIGINAL_DOCUMENT_TEXT,
        s.CORTEX_EXTRACTION_REASONING,
        s.CORTEX_BMCS_REASONING,
        s.RULE_BASED_BMCS_SCORE,
        s.CORTEX_BMCS_SCORE,
        s.BOM_MATCH_CONFIDENCE_SCORE,
        s.REVIEW_STATUS,
        s.REVIEW_REQUIRED_FLAG,
        s.FINAL_TRUSTED_COST_ALLOWED_FLAG,
        s.FINAL_BMCS_METHOD,

        UPPER(COALESCE(NULLIF(TRIM(s.SOURCE_LANGUAGE_CODE),''),'EN')) AS SOURCE_LANGUAGE,
        UPPER(COALESCE(NULLIF(TRIM(s.ENGINE),''),'UNKNOWN')) AS EXTRACTED_ENGINE,
        UPPER(COALESCE(NULLIF(TRIM(s.CAB),''),'UNKNOWN')) AS EXTRACTED_CAB,
        UPPER(COALESCE(NULLIF(TRIM(s.WHEEL),''),'UNKNOWN')) AS EXTRACTED_WHEEL,
        UPPER(COALESCE(NULLIF(TRIM(s.COLOR),''),'UNKNOWN')) AS EXTRACTED_COLOR,

        TRY_TO_DOUBLE(s.CORTEX_EXTRACTION_SCORES:scores:ENGINE:score::VARCHAR) AS ENGINE_EXTRACTION_CONFIDENCE,
        TRY_TO_DOUBLE(s.CORTEX_EXTRACTION_SCORES:scores:CAB:score::VARCHAR) AS CAB_EXTRACTION_CONFIDENCE,
        TRY_TO_DOUBLE(s.CORTEX_EXTRACTION_SCORES:scores:WHEEL:score::VARCHAR) AS WHEEL_EXTRACTION_CONFIDENCE,
        TRY_TO_DOUBLE(s.CORTEX_EXTRACTION_SCORES:scores:COLOR:score::VARCHAR) AS COLOR_EXTRACTION_CONFIDENCE,

        h.RFQ_RECEIVED_AT,
        h.CREATED_AT AS RFQ_CREATED_AT,
        h.UPDATED_AT AS RFQ_UPDATED_AT,

        d.CHARACTERISTIC_ROW_COUNT,
        d.VALID_EXTRACTED_VALUE_COUNT,
        d.TEXT_SUPPORTED_VALUE_COUNT,
        d.UNSUPPORTED_VALUE_COUNT,
        COALESCE(d.ENGINE_TEXT_EVIDENCE_FLAG,0) AS ENGINE_TEXT_EVIDENCE_FLAG,
        COALESCE(d.CAB_TEXT_EVIDENCE_FLAG,0) AS CAB_TEXT_EVIDENCE_FLAG,
        COALESCE(d.WHEEL_TEXT_EVIDENCE_FLAG,0) AS WHEEL_TEXT_EVIDENCE_FLAG,
        COALESCE(d.COLOR_TEXT_EVIDENCE_FLAG,0) AS COLOR_TEXT_EVIDENCE_FLAG,
        d.LATEST_DETAIL_CREATED_AT,

        COALESCE(NULLIF(s.PROCESSING_TEXT_EN,''), NULLIF(s.SOURCE_DOCUMENT_TEXT,''), NULLIF(s.ORIGINAL_DOCUMENT_TEXT,''), '') AS PROCESSING_TEXT

    FROM KMAT_COST_MODEL_DB.CORE_ML.VW_RFQ_BMCS_STATUS_LATEST_V2 s
    LEFT JOIN KMAT_COST_MODEL_DB.CORE_INPUT.RFQ_HEADER h
      ON s.RFQ_ID = h.RFQ_ID
    LEFT JOIN KMAT_COST_MODEL_DB.CORE_ML.VW_BMCS_SCORING_DETAIL_AGG_V2 d
      ON s.RFQ_ID = d.RFQ_ID
     AND COALESCE(s.SIMULATION_ID,'__NO_SIMULATION__') = COALESCE(d.SIMULATION_ID,'__NO_SIMULATION__')
),
D AS (
    SELECT
        B.*,
        RFQ_ID || '::' || COALESCE(SIMULATION_ID,'NO_SIMULATION') || '::V' || COALESCE(CONFIGURATION_VERSION::VARCHAR,'0') AS ENTITY_ID,
        COALESCE(CORTEX_PROCESSED_AT, LATEST_DETAIL_CREATED_AT, RFQ_UPDATED_AT, RFQ_CREATED_AT, RFQ_RECEIVED_AT) AS FEATURE_AS_OF_TIMESTAMP,
        LENGTH(PROCESSING_TEXT) AS DOCUMENT_LENGTH_CHARS,
        IFF(LENGTH(PROCESSING_TEXT)>0, GREATEST(1, CEIL(LENGTH(PROCESSING_TEXT)/1800.0)), 0) AS PAGE_COUNT,

        CASE
            WHEN LENGTH(PROCESSING_TEXT)=0 THEN 0.0
            WHEN UPPER(COALESCE(SOURCE_DOCUMENT_TYPE,'')) IN ('TEXT','TXT') THEN 0.98
            WHEN UPPER(COALESCE(SOURCE_DOCUMENT_TYPE,''))='PDF' THEN 0.90
            ELSE 0.85
        END AS OCR_QUALITY_SCORE,

        CASE
            WHEN UPPER(COALESCE(RFQ_COMPLEXITY_CATEGORY,''))='STANDARD_CONFIGURATION' THEN 30.0
            WHEN UPPER(COALESCE(RFQ_COMPLEXITY_CATEGORY,''))='CUSTOM_CONFIGURATION' THEN 70.0
            WHEN UPPER(COALESCE(RFQ_COMPLEXITY_CATEGORY,'')) IN ('COMPLEX_CONFIGURATION','HIGH_COMPLEXITY') THEN 90.0
            ELSE 50.0
        END AS DOCUMENT_COMPLEXITY_SCORE,

        REGEXP_COUNT(LOWER(COALESCE(CORTEX_EXTRACTION_REASONING,'') || ' ' || COALESCE(CORTEX_BMCS_REASONING,'')),
                     'unclear|ambiguous|inferred|not explicit|not fully|brief|does not explicitly') AS AMBIGUITY_TERM_COUNT,

        REGEXP_COUNT(LOWER(COALESCE(CORTEX_EXTRACTION_REASONING,'') || ' ' || COALESCE(CORTEX_BMCS_REASONING,'')),
                     'conflict|contradict|inconsistent|mismatch') AS CONFLICTING_PHRASE_COUNT,

        IFF(SOURCE_LANGUAGE<>'EN',1,0) AS TRANSLATION_USED_FLAG,
        CASE
            WHEN SOURCE_LANGUAGE='EN' THEN 1.0
            WHEN LENGTH(PROCESSING_TEXT)>0 AND NULLIF(TRIM(COALESCE(TRANSLATION_METHOD,'')),'') IS NOT NULL THEN 0.90
            WHEN LENGTH(PROCESSING_TEXT)>0 THEN 0.70
            ELSE 0.0
        END AS TRANSLATION_QUALITY_SCORE,

        IFF(LENGTH(PROCESSING_TEXT)>0,1,0) AS SOURCE_TEXT_PRESENT_FLAG,

        IFF(EXTRACTED_ENGINE IN ('V6','V8'),0,1)
        + IFF(EXTRACTED_CAB IN ('STANDARD','PREMIUM'),0,1)
        + IFF(EXTRACTED_WHEEL IN ('STANDARD','OFFROAD'),0,1)
        + IFF(EXTRACTED_COLOR IN ('RED','BLUE'),0,1) AS MISSING_REQUIREMENT_COUNT,

        IFF(ENGINE_TEXT_EVIDENCE_FLAG=1 AND POSITION(EXTRACTED_ENGINE IN UPPER(PROCESSING_TEXT))>0,1,0)
        + IFF(CAB_TEXT_EVIDENCE_FLAG=1 AND POSITION(EXTRACTED_CAB IN UPPER(PROCESSING_TEXT))>0,1,0)
        + IFF(WHEEL_TEXT_EVIDENCE_FLAG=1 AND POSITION(EXTRACTED_WHEEL IN UPPER(PROCESSING_TEXT))>0,1,0)
        + IFF(COLOR_TEXT_EVIDENCE_FLAG=1 AND POSITION(EXTRACTED_COLOR IN UPPER(PROCESSING_TEXT))>0,1,0) AS EXACT_PHRASE_MATCH_COUNT,

        LEAST(1.0, GREATEST(0.0,
            0.50 * (COALESCE(TEXT_SUPPORTED_VALUE_COUNT,0)/4.0)
            + 0.50 * COALESCE((ENGINE_EXTRACTION_CONFIDENCE+CAB_EXTRACTION_CONFIDENCE+WHEEL_EXTRACTION_CONFIDENCE+COLOR_EXTRACTION_CONFIDENCE)/4.0,0.0)
        )) AS SYNONYM_MATCH_STRENGTH,

        IFF(NULLIF(TRIM(COALESCE(CORTEX_EXTRACTION_REASONING,'')),'') IS NOT NULL,1,0) AS CORTEX_REASONING_AVAILABLE_FLAG,

        CASE
            WHEN UPPER(COALESCE(CORTEX_PROCESSING_STATUS,'')) LIKE '%COMPLETE%' AND COALESCE(CHARACTERISTIC_ROW_COUNT,0)=4 THEN 'COMPLETE'
            WHEN UPPER(COALESCE(CORTEX_PROCESSING_STATUS,'')) LIKE '%FAIL%' THEN 'FAILED'
            ELSE 'PARTIAL'
        END AS CORTEX_EXTRACTION_STATUS,

        COALESCE(RULE_BASED_BMCS_SCORE::FLOAT, BOM_MATCH_CONFIDENCE_SCORE::FLOAT, 0.0) AS RULE_BMCS_SCORE,
        COALESCE(CORTEX_BMCS_SCORE::FLOAT,
                 100.0 * (ENGINE_EXTRACTION_CONFIDENCE+CAB_EXTRACTION_CONFIDENCE+WHEEL_EXTRACTION_CONFIDENCE+COLOR_EXTRACTION_CONFIDENCE)/4.0,
                 BOM_MATCH_CONFIDENCE_SCORE::FLOAT,0.0) AS CORTEX_CONFIDENCE_SCORE,
        COALESCE(BOM_MATCH_CONFIDENCE_SCORE::FLOAT, RULE_BASED_BMCS_SCORE::FLOAT, CORTEX_BMCS_SCORE::FLOAT,0.0) AS DEVELOPMENT_HYBRID_BMCS_SCORE
    FROM B
),
F AS (
    SELECT
        D.*,
        GREATEST(0, COALESCE(TEXT_SUPPORTED_VALUE_COUNT,0)-EXACT_PHRASE_MATCH_COUNT) AS SYNONYM_MATCH_COUNT,
        COALESCE(VALID_EXTRACTED_VALUE_COUNT,0) AS RULE_VALIDATION_PASS_COUNT,
        IFF(SOURCE_LANGUAGE NOT IN ('EN','DE','FR','ES'),TRUE,FALSE) AS OOD_LANGUAGE_FLAG,
        IFF(DOCUMENT_LENGTH_CHARS<400 OR DOCUMENT_LENGTH_CHARS>18000,TRUE,FALSE) AS OOD_DOCUMENT_LENGTH_FLAG,
        7 AS PROXY_FEATURE_COUNT,

        IFF(
            FEATURE_AS_OF_TIMESTAMP IS NOT NULL
            AND SOURCE_TEXT_PRESENT_FLAG=1
            AND SIMULATION_ID IS NOT NULL
            AND EXTRACTED_ENGINE IN ('V6','V8')
            AND EXTRACTED_CAB IN ('STANDARD','PREMIUM')
            AND EXTRACTED_WHEEL IN ('STANDARD','OFFROAD')
            AND EXTRACTED_COLOR IN ('RED','BLUE')
            AND ENGINE_EXTRACTION_CONFIDENCE BETWEEN 0 AND 1
            AND CAB_EXTRACTION_CONFIDENCE BETWEEN 0 AND 1
            AND WHEEL_EXTRACTION_CONFIDENCE BETWEEN 0 AND 1
            AND COLOR_EXTRACTION_CONFIDENCE BETWEEN 0 AND 1
            AND COALESCE(CHARACTERISTIC_ROW_COUNT,0)=4
            AND COALESCE(VALID_EXTRACTED_VALUE_COUNT,0)=4
            AND RULE_BASED_BMCS_SCORE IS NOT NULL
            AND BOM_MATCH_CONFIDENCE_SCORE IS NOT NULL,
            TRUE,FALSE
        ) AS FEATURE_QUALITY_PASS_FLAG
    FROM D
)
SELECT
    ENTITY_ID,
    RFQ_ID,
    SIMULATION_ID,
    KMAT_ID,
    CONFIGURATION_VERSION,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SOURCE_DOCUMENT_NAME,
    SOURCE_DOCUMENT_TYPE,
    FEATURE_AS_OF_TIMESTAMP,

    SOURCE_LANGUAGE,
    DOCUMENT_LENGTH_CHARS,
    PAGE_COUNT,
    OCR_QUALITY_SCORE,
    DOCUMENT_COMPLEXITY_SCORE,
    AMBIGUITY_TERM_COUNT,
    CONFLICTING_PHRASE_COUNT,
    COALESCE(UNSUPPORTED_VALUE_COUNT,0) AS UNSUPPORTED_VALUE_COUNT,
    SYNONYM_MATCH_STRENGTH,
    TRANSLATION_USED_FLAG,
    TRANSLATION_QUALITY_SCORE,
    SOURCE_TEXT_PRESENT_FLAG,

    EXTRACTED_ENGINE,
    EXTRACTED_CAB,
    EXTRACTED_WHEEL,
    EXTRACTED_COLOR,

    ENGINE_EXTRACTION_CONFIDENCE,
    CAB_EXTRACTION_CONFIDENCE,
    WHEEL_EXTRACTION_CONFIDENCE,
    COLOR_EXTRACTION_CONFIDENCE,

    ENGINE_TEXT_EVIDENCE_FLAG,
    CAB_TEXT_EVIDENCE_FLAG,
    WHEEL_TEXT_EVIDENCE_FLAG,
    COLOR_TEXT_EVIDENCE_FLAG,

    COALESCE(VALID_EXTRACTED_VALUE_COUNT,0) AS VALID_EXTRACTED_VALUE_COUNT,
    COALESCE(TEXT_SUPPORTED_VALUE_COUNT,0) AS TEXT_SUPPORTED_VALUE_COUNT,
    MISSING_REQUIREMENT_COUNT,
    EXACT_PHRASE_MATCH_COUNT,
    SYNONYM_MATCH_COUNT,
    RULE_VALIDATION_PASS_COUNT,

    CORTEX_EXTRACTION_STATUS,
    CORTEX_REASONING_AVAILABLE_FLAG,
    RULE_BMCS_SCORE,
    CORTEX_CONFIDENCE_SCORE,
    DEVELOPMENT_HYBRID_BMCS_SCORE,

    COALESCE(CHARACTERISTIC_ROW_COUNT,0) AS CHARACTERISTIC_ROW_COUNT,
    PROXY_FEATURE_COUNT,
    OOD_LANGUAGE_FLAG,
    OOD_DOCUMENT_LENGTH_FLAG,
    IFF(OOD_LANGUAGE_FLAG OR OOD_DOCUMENT_LENGTH_FLAG,TRUE,FALSE) AS MODEL_OOD_FLAG,
    FEATURE_QUALITY_PASS_FLAG,

    CASE
        WHEN FEATURE_QUALITY_PASS_FLAG=FALSE THEN 'FEATURE_QUALITY_FAILED'
        WHEN OOD_LANGUAGE_FLAG=TRUE THEN 'ML_ELIGIBLE_WITH_LANGUAGE_OOD'
        WHEN OOD_DOCUMENT_LENGTH_FLAG=TRUE THEN 'ML_ELIGIBLE_WITH_LENGTH_OOD'
        ELSE 'ML_ELIGIBLE'
    END AS ADAPTER_STATUS,

    RULE_BASED_BMCS_SCORE AS OFFICIAL_RULE_BMCS_SCORE,
    CORTEX_BMCS_SCORE AS OFFICIAL_CORTEX_BMCS_SCORE,
    BOM_MATCH_CONFIDENCE_SCORE AS OFFICIAL_HYBRID_BMCS_SCORE,
    REVIEW_STATUS AS OFFICIAL_REVIEW_STATUS,
    REVIEW_REQUIRED_FLAG AS OFFICIAL_REVIEW_REQUIRED_FLAG,
    FINAL_TRUSTED_COST_ALLOWED_FLAG AS OFFICIAL_TRUSTED_COST_ALLOWED_FLAG,
    FINAL_BMCS_METHOD AS OFFICIAL_BMCS_METHOD
FROM F;


CREATE TABLE IF NOT EXISTS
KMAT_COST_MODEL_DB.CORE_ML.BMCS_PHASE7_SCORING_INPUT_FINAL_V2 (
    SCORING_BATCH_ID VARCHAR,
    ENTITY_ID VARCHAR,
    RFQ_ID VARCHAR,
    SIMULATION_ID VARCHAR,
    KMAT_ID VARCHAR,
    CONFIGURATION_VERSION NUMBER,
    FEATURE_AS_OF_TIMESTAMP TIMESTAMP_NTZ,

    SOURCE_LANGUAGE VARCHAR,
    DOCUMENT_LENGTH_CHARS NUMBER,
    PAGE_COUNT NUMBER,
    OCR_QUALITY_SCORE FLOAT,
    DOCUMENT_COMPLEXITY_SCORE FLOAT,
    AMBIGUITY_TERM_COUNT NUMBER,
    CONFLICTING_PHRASE_COUNT NUMBER,
    UNSUPPORTED_VALUE_COUNT NUMBER,
    SYNONYM_MATCH_STRENGTH FLOAT,
    TRANSLATION_USED_FLAG NUMBER,
    TRANSLATION_QUALITY_SCORE FLOAT,
    SOURCE_TEXT_PRESENT_FLAG NUMBER,

    EXTRACTED_ENGINE VARCHAR,
    EXTRACTED_CAB VARCHAR,
    EXTRACTED_WHEEL VARCHAR,
    EXTRACTED_COLOR VARCHAR,
    ENGINE_EXTRACTION_CONFIDENCE FLOAT,
    CAB_EXTRACTION_CONFIDENCE FLOAT,
    WHEEL_EXTRACTION_CONFIDENCE FLOAT,
    COLOR_EXTRACTION_CONFIDENCE FLOAT,
    ENGINE_TEXT_EVIDENCE_FLAG NUMBER,
    CAB_TEXT_EVIDENCE_FLAG NUMBER,
    WHEEL_TEXT_EVIDENCE_FLAG NUMBER,
    COLOR_TEXT_EVIDENCE_FLAG NUMBER,
    VALID_EXTRACTED_VALUE_COUNT NUMBER,
    TEXT_SUPPORTED_VALUE_COUNT NUMBER,
    MISSING_REQUIREMENT_COUNT NUMBER,
    EXACT_PHRASE_MATCH_COUNT NUMBER,
    SYNONYM_MATCH_COUNT NUMBER,
    RULE_VALIDATION_PASS_COUNT NUMBER,
    CORTEX_EXTRACTION_STATUS VARCHAR,
    CORTEX_REASONING_AVAILABLE_FLAG NUMBER,
    RULE_BMCS_SCORE FLOAT,
    CORTEX_CONFIDENCE_SCORE FLOAT,
    DEVELOPMENT_HYBRID_BMCS_SCORE FLOAT,

    FEATURE_QUALITY_PASS_FLAG BOOLEAN,
    MODEL_OOD_FLAG BOOLEAN,
    OOD_LANGUAGE_FLAG BOOLEAN,
    OOD_DOCUMENT_LENGTH_FLAG BOOLEAN,
    PROXY_FEATURE_COUNT NUMBER,
    ADAPTER_STATUS VARCHAR,

    OFFICIAL_RULE_BMCS_SCORE FLOAT,
    OFFICIAL_CORTEX_BMCS_SCORE FLOAT,
    OFFICIAL_HYBRID_BMCS_SCORE FLOAT,
    OFFICIAL_REVIEW_STATUS VARCHAR,
    OFFICIAL_REVIEW_REQUIRED_FLAG BOOLEAN,
    OFFICIAL_TRUSTED_COST_ALLOWED_FLAG BOOLEAN,
    OFFICIAL_BMCS_METHOD VARCHAR,

    INPUT_STATUS VARCHAR,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


CREATE TABLE IF NOT EXISTS
KMAT_COST_MODEL_DB.CORE_ML.BMCS_PHASE7_SHADOW_SCORE_FINAL_V2 (
    SCORING_BATCH_ID VARCHAR,
    ENTITY_ID VARCHAR,
    RFQ_ID VARCHAR,
    SIMULATION_ID VARCHAR,
    KMAT_ID VARCHAR,
    CONFIGURATION_VERSION NUMBER,

    RAW_ML_PROBABILITY FLOAT,
    CALIBRATED_ML_PROBABILITY FLOAT,
    ML_BMCS_SCORE FLOAT,
    ML_ADVISORY_TRUST_BAND VARCHAR,
    ML_FALLBACK_REASON VARCHAR,
    MODEL_OOD_FLAG BOOLEAN,
    PROXY_FEATURE_COUNT NUMBER,

    SHADOW_REVIEW_ACTION VARCHAR,
    OFFICIAL_TRUST_SOURCE VARCHAR,
    OFFICIAL_RULE_BMCS_SCORE FLOAT,
    OFFICIAL_CORTEX_BMCS_SCORE FLOAT,
    OFFICIAL_HYBRID_BMCS_SCORE FLOAT,
    OFFICIAL_REVIEW_STATUS VARCHAR,
    OFFICIAL_REVIEW_REQUIRED_FLAG BOOLEAN,
    OFFICIAL_TRUSTED_COST_ALLOWED_FLAG BOOLEAN,
    OFFICIAL_BMCS_METHOD VARCHAR,

    PHYSICAL_MODEL_NAME VARCHAR,
    PHYSICAL_MODEL_VERSION VARCHAR,
    FEATURE_SET_VERSION VARCHAR,
    DEPLOYMENT_MODE VARCHAR,
    ML_ADVISORY_ONLY_FLAG BOOLEAN,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG BOOLEAN,
    BUSINESS_DECISION_ALLOWED_FLAG BOOLEAN,
    SCORED_AT TIMESTAMP_NTZ
);


CREATE OR REPLACE PROCEDURE
KMAT_COST_MODEL_DB.CORE_ML.PREPARE_BMCS_PHASE7_SHADOW_BATCH_FINAL_V2(
    P_SCORING_BATCH_ID VARCHAR,
    P_RFQ_ID VARCHAR
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS '
DECLARE
    V_TOTAL NUMBER DEFAULT 0;
    V_ELIGIBLE NUMBER DEFAULT 0;
    V_FALLBACK NUMBER DEFAULT 0;
BEGIN
    IF (P_SCORING_BATCH_ID IS NULL OR LENGTH(TRIM(P_SCORING_BATCH_ID))=0) THEN
        RETURN OBJECT_CONSTRUCT(''status'',''ERROR'',''message'',''P_SCORING_BATCH_ID is required'');
    END IF;

    DELETE FROM KMAT_COST_MODEL_DB.CORE_ML.BMCS_PHASE7_SCORING_INPUT_FINAL_V2
    WHERE SCORING_BATCH_ID=:P_SCORING_BATCH_ID;

    INSERT INTO KMAT_COST_MODEL_DB.CORE_ML.BMCS_PHASE7_SCORING_INPUT_FINAL_V2
    SELECT
        :P_SCORING_BATCH_ID,
        ENTITY_ID,
        RFQ_ID,
        SIMULATION_ID,
        KMAT_ID,
        CONFIGURATION_VERSION,
        FEATURE_AS_OF_TIMESTAMP,

        SOURCE_LANGUAGE,
        DOCUMENT_LENGTH_CHARS,
        PAGE_COUNT,
        OCR_QUALITY_SCORE,
        DOCUMENT_COMPLEXITY_SCORE,
        AMBIGUITY_TERM_COUNT,
        CONFLICTING_PHRASE_COUNT,
        UNSUPPORTED_VALUE_COUNT,
        SYNONYM_MATCH_STRENGTH,
        TRANSLATION_USED_FLAG,
        TRANSLATION_QUALITY_SCORE,
        SOURCE_TEXT_PRESENT_FLAG,

        EXTRACTED_ENGINE,
        EXTRACTED_CAB,
        EXTRACTED_WHEEL,
        EXTRACTED_COLOR,
        ENGINE_EXTRACTION_CONFIDENCE,
        CAB_EXTRACTION_CONFIDENCE,
        WHEEL_EXTRACTION_CONFIDENCE,
        COLOR_EXTRACTION_CONFIDENCE,
        ENGINE_TEXT_EVIDENCE_FLAG,
        CAB_TEXT_EVIDENCE_FLAG,
        WHEEL_TEXT_EVIDENCE_FLAG,
        COLOR_TEXT_EVIDENCE_FLAG,
        VALID_EXTRACTED_VALUE_COUNT,
        TEXT_SUPPORTED_VALUE_COUNT,
        MISSING_REQUIREMENT_COUNT,
        EXACT_PHRASE_MATCH_COUNT,
        SYNONYM_MATCH_COUNT,
        RULE_VALIDATION_PASS_COUNT,
        CORTEX_EXTRACTION_STATUS,
        CORTEX_REASONING_AVAILABLE_FLAG,
        RULE_BMCS_SCORE,
        CORTEX_CONFIDENCE_SCORE,
        DEVELOPMENT_HYBRID_BMCS_SCORE,

        FEATURE_QUALITY_PASS_FLAG,
        MODEL_OOD_FLAG,
        OOD_LANGUAGE_FLAG,
        OOD_DOCUMENT_LENGTH_FLAG,
        PROXY_FEATURE_COUNT,
        ADAPTER_STATUS,

        OFFICIAL_RULE_BMCS_SCORE,
        OFFICIAL_CORTEX_BMCS_SCORE,
        OFFICIAL_HYBRID_BMCS_SCORE,
        OFFICIAL_REVIEW_STATUS,
        OFFICIAL_REVIEW_REQUIRED_FLAG,
        OFFICIAL_TRUSTED_COST_ALLOWED_FLAG,
        OFFICIAL_BMCS_METHOD,

        ''PENDING'',
        CURRENT_TIMESTAMP(),
        CURRENT_TIMESTAMP()
    FROM KMAT_COST_MODEL_DB.CORE_ML.BMCS_PHASE7_FEATURE_ADAPTER_FINAL_V2
    WHERE :P_RFQ_ID IS NULL OR RFQ_ID=:P_RFQ_ID;

    SELECT
        COUNT(*),
        COUNT_IF(FEATURE_QUALITY_PASS_FLAG=TRUE),
        COUNT_IF(FEATURE_QUALITY_PASS_FLAG=FALSE)
    INTO :V_TOTAL, :V_ELIGIBLE, :V_FALLBACK
    FROM KMAT_COST_MODEL_DB.CORE_ML.BMCS_PHASE7_SCORING_INPUT_FINAL_V2
    WHERE SCORING_BATCH_ID=:P_SCORING_BATCH_ID;

    RETURN OBJECT_CONSTRUCT(
        ''status'',''SUCCESS'',
        ''scoring_batch_id'',P_SCORING_BATCH_ID,
        ''rfq_filter'',P_RFQ_ID,
        ''batch_rows'',V_TOTAL,
        ''ml_eligible_rows'',V_ELIGIBLE,
        ''fallback_rows'',V_FALLBACK,
        ''deployment_mode'',''SHADOW'',
        ''business_decision_allowed'',FALSE
    );
END;
';


CREATE OR REPLACE VIEW
KMAT_COST_MODEL_DB.CORE_ML.VW_RFQ_BMCS_ML_SHADOW_STATUS_FINAL_V2 AS
WITH LATEST_ML AS (
    SELECT *
    FROM KMAT_COST_MODEL_DB.CORE_ML.BMCS_PHASE7_SHADOW_SCORE_FINAL_V2
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ENTITY_ID ORDER BY SCORED_AT DESC)=1
)
SELECT
    a.RFQ_ID,
    a.SIMULATION_ID,
    a.KMAT_ID,
    a.CONFIGURATION_VERSION,
    a.CUSTOMER_ID,
    a.CUSTOMER_NAME,
    a.SOURCE_DOCUMENT_NAME,
    a.SOURCE_DOCUMENT_TYPE,
    a.SOURCE_LANGUAGE,
    a.EXTRACTED_ENGINE AS ENGINE,
    a.EXTRACTED_CAB AS CAB,
    a.EXTRACTED_WHEEL AS WHEEL,
    a.EXTRACTED_COLOR AS COLOR,

    a.OFFICIAL_RULE_BMCS_SCORE,
    a.OFFICIAL_CORTEX_BMCS_SCORE,
    a.OFFICIAL_HYBRID_BMCS_SCORE,

    m.RAW_ML_PROBABILITY,
    m.CALIBRATED_ML_PROBABILITY,
    m.ML_BMCS_SCORE,
    m.ML_ADVISORY_TRUST_BAND,

    a.FEATURE_QUALITY_PASS_FLAG,
    a.MODEL_OOD_FLAG,
    a.OOD_LANGUAGE_FLAG,
    a.OOD_DOCUMENT_LENGTH_FLAG,
    a.PROXY_FEATURE_COUNT,
    a.ADAPTER_STATUS,
    m.ML_FALLBACK_REASON,
    m.SHADOW_REVIEW_ACTION,

    a.OFFICIAL_REVIEW_STATUS,
    a.OFFICIAL_REVIEW_REQUIRED_FLAG,
    a.OFFICIAL_TRUSTED_COST_ALLOWED_FLAG,
    a.OFFICIAL_BMCS_METHOD,

    COALESCE(m.OFFICIAL_TRUST_SOURCE,'PHASE7_RULE_CORTEX_HYBRID') AS OFFICIAL_TRUST_SOURCE,
    m.PHYSICAL_MODEL_NAME,
    m.PHYSICAL_MODEL_VERSION,
    m.FEATURE_SET_VERSION,
    COALESCE(m.DEPLOYMENT_MODE,'SHADOW') AS DEPLOYMENT_MODE,
    COALESCE(m.ML_ADVISORY_ONLY_FLAG,TRUE) AS ML_ADVISORY_ONLY_FLAG,
    COALESCE(m.OFFICIAL_COST_IMPACT_ALLOWED_FLAG,FALSE) AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    COALESCE(m.BUSINESS_DECISION_ALLOWED_FLAG,FALSE) AS BUSINESS_DECISION_ALLOWED_FLAG,
    m.SCORED_AT
FROM KMAT_COST_MODEL_DB.CORE_ML.BMCS_PHASE7_FEATURE_ADAPTER_FINAL_V2 a
LEFT JOIN LATEST_ML m
  ON a.ENTITY_ID=m.ENTITY_ID;

  -- ============================================================
-- PHASE 8E.9–8E.10 FINAL VERIFICATION
-- ============================================================

-- 1. Latest characteristic evidence must be unique.
SELECT
    RFQ_ID,
    SIMULATION_ID,
    CHARACTERISTIC_NAME,
    COUNT(*) AS DUPLICATE_COUNT
FROM VW_BMCS_SCORING_DETAIL_LATEST_V2
GROUP BY RFQ_ID, SIMULATION_ID, CHARACTERISTIC_NAME
HAVING COUNT(*) > 1;

-- Expected zero rows.


-- 2. No RFQ/simulation may have more than four latest characteristics.
SELECT
    RFQ_ID,
    SIMULATION_ID,
    COUNT(*) AS CHARACTERISTIC_ROWS,
    COUNT(DISTINCT CHARACTERISTIC_NAME) AS DISTINCT_CHARACTERISTICS
FROM VW_BMCS_SCORING_DETAIL_LATEST_V2
GROUP BY RFQ_ID, SIMULATION_ID
HAVING COUNT(*) > 4
    OR COUNT(*) <> COUNT(DISTINCT CHARACTERISTIC_NAME);

-- Expected zero rows.


-- 3. Review adapter outputs and explicit proxy/OOD flags.
SELECT
    RFQ_ID,
    SIMULATION_ID,
    CONFIGURATION_VERSION,
    SOURCE_LANGUAGE,
    DOCUMENT_LENGTH_CHARS,
    EXTRACTED_ENGINE,
    EXTRACTED_CAB,
    EXTRACTED_WHEEL,
    EXTRACTED_COLOR,
    ENGINE_EXTRACTION_CONFIDENCE,
    CAB_EXTRACTION_CONFIDENCE,
    WHEEL_EXTRACTION_CONFIDENCE,
    COLOR_EXTRACTION_CONFIDENCE,
    VALID_EXTRACTED_VALUE_COUNT,
    TEXT_SUPPORTED_VALUE_COUNT,
    RULE_BMCS_SCORE,
    CORTEX_CONFIDENCE_SCORE,
    DEVELOPMENT_HYBRID_BMCS_SCORE,
    CHARACTERISTIC_ROW_COUNT,
    PROXY_FEATURE_COUNT,
    FEATURE_QUALITY_PASS_FLAG,
    MODEL_OOD_FLAG,
    OOD_LANGUAGE_FLAG,
    OOD_DOCUMENT_LENGTH_FLAG,
    ADAPTER_STATUS
FROM BMCS_PHASE7_FEATURE_ADAPTER_FINAL_V2
ORDER BY FEATURE_AS_OF_TIMESTAMP DESC, RFQ_ID;


-- 4. Adapter coverage must have one unique entity per row.
SELECT
    COUNT(*) AS TOTAL_ADAPTER_ROWS,
    COUNT(DISTINCT ENTITY_ID) AS DISTINCT_ENTITIES,
    COUNT_IF(FEATURE_QUALITY_PASS_FLAG=TRUE) AS ML_ELIGIBLE_ROWS,
    COUNT_IF(FEATURE_QUALITY_PASS_FLAG=FALSE) AS FALLBACK_ROWS,
    COUNT_IF(MODEL_OOD_FLAG=TRUE) AS OOD_ROWS,
    COUNT_IF(OOD_LANGUAGE_FLAG=TRUE) AS OOD_LANGUAGE_ROWS,
    COUNT_IF(OOD_DOCUMENT_LENGTH_FLAG=TRUE) AS OOD_DOCUMENT_LENGTH_ROWS
FROM BMCS_PHASE7_FEATURE_ADAPTER_FINAL_V2;


-- 5. Prepare a controlled all-RFQ batch.
CALL PREPARE_BMCS_PHASE7_SHADOW_BATCH_FINAL_V2(
    'BMCS_PHASE7_SHADOW_001',
    NULL
);


-- 6. Verify prepared queue.
SELECT
    SCORING_BATCH_ID,
    COUNT(*) AS INPUT_ROWS,
    COUNT_IF(FEATURE_QUALITY_PASS_FLAG=TRUE) AS ML_ELIGIBLE_ROWS,
    COUNT_IF(FEATURE_QUALITY_PASS_FLAG=FALSE) AS FALLBACK_ROWS,
    COUNT_IF(MODEL_OOD_FLAG=TRUE) AS OOD_ROWS,
    COUNT_IF(INPUT_STATUS='PENDING') AS PENDING_ROWS
FROM BMCS_PHASE7_SCORING_INPUT_FINAL_V2
WHERE SCORING_BATCH_ID='BMCS_PHASE7_SHADOW_001'
GROUP BY SCORING_BATCH_ID;


-- 7. Run phase8e_9_to_10_score_phase7_bmcs_shadow_final_v2.py.
-- Then check the run log.
SELECT *
FROM BMCS_PHASE7_SHADOW_RUN_LOG_FINAL_V2
ORDER BY CREATED_AT DESC;


-- 8. Output integrity and authority checks.
SELECT
    SCORING_BATCH_ID,
    COUNT(*) AS OUTPUT_ROWS,
    COUNT_IF(CALIBRATED_ML_PROBABILITY IS NOT NULL) AS ML_SCORED_ROWS,
    COUNT_IF(ML_FALLBACK_REASON IS NOT NULL) AS FALLBACK_ROWS,
    COUNT_IF(ML_ADVISORY_TRUST_BAND='OOD_ADVISORY') AS OOD_ADVISORY_ROWS,
    COUNT_IF(
        RAW_ML_PROBABILITY IS NOT NULL
        AND (RAW_ML_PROBABILITY<0 OR RAW_ML_PROBABILITY>1)
    ) AS INVALID_RAW_PROBABILITY_ROWS,
    COUNT_IF(
        CALIBRATED_ML_PROBABILITY IS NOT NULL
        AND (CALIBRATED_ML_PROBABILITY<0 OR CALIBRATED_ML_PROBABILITY>1)
    ) AS INVALID_CALIBRATED_PROBABILITY_ROWS,
    COUNT_IF(
        ML_BMCS_SCORE IS NOT NULL
        AND (ML_BMCS_SCORE<0 OR ML_BMCS_SCORE>100)
    ) AS INVALID_ML_SCORE_ROWS,
    COUNT_IF(SHADOW_REVIEW_ACTION<>'ENGINEERING_REVIEW_REQUIRED') AS INVALID_ACTION_ROWS,
    COUNT_IF(
        DEPLOYMENT_MODE<>'SHADOW'
        OR ML_ADVISORY_ONLY_FLAG<>TRUE
        OR OFFICIAL_COST_IMPACT_ALLOWED_FLAG<>FALSE
        OR BUSINESS_DECISION_ALLOWED_FLAG<>FALSE
    ) AS INVALID_AUTHORITY_ROWS
FROM BMCS_PHASE7_SHADOW_SCORE_FINAL_V2
WHERE SCORING_BATCH_ID='BMCS_PHASE7_SHADOW_001'
GROUP BY SCORING_BATCH_ID;


-- 9. Official and ML scores side by side.
SELECT
    RFQ_ID,
    SIMULATION_ID,
    ENGINE,
    CAB,
    WHEEL,
    COLOR,
    OFFICIAL_RULE_BMCS_SCORE,
    OFFICIAL_CORTEX_BMCS_SCORE,
    OFFICIAL_HYBRID_BMCS_SCORE,
    RAW_ML_PROBABILITY,
    CALIBRATED_ML_PROBABILITY,
    ML_BMCS_SCORE,
    ML_ADVISORY_TRUST_BAND,
    FEATURE_QUALITY_PASS_FLAG,
    MODEL_OOD_FLAG,
    PROXY_FEATURE_COUNT,
    ADAPTER_STATUS,
    ML_FALLBACK_REASON,
    SHADOW_REVIEW_ACTION,
    OFFICIAL_REVIEW_STATUS,
    OFFICIAL_REVIEW_REQUIRED_FLAG,
    OFFICIAL_TRUSTED_COST_ALLOWED_FLAG,
    OFFICIAL_TRUST_SOURCE,
    PHYSICAL_MODEL_NAME,
    PHYSICAL_MODEL_VERSION,
    DEPLOYMENT_MODE,
    ML_ADVISORY_ONLY_FLAG,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG,
    SCORED_AT
FROM VW_RFQ_BMCS_ML_SHADOW_STATUS_FINAL_V2
ORDER BY SCORED_AT DESC NULLS LAST, RFQ_ID;


-- 10. Physical model remains the atomic calibrated version.
SHOW VERSIONS
IN MODEL KMAT_COST_MODEL_DB.CORE_ML.BMCS_CALIBRATED_CLASSIFIER;

SHOW FUNCTIONS
IN MODEL KMAT_COST_MODEL_DB.CORE_ML.BMCS_CALIBRATED_CLASSIFIER
VERSION V2_SHADOW_2;