USE ROLE SYSADMIN;
USE WAREHOUSE KMAT_WH;
USE DATABASE KMAT_COST_MODEL_DB;
USE SCHEMA CORE_ML;

-- ============================================================
-- PHASE 8D.7
-- TDS V2 shadow output, diagnostics and governance
-- Run after the Python model-registration worksheet succeeds.
-- ============================================================


-- ------------------------------------------------------------
-- 1. RAW VERSUS CLIPPED RANGE DIAGNOSTICS
-- ------------------------------------------------------------

CREATE OR REPLACE TABLE TDS_PREDICTION_RANGE_DIAGNOSTICS_V2 AS
SELECT
    COUNT(*) AS OBSERVATION_COUNT,

    COUNT_IF(
        RAW_PREDICTED_TDS_FACTOR IS NULL
    ) AS NULL_RAW_PREDICTIONS,

    COUNT_IF(
        PREDICTED_TDS_FACTOR IS NULL
    ) AS NULL_SELECTED_PREDICTIONS,

    COUNT_IF(
        RAW_PREDICTED_TDS_FACTOR < 1.0
        OR RAW_PREDICTED_TDS_FACTOR > 3.5
    ) AS RAW_RANGE_VIOLATION_ROWS,

    COUNT_IF(
        ABS(
            RAW_PREDICTED_TDS_FACTOR
            - PREDICTED_TDS_FACTOR
        ) > 0.0000001
    ) AS CLIPPED_PREDICTION_ROWS,

    MIN(RAW_PREDICTED_TDS_FACTOR)
        AS RAW_PREDICTION_MIN,

    MAX(RAW_PREDICTED_TDS_FACTOR)
        AS RAW_PREDICTION_MAX,

    MIN(PREDICTED_TDS_FACTOR)
        AS SELECTED_PREDICTION_MIN,

    MAX(PREDICTED_TDS_FACTOR)
        AS SELECTED_PREDICTION_MAX,

    CURRENT_TIMESTAMP() AS CALCULATED_AT

FROM TDS_TEST_PREDICTIONS_V2;


-- ------------------------------------------------------------
-- 2. GOVERNED SHADOW OUTPUT
-- ------------------------------------------------------------

CREATE OR REPLACE VIEW TDS_SHADOW_OUTPUT_V2 AS
SELECT
    ENTITY_ID AS OPERATION_RUN_ID,
    FEATURE_AS_OF_DATE AS RUN_DATE,

    WORK_CENTER_ID,
    MACHINE_ID,
    OPERATION_ID,

    ENGINE,
    CAB,
    WHEEL,

    TARGET_TDS_FACTOR AS ACTUAL_TDS_FACTOR,

    DEVELOPMENT_RULE_BASELINE_FACTOR
        AS DETERMINISTIC_RULE_FACTOR,

    RAW_PREDICTED_TDS_FACTOR,
    PREDICTED_TDS_FACTOR
        AS RANGE_CONTROLLED_ML_FACTOR,

    CASE
        WHEN RAW_PREDICTED_TDS_FACTOR IS NULL
            THEN 'FALLBACK_NULL_PREDICTION'

        WHEN PREDICTED_TDS_FACTOR < 1.0
          OR PREDICTED_TDS_FACTOR > 3.5
            THEN 'FALLBACK_RANGE_FAILURE'

        ELSE 'ML_SHADOW_ACCEPTED'
    END AS SHADOW_SELECTION_STATUS,

    CASE
        WHEN RAW_PREDICTED_TDS_FACTOR IS NOT NULL
         AND PREDICTED_TDS_FACTOR BETWEEN 1.0 AND 3.5
            THEN PREDICTED_TDS_FACTOR

        ELSE DEVELOPMENT_RULE_BASELINE_FACTOR
    END AS SELECTED_SHADOW_TDS_FACTOR,

    ABSOLUTE_ERROR,
    UNDERPREDICTION_FLAG,
    SEVERE_UNDERPREDICTION_FLAG,
    HIGH_STRAIN_FLAG,

    'TDS_XGB_REGRESSOR'
        AS PHYSICAL_MODEL_NAME,

    'V2_SHADOW_1'
        AS PHYSICAL_MODEL_VERSION,

    MODEL_NAME
        AS EXPERIMENT_MODEL_NAME,

    MODEL_VERSION
        AS EXPERIMENT_MODEL_VERSION,

    FEATURE_SET_VERSION,

    'SYNTHETIC'
        AS TRAINING_DATA_CLASS,

    'ACCEPTED_FOR_SHADOW_WITH_MONITORING'
        AS VALIDATION_STATUS,

    'SHADOW'
        AS DEPLOYMENT_MODE,

    FALSE
        AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,

    FALSE
        AS BUSINESS_DECISION_ALLOWED_FLAG,

    CURRENT_TIMESTAMP() AS CREATED_AT

FROM TDS_TEST_PREDICTIONS_V2;


-- ------------------------------------------------------------
-- 3. PROPERLY TYPED GOVERNANCE RECORD
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS TDS_MODEL_GOVERNANCE (
    PHYSICAL_MODEL_NAME VARCHAR NOT NULL,
    PHYSICAL_MODEL_VERSION VARCHAR NOT NULL,
    EXPERIMENT_MODEL_NAME VARCHAR NOT NULL,
    FEATURE_SET_VERSION VARCHAR NOT NULL,

    TRAINING_DATA_CLASS VARCHAR NOT NULL,
    VALIDATION_STATUS VARCHAR NOT NULL,
    DEPLOYMENT_MODE VARCHAR NOT NULL,

    OFFICIAL_COST_IMPACT_ALLOWED_FLAG BOOLEAN NOT NULL,
    BUSINESS_DECISION_ALLOWED_FLAG BOOLEAN NOT NULL,

    METRICS_JSON VARIANT,
    RISK_NOTE VARCHAR,
    DECISION_REASON VARCHAR,

    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


MERGE INTO TDS_MODEL_GOVERNANCE target
USING (
    SELECT
        'TDS_XGB_REGRESSOR'
            AS PHYSICAL_MODEL_NAME,

        'V2_SHADOW_1'
            AS PHYSICAL_MODEL_VERSION,

        MODEL_NAME
            AS EXPERIMENT_MODEL_NAME,

        'TDS_FEATURES_V2'
            AS FEATURE_SET_VERSION,

        'SYNTHETIC'
            AS TRAINING_DATA_CLASS,

        'ACCEPTED_FOR_SHADOW_WITH_MONITORING'
            AS VALIDATION_STATUS,

        'SHADOW'
            AS DEPLOYMENT_MODE,

        FALSE
            AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,

        FALSE
            AS BUSINESS_DECISION_ALLOWED_FLAG,

        OBJECT_CONSTRUCT_KEEP_NULL(
            'test_mae', MAE,
            'test_rmse', RMSE,
            'test_median_absolute_error',
                MEDIAN_ABSOLUTE_ERROR,
            'underprediction_rate',
                UNDERPREDICTION_RATE,
            'severe_underprediction_rate',
                SEVERE_UNDERPREDICTION_RATE,
            'high_strain_mae',
                HIGH_STRAIN_MAE,
            'high_strain_underprediction_rate',
                HIGH_STRAIN_UNDERPREDICTION_RATE,
            'high_strain_severe_underprediction_rate',
                HIGH_STRAIN_SEVERE_UNDERPREDICTION_RATE,
            'rule_baseline_mae',
                RULE_BASELINE_MAE,
            'rule_baseline_rmse',
                RULE_BASELINE_RMSE,
            'mae_improvement_vs_rule',
                MAE_IMPROVEMENT_VS_RULE,
            'rmse_improvement_vs_rule',
                RMSE_IMPROVEMENT_VS_RULE
        ) AS METRICS_JSON,

        'High-strain underprediction occurs in 61.4 percent of high-strain rows, but severe high-strain underprediction is 8.46 percent. Production promotion requires real-data validation and an approved asymmetric-risk policy.'
            AS RISK_NOTE,

        'XGB_V1_BALANCED passed validation selection and substantially outperformed the deterministic development benchmark on the untouched synthetic test period.'
            AS DECISION_REASON

    FROM TDS_TEST_EVALUATION_V2
) source

ON target.PHYSICAL_MODEL_NAME =
    source.PHYSICAL_MODEL_NAME
AND target.PHYSICAL_MODEL_VERSION =
    source.PHYSICAL_MODEL_VERSION

WHEN MATCHED THEN UPDATE SET
    EXPERIMENT_MODEL_NAME =
        source.EXPERIMENT_MODEL_NAME,
    FEATURE_SET_VERSION =
        source.FEATURE_SET_VERSION,
    TRAINING_DATA_CLASS =
        source.TRAINING_DATA_CLASS,
    VALIDATION_STATUS =
        source.VALIDATION_STATUS,
    DEPLOYMENT_MODE =
        source.DEPLOYMENT_MODE,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG =
        source.OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG =
        source.BUSINESS_DECISION_ALLOWED_FLAG,
    METRICS_JSON =
        source.METRICS_JSON,
    RISK_NOTE =
        source.RISK_NOTE,
    DECISION_REASON =
        source.DECISION_REASON,
    UPDATED_AT =
        CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT (
    PHYSICAL_MODEL_NAME,
    PHYSICAL_MODEL_VERSION,
    EXPERIMENT_MODEL_NAME,
    FEATURE_SET_VERSION,

    TRAINING_DATA_CLASS,
    VALIDATION_STATUS,
    DEPLOYMENT_MODE,

    OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG,

    METRICS_JSON,
    RISK_NOTE,
    DECISION_REASON
)
VALUES (
    source.PHYSICAL_MODEL_NAME,
    source.PHYSICAL_MODEL_VERSION,
    source.EXPERIMENT_MODEL_NAME,
    source.FEATURE_SET_VERSION,

    source.TRAINING_DATA_CLASS,
    source.VALIDATION_STATUS,
    source.DEPLOYMENT_MODE,

    source.OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    source.BUSINESS_DECISION_ALLOWED_FLAG,

    source.METRICS_JSON,
    source.RISK_NOTE,
    source.DECISION_REASON
);


-- ------------------------------------------------------------
-- 4. MERGE INTO THE SHARED PROJECT MODEL REGISTRY
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS MODEL_REGISTRY (
    MODEL_NAME VARCHAR NOT NULL,
    MODEL_VERSION VARCHAR NOT NULL,
    MODEL_FAMILY VARCHAR NOT NULL,
    FEATURE_SET_VERSION VARCHAR NOT NULL,
    TRAINING_DATA_CLASS VARCHAR NOT NULL,

    VALIDATION_STATUS VARCHAR NOT NULL,
    DEPLOYMENT_MODE VARCHAR NOT NULL,

    OFFICIAL_COST_IMPACT_ALLOWED_FLAG BOOLEAN NOT NULL,
    BUSINESS_DECISION_ALLOWED_FLAG BOOLEAN NOT NULL,

    METRICS_JSON VARIANT,
    DECISION_REASON VARCHAR,

    MODEL_OWNER VARCHAR,
    BUSINESS_OWNER VARCHAR,

    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


MERGE INTO MODEL_REGISTRY target
USING (
    SELECT
        PHYSICAL_MODEL_NAME
            AS MODEL_NAME,

        PHYSICAL_MODEL_VERSION
            AS MODEL_VERSION,

        'XGBOOST_REGRESSION'
            AS MODEL_FAMILY,

        FEATURE_SET_VERSION,

        TRAINING_DATA_CLASS,
        VALIDATION_STATUS,
        DEPLOYMENT_MODE,

        OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
        BUSINESS_DECISION_ALLOWED_FLAG,

        METRICS_JSON,
        DECISION_REASON,

        'DATA_SCIENCE'
            AS MODEL_OWNER,

        'MANUFACTURING_FINANCE'
            AS BUSINESS_OWNER

    FROM TDS_MODEL_GOVERNANCE
    WHERE PHYSICAL_MODEL_NAME = 'TDS_XGB_REGRESSOR'
      AND PHYSICAL_MODEL_VERSION = 'V2_SHADOW_1'
) source

ON target.MODEL_NAME = source.MODEL_NAME
AND target.MODEL_VERSION = source.MODEL_VERSION

WHEN MATCHED THEN UPDATE SET
    MODEL_FAMILY = source.MODEL_FAMILY,
    FEATURE_SET_VERSION = source.FEATURE_SET_VERSION,
    TRAINING_DATA_CLASS = source.TRAINING_DATA_CLASS,
    VALIDATION_STATUS = source.VALIDATION_STATUS,
    DEPLOYMENT_MODE = source.DEPLOYMENT_MODE,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG =
        source.OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG =
        source.BUSINESS_DECISION_ALLOWED_FLAG,
    METRICS_JSON = source.METRICS_JSON,
    DECISION_REASON = source.DECISION_REASON,
    MODEL_OWNER = source.MODEL_OWNER,
    BUSINESS_OWNER = source.BUSINESS_OWNER,
    UPDATED_AT = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT (
    MODEL_NAME,
    MODEL_VERSION,
    MODEL_FAMILY,
    FEATURE_SET_VERSION,
    TRAINING_DATA_CLASS,

    VALIDATION_STATUS,
    DEPLOYMENT_MODE,

    OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG,

    METRICS_JSON,
    DECISION_REASON,

    MODEL_OWNER,
    BUSINESS_OWNER
)
VALUES (
    source.MODEL_NAME,
    source.MODEL_VERSION,
    source.MODEL_FAMILY,
    source.FEATURE_SET_VERSION,
    source.TRAINING_DATA_CLASS,

    source.VALIDATION_STATUS,
    source.DEPLOYMENT_MODE,

    source.OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    source.BUSINESS_DECISION_ALLOWED_FLAG,

    source.METRICS_JSON,
    source.DECISION_REASON,

    source.MODEL_OWNER,
    source.BUSINESS_OWNER
);


-- ------------------------------------------------------------
-- 5. FINAL CHECKS
-- ------------------------------------------------------------

SELECT *
FROM TDS_PREDICTION_RANGE_DIAGNOSTICS_V2;


SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT OPERATION_RUN_ID)
        AS DISTINCT_OPERATION_RUNS,

    COUNT_IF(
        SELECTED_SHADOW_TDS_FACTOR IS NULL
    ) AS NULL_SELECTED_FACTORS,

    COUNT_IF(
        SELECTED_SHADOW_TDS_FACTOR < 1.0
        OR SELECTED_SHADOW_TDS_FACTOR > 3.5
    ) AS INVALID_SELECTED_FACTORS,

    COUNT_IF(
        DEPLOYMENT_MODE <> 'SHADOW'
        OR OFFICIAL_COST_IMPACT_ALLOWED_FLAG <> FALSE
        OR BUSINESS_DECISION_ALLOWED_FLAG <> FALSE
    ) AS INVALID_AUTHORITY_ROWS

FROM TDS_SHADOW_OUTPUT_V2;


SELECT *
FROM TDS_MODEL_GOVERNANCE
WHERE PHYSICAL_MODEL_NAME = 'TDS_XGB_REGRESSOR'
  AND PHYSICAL_MODEL_VERSION = 'V2_SHADOW_1';


SELECT
    MODEL_NAME,
    MODEL_VERSION,
    MODEL_FAMILY,
    FEATURE_SET_VERSION,
    TRAINING_DATA_CLASS,
    VALIDATION_STATUS,
    DEPLOYMENT_MODE,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG,
    METRICS_JSON,
    DECISION_REASON

FROM MODEL_REGISTRY
WHERE MODEL_NAME = 'TDS_XGB_REGRESSOR'
  AND MODEL_VERSION = 'V2_SHADOW_1';


-- Physical Snowflake Model Registry checks.
SHOW MODELS
LIKE 'TDS_XGB_REGRESSOR'
IN SCHEMA KMAT_COST_MODEL_DB.CORE_ML;

SHOW VERSIONS
IN MODEL KMAT_COST_MODEL_DB.CORE_ML.TDS_XGB_REGRESSOR;

SHOW FUNCTIONS
IN MODEL KMAT_COST_MODEL_DB.CORE_ML.TDS_XGB_REGRESSOR
VERSION V2_SHADOW_1;

SELECT *
FROM KMAT_COST_MODEL_DB.CORE_ML.TDS_MODEL_REGISTRATION_LOG_V2
ORDER BY CREATED_AT DESC;

SHOW MODELS
LIKE 'TDS_XGB_REGRESSOR'
IN SCHEMA KMAT_COST_MODEL_DB.CORE_ML;

SHOW VERSIONS
IN MODEL KMAT_COST_MODEL_DB.CORE_ML.TDS_XGB_REGRESSOR;

SHOW FUNCTIONS
IN MODEL KMAT_COST_MODEL_DB.CORE_ML.TDS_XGB_REGRESSOR
VERSION V2_SHADOW_1;

SELECT
    ENTITY_ID,
    MODEL(
        KMAT_COST_MODEL_DB.CORE_ML.TDS_XGB_REGRESSOR
    )!PREDICT(
        KMAT_ID,
        WORK_CENTER_ID,
        MACHINE_ID,
        OPERATION_ID,
        ENGINE,
        CAB,
        WHEEL,
        COLOR,
        MACHINE_AGE_YEARS,
        MACHINE_HOURS_RUN,
        PRE_RUN_VIBRATION_MM_S,
        PRE_RUN_TEMPERATURE_C,
        DAYS_SINCE_MAINTENANCE,
        TOOL_USAGE_CYCLES_PRE_RUN,
        SETUP_TIME_MINUTES,
        CONFIG_COMPLEXITY_SCORE,
        STANDARD_MAINTENANCE_COST_USD,
        SHIFT_LOAD_PCT,
        OPERATOR_EXPERIENCE_YEARS,
        RECENT_30D_DOWNTIME_MIN,
        PRIOR_30D_MAINTENANCE_COUNT,
        MACHINE_HEALTH_SCORE,
        PRIOR_30D_MEAN_VIBRATION_MM_S,
        PRIOR_WORK_CENTER_TDS_AVG
    ) AS PREDICTION_RESULT
FROM KMAT_COST_MODEL_DB.CORE_ML.TDS_MODEL_DATASET_V2
WHERE DATA_SPLIT = 'TEST'
LIMIT 5;

-- ============================================================
-- PHASE 8D.7
-- TDS V2 shadow output, diagnostics and governance
-- Run after the Python model-registration worksheet succeeds.
-- ============================================================


-- ------------------------------------------------------------
-- 1. RAW VERSUS CLIPPED RANGE DIAGNOSTICS
-- ------------------------------------------------------------

CREATE OR REPLACE TABLE TDS_PREDICTION_RANGE_DIAGNOSTICS_V2 AS
SELECT
    COUNT(*) AS OBSERVATION_COUNT,

    COUNT_IF(
        RAW_PREDICTED_TDS_FACTOR IS NULL
    ) AS NULL_RAW_PREDICTIONS,

    COUNT_IF(
        PREDICTED_TDS_FACTOR IS NULL
    ) AS NULL_SELECTED_PREDICTIONS,

    COUNT_IF(
        RAW_PREDICTED_TDS_FACTOR < 1.0
        OR RAW_PREDICTED_TDS_FACTOR > 3.5
    ) AS RAW_RANGE_VIOLATION_ROWS,

    COUNT_IF(
        ABS(
            RAW_PREDICTED_TDS_FACTOR
            - PREDICTED_TDS_FACTOR
        ) > 0.0000001
    ) AS CLIPPED_PREDICTION_ROWS,

    MIN(RAW_PREDICTED_TDS_FACTOR)
        AS RAW_PREDICTION_MIN,

    MAX(RAW_PREDICTED_TDS_FACTOR)
        AS RAW_PREDICTION_MAX,

    MIN(PREDICTED_TDS_FACTOR)
        AS SELECTED_PREDICTION_MIN,

    MAX(PREDICTED_TDS_FACTOR)
        AS SELECTED_PREDICTION_MAX,

    CURRENT_TIMESTAMP() AS CALCULATED_AT

FROM TDS_TEST_PREDICTIONS_V2;


-- ------------------------------------------------------------
-- 2. GOVERNED SHADOW OUTPUT
-- ------------------------------------------------------------

CREATE OR REPLACE VIEW TDS_SHADOW_OUTPUT_V2 AS
SELECT
    ENTITY_ID AS OPERATION_RUN_ID,
    FEATURE_AS_OF_DATE AS RUN_DATE,

    WORK_CENTER_ID,
    MACHINE_ID,
    OPERATION_ID,

    ENGINE,
    CAB,
    WHEEL,

    TARGET_TDS_FACTOR AS ACTUAL_TDS_FACTOR,

    DEVELOPMENT_RULE_BASELINE_FACTOR
        AS DETERMINISTIC_RULE_FACTOR,

    RAW_PREDICTED_TDS_FACTOR,
    PREDICTED_TDS_FACTOR
        AS RANGE_CONTROLLED_ML_FACTOR,

    CASE
        WHEN RAW_PREDICTED_TDS_FACTOR IS NULL
            THEN 'FALLBACK_NULL_PREDICTION'

        WHEN PREDICTED_TDS_FACTOR < 1.0
          OR PREDICTED_TDS_FACTOR > 3.5
            THEN 'FALLBACK_RANGE_FAILURE'

        ELSE 'ML_SHADOW_ACCEPTED'
    END AS SHADOW_SELECTION_STATUS,

    CASE
        WHEN RAW_PREDICTED_TDS_FACTOR IS NOT NULL
         AND PREDICTED_TDS_FACTOR BETWEEN 1.0 AND 3.5
            THEN PREDICTED_TDS_FACTOR

        ELSE DEVELOPMENT_RULE_BASELINE_FACTOR
    END AS SELECTED_SHADOW_TDS_FACTOR,

    ABSOLUTE_ERROR,
    UNDERPREDICTION_FLAG,
    SEVERE_UNDERPREDICTION_FLAG,
    HIGH_STRAIN_FLAG,

    'TDS_XGB_REGRESSOR'
        AS PHYSICAL_MODEL_NAME,

    'V2_SHADOW_1'
        AS PHYSICAL_MODEL_VERSION,

    MODEL_NAME
        AS EXPERIMENT_MODEL_NAME,

    MODEL_VERSION
        AS EXPERIMENT_MODEL_VERSION,

    FEATURE_SET_VERSION,

    'SYNTHETIC'
        AS TRAINING_DATA_CLASS,

    'ACCEPTED_FOR_SHADOW_WITH_MONITORING'
        AS VALIDATION_STATUS,

    'SHADOW'
        AS DEPLOYMENT_MODE,

    FALSE
        AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,

    FALSE
        AS BUSINESS_DECISION_ALLOWED_FLAG,

    CURRENT_TIMESTAMP() AS CREATED_AT

FROM TDS_TEST_PREDICTIONS_V2;


-- ------------------------------------------------------------
-- 3. PROPERLY TYPED GOVERNANCE RECORD
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS TDS_MODEL_GOVERNANCE (
    PHYSICAL_MODEL_NAME VARCHAR NOT NULL,
    PHYSICAL_MODEL_VERSION VARCHAR NOT NULL,
    EXPERIMENT_MODEL_NAME VARCHAR NOT NULL,
    FEATURE_SET_VERSION VARCHAR NOT NULL,

    TRAINING_DATA_CLASS VARCHAR NOT NULL,
    VALIDATION_STATUS VARCHAR NOT NULL,
    DEPLOYMENT_MODE VARCHAR NOT NULL,

    OFFICIAL_COST_IMPACT_ALLOWED_FLAG BOOLEAN NOT NULL,
    BUSINESS_DECISION_ALLOWED_FLAG BOOLEAN NOT NULL,

    METRICS_JSON VARIANT,
    RISK_NOTE VARCHAR,
    DECISION_REASON VARCHAR,

    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


MERGE INTO TDS_MODEL_GOVERNANCE target
USING (
    SELECT
        'TDS_XGB_REGRESSOR'
            AS PHYSICAL_MODEL_NAME,

        'V2_SHADOW_1'
            AS PHYSICAL_MODEL_VERSION,

        MODEL_NAME
            AS EXPERIMENT_MODEL_NAME,

        'TDS_FEATURES_V2'
            AS FEATURE_SET_VERSION,

        'SYNTHETIC'
            AS TRAINING_DATA_CLASS,

        'ACCEPTED_FOR_SHADOW_WITH_MONITORING'
            AS VALIDATION_STATUS,

        'SHADOW'
            AS DEPLOYMENT_MODE,

        FALSE
            AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,

        FALSE
            AS BUSINESS_DECISION_ALLOWED_FLAG,

        OBJECT_CONSTRUCT_KEEP_NULL(
            'test_mae', MAE,
            'test_rmse', RMSE,
            'test_median_absolute_error',
                MEDIAN_ABSOLUTE_ERROR,
            'underprediction_rate',
                UNDERPREDICTION_RATE,
            'severe_underprediction_rate',
                SEVERE_UNDERPREDICTION_RATE,
            'high_strain_mae',
                HIGH_STRAIN_MAE,
            'high_strain_underprediction_rate',
                HIGH_STRAIN_UNDERPREDICTION_RATE,
            'high_strain_severe_underprediction_rate',
                HIGH_STRAIN_SEVERE_UNDERPREDICTION_RATE,
            'rule_baseline_mae',
                RULE_BASELINE_MAE,
            'rule_baseline_rmse',
                RULE_BASELINE_RMSE,
            'mae_improvement_vs_rule',
                MAE_IMPROVEMENT_VS_RULE,
            'rmse_improvement_vs_rule',
                RMSE_IMPROVEMENT_VS_RULE
        ) AS METRICS_JSON,

        'High-strain underprediction occurs in 61.4 percent of high-strain rows, but severe high-strain underprediction is 8.46 percent. Production promotion requires real-data validation and an approved asymmetric-risk policy.'
            AS RISK_NOTE,

        'XGB_V1_BALANCED passed validation selection and substantially outperformed the deterministic development benchmark on the untouched synthetic test period.'
            AS DECISION_REASON

    FROM TDS_TEST_EVALUATION_V2
) source

ON target.PHYSICAL_MODEL_NAME =
    source.PHYSICAL_MODEL_NAME
AND target.PHYSICAL_MODEL_VERSION =
    source.PHYSICAL_MODEL_VERSION

WHEN MATCHED THEN UPDATE SET
    EXPERIMENT_MODEL_NAME =
        source.EXPERIMENT_MODEL_NAME,
    FEATURE_SET_VERSION =
        source.FEATURE_SET_VERSION,
    TRAINING_DATA_CLASS =
        source.TRAINING_DATA_CLASS,
    VALIDATION_STATUS =
        source.VALIDATION_STATUS,
    DEPLOYMENT_MODE =
        source.DEPLOYMENT_MODE,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG =
        source.OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG =
        source.BUSINESS_DECISION_ALLOWED_FLAG,
    METRICS_JSON =
        source.METRICS_JSON,
    RISK_NOTE =
        source.RISK_NOTE,
    DECISION_REASON =
        source.DECISION_REASON,
    UPDATED_AT =
        CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT (
    PHYSICAL_MODEL_NAME,
    PHYSICAL_MODEL_VERSION,
    EXPERIMENT_MODEL_NAME,
    FEATURE_SET_VERSION,

    TRAINING_DATA_CLASS,
    VALIDATION_STATUS,
    DEPLOYMENT_MODE,

    OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG,

    METRICS_JSON,
    RISK_NOTE,
    DECISION_REASON
)
VALUES (
    source.PHYSICAL_MODEL_NAME,
    source.PHYSICAL_MODEL_VERSION,
    source.EXPERIMENT_MODEL_NAME,
    source.FEATURE_SET_VERSION,

    source.TRAINING_DATA_CLASS,
    source.VALIDATION_STATUS,
    source.DEPLOYMENT_MODE,

    source.OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    source.BUSINESS_DECISION_ALLOWED_FLAG,

    source.METRICS_JSON,
    source.RISK_NOTE,
    source.DECISION_REASON
);


-- ------------------------------------------------------------
-- 4. MERGE INTO THE SHARED PROJECT MODEL REGISTRY
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS MODEL_REGISTRY (
    MODEL_NAME VARCHAR NOT NULL,
    MODEL_VERSION VARCHAR NOT NULL,
    MODEL_FAMILY VARCHAR NOT NULL,
    FEATURE_SET_VERSION VARCHAR NOT NULL,
    TRAINING_DATA_CLASS VARCHAR NOT NULL,

    VALIDATION_STATUS VARCHAR NOT NULL,
    DEPLOYMENT_MODE VARCHAR NOT NULL,

    OFFICIAL_COST_IMPACT_ALLOWED_FLAG BOOLEAN NOT NULL,
    BUSINESS_DECISION_ALLOWED_FLAG BOOLEAN NOT NULL,

    METRICS_JSON VARIANT,
    DECISION_REASON VARCHAR,

    MODEL_OWNER VARCHAR,
    BUSINESS_OWNER VARCHAR,

    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


MERGE INTO MODEL_REGISTRY target
USING (
    SELECT
        PHYSICAL_MODEL_NAME
            AS MODEL_NAME,

        PHYSICAL_MODEL_VERSION
            AS MODEL_VERSION,

        'XGBOOST_REGRESSION'
            AS MODEL_FAMILY,

        FEATURE_SET_VERSION,

        TRAINING_DATA_CLASS,
        VALIDATION_STATUS,
        DEPLOYMENT_MODE,

        OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
        BUSINESS_DECISION_ALLOWED_FLAG,

        METRICS_JSON,
        DECISION_REASON,

        'DATA_SCIENCE'
            AS MODEL_OWNER,

        'MANUFACTURING_FINANCE'
            AS BUSINESS_OWNER

    FROM TDS_MODEL_GOVERNANCE
    WHERE PHYSICAL_MODEL_NAME = 'TDS_XGB_REGRESSOR'
      AND PHYSICAL_MODEL_VERSION = 'V2_SHADOW_1'
) source

ON target.MODEL_NAME = source.MODEL_NAME
AND target.MODEL_VERSION = source.MODEL_VERSION

WHEN MATCHED THEN UPDATE SET
    MODEL_FAMILY = source.MODEL_FAMILY,
    FEATURE_SET_VERSION = source.FEATURE_SET_VERSION,
    TRAINING_DATA_CLASS = source.TRAINING_DATA_CLASS,
    VALIDATION_STATUS = source.VALIDATION_STATUS,
    DEPLOYMENT_MODE = source.DEPLOYMENT_MODE,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG =
        source.OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG =
        source.BUSINESS_DECISION_ALLOWED_FLAG,
    METRICS_JSON = source.METRICS_JSON,
    DECISION_REASON = source.DECISION_REASON,
    MODEL_OWNER = source.MODEL_OWNER,
    BUSINESS_OWNER = source.BUSINESS_OWNER,
    UPDATED_AT = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT (
    MODEL_NAME,
    MODEL_VERSION,
    MODEL_FAMILY,
    FEATURE_SET_VERSION,
    TRAINING_DATA_CLASS,

    VALIDATION_STATUS,
    DEPLOYMENT_MODE,

    OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG,

    METRICS_JSON,
    DECISION_REASON,

    MODEL_OWNER,
    BUSINESS_OWNER
)
VALUES (
    source.MODEL_NAME,
    source.MODEL_VERSION,
    source.MODEL_FAMILY,
    source.FEATURE_SET_VERSION,
    source.TRAINING_DATA_CLASS,

    source.VALIDATION_STATUS,
    source.DEPLOYMENT_MODE,

    source.OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    source.BUSINESS_DECISION_ALLOWED_FLAG,

    source.METRICS_JSON,
    source.DECISION_REASON,

    source.MODEL_OWNER,
    source.BUSINESS_OWNER
);


-- ------------------------------------------------------------
-- 5. FINAL CHECKS
-- ------------------------------------------------------------

SELECT *
FROM TDS_PREDICTION_RANGE_DIAGNOSTICS_V2;


SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT OPERATION_RUN_ID)
        AS DISTINCT_OPERATION_RUNS,

    COUNT_IF(
        SELECTED_SHADOW_TDS_FACTOR IS NULL
    ) AS NULL_SELECTED_FACTORS,

    COUNT_IF(
        SELECTED_SHADOW_TDS_FACTOR < 1.0
        OR SELECTED_SHADOW_TDS_FACTOR > 3.5
    ) AS INVALID_SELECTED_FACTORS,

    COUNT_IF(
        DEPLOYMENT_MODE <> 'SHADOW'
        OR OFFICIAL_COST_IMPACT_ALLOWED_FLAG <> FALSE
        OR BUSINESS_DECISION_ALLOWED_FLAG <> FALSE
    ) AS INVALID_AUTHORITY_ROWS

FROM TDS_SHADOW_OUTPUT_V2;


SELECT *
FROM TDS_MODEL_GOVERNANCE
WHERE PHYSICAL_MODEL_NAME = 'TDS_XGB_REGRESSOR'
  AND PHYSICAL_MODEL_VERSION = 'V2_SHADOW_1';


SELECT
    MODEL_NAME,
    MODEL_VERSION,
    MODEL_FAMILY,
    FEATURE_SET_VERSION,
    TRAINING_DATA_CLASS,
    VALIDATION_STATUS,
    DEPLOYMENT_MODE,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG,
    METRICS_JSON,
    DECISION_REASON

FROM MODEL_REGISTRY
WHERE MODEL_NAME = 'TDS_XGB_REGRESSOR'
  AND MODEL_VERSION = 'V2_SHADOW_1';


-- Physical Snowflake Model Registry checks.
SHOW MODELS
LIKE 'TDS_XGB_REGRESSOR'
IN SCHEMA KMAT_COST_MODEL_DB.CORE_ML;

SHOW VERSIONS
IN MODEL KMAT_COST_MODEL_DB.CORE_ML.TDS_XGB_REGRESSOR;

SHOW FUNCTIONS
IN MODEL KMAT_COST_MODEL_DB.CORE_ML.TDS_XGB_REGRESSOR
VERSION V2_SHADOW_1;

SELECT *
FROM KMAT_COST_MODEL_DB.CORE_ML.TDS_PREDICTION_RANGE_DIAGNOSTICS_V2;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT OPERATION_RUN_ID) AS DISTINCT_OPERATION_RUNS,
    COUNT_IF(SELECTED_SHADOW_TDS_FACTOR IS NULL)
        AS NULL_SELECTED_FACTORS,
    COUNT_IF(
        SELECTED_SHADOW_TDS_FACTOR < 1.0
        OR SELECTED_SHADOW_TDS_FACTOR > 3.5
    ) AS INVALID_SELECTED_FACTORS,
    COUNT_IF(
        DEPLOYMENT_MODE <> 'SHADOW'
        OR OFFICIAL_COST_IMPACT_ALLOWED_FLAG <> FALSE
        OR BUSINESS_DECISION_ALLOWED_FLAG <> FALSE
    ) AS INVALID_AUTHORITY_ROWS
FROM KMAT_COST_MODEL_DB.CORE_ML.TDS_SHADOW_OUTPUT_V2;

SELECT *
FROM KMAT_COST_MODEL_DB.CORE_ML.TDS_PREDICTION_RANGE_DIAGNOSTICS_V2;