USE ROLE SYSADMIN;
USE DATABASE KMAT_COST_MODEL_DB;
USE SCHEMA CORE_ML;

-- ============================================================
-- PHASE 8D.1-8D.3
-- TDS V2 ingestion, chronological split and feature contract
--
-- Upload tds_v2_training_data.csv to:
-- @CORE_ML.ML_SYNTHETIC_STAGE/tds_v2_training_data.csv
-- ============================================================

CREATE OR REPLACE TABLE TDS_SYNTHETIC_RAW_V2 (
    OPERATION_RUN_ID VARCHAR,
    RUN_DATE DATE,
    KMAT_ID VARCHAR,
    WORK_CENTER_ID VARCHAR,
    MACHINE_ID VARCHAR,
    OPERATION_ID VARCHAR,
    ENGINE VARCHAR,
    CAB VARCHAR,
    WHEEL VARCHAR,
    COLOR VARCHAR,

    MACHINE_AGE_YEARS FLOAT,
    MACHINE_HOURS_RUN FLOAT,
    PRE_RUN_VIBRATION_MM_S FLOAT,
    PRE_RUN_TEMPERATURE_C FLOAT,
    DAYS_SINCE_MAINTENANCE FLOAT,
    TOOL_USAGE_CYCLES_PRE_RUN FLOAT,
    SETUP_TIME_MINUTES FLOAT,
    CONFIG_COMPLEXITY_SCORE FLOAT,
    STANDARD_MAINTENANCE_COST_USD FLOAT,

    SHIFT_LOAD_PCT FLOAT,
    OPERATOR_EXPERIENCE_YEARS FLOAT,
    RECENT_30D_DOWNTIME_MIN FLOAT,
    PRIOR_30D_MAINTENANCE_COUNT NUMBER,
    MACHINE_HEALTH_SCORE FLOAT,
    PRIOR_30D_MEAN_VIBRATION_MM_S FLOAT,
    PRIOR_WORK_CENTER_TDS_AVG FLOAT,

    ACTUAL_MAINTENANCE_COST_USD FLOAT,
    ACTUAL_TDS_FACTOR FLOAT,
    ACTUAL_TOOL_REPLACEMENT_COUNT NUMBER,
    ACTUAL_DOWNTIME_MINUTES FLOAT
);

TRUNCATE TABLE TDS_SYNTHETIC_RAW_V2;

COPY INTO TDS_SYNTHETIC_RAW_V2
FROM @CORE_ML.ML_SYNTHETIC_STAGE/tds_v2_training_data.csv
FILE_FORMAT = (
    FORMAT_NAME = CORE_ML.PHASE8_CSV_FORMAT
)
ON_ERROR = 'ABORT_STATEMENT'
FORCE = TRUE;


CREATE OR REPLACE VIEW TDS_SYNTHETIC_SPLIT_V2 AS
SELECT
    r.*,

    CASE
        WHEN RUN_DATE <= TO_DATE('2024-12-31')
            THEN 'TRAIN'

        WHEN RUN_DATE <= TO_DATE('2025-06-30')
            THEN 'VALIDATION'

        WHEN RUN_DATE <= TO_DATE('2025-12-31')
            THEN 'TEST'

        ELSE 'EXCLUDED'
    END AS DATA_SPLIT,

    'SPLIT_V2' AS SPLIT_VERSION

FROM TDS_SYNTHETIC_RAW_V2 r;


MERGE INTO FEATURE_SET_REGISTRY target
USING (
    SELECT
        'TDS_FEATURES' AS FEATURE_SET_NAME,
        'V2' AS FEATURE_SET_VERSION,
        'REGRESSION' AS PREDICTION_TYPE,
        'ONE_OPERATION_RUN' AS ENTITY_GRAIN,
        'TARGET_TDS_FACTOR' AS TARGET_COLUMN_NAME,
        'CORE_ML.TDS_SYNTHETIC_SPLIT_V2'
            AS SOURCE_OBJECT_NAME,
        'DEVELOPMENT' AS STATUS,
        'Synthetic point-in-time TDS feature dataset. Post-run maintenance, tool replacement and downtime outcomes are excluded from prediction inputs.'
            AS NOTES
) source

ON target.FEATURE_SET_NAME = source.FEATURE_SET_NAME
AND target.FEATURE_SET_VERSION = source.FEATURE_SET_VERSION

WHEN MATCHED THEN UPDATE SET
    PREDICTION_TYPE = source.PREDICTION_TYPE,
    ENTITY_GRAIN = source.ENTITY_GRAIN,
    TARGET_COLUMN_NAME = source.TARGET_COLUMN_NAME,
    SOURCE_OBJECT_NAME = source.SOURCE_OBJECT_NAME,
    STATUS = source.STATUS,
    NOTES = source.NOTES

WHEN NOT MATCHED THEN INSERT (
    FEATURE_SET_NAME,
    FEATURE_SET_VERSION,
    PREDICTION_TYPE,
    ENTITY_GRAIN,
    TARGET_COLUMN_NAME,
    SOURCE_OBJECT_NAME,
    STATUS,
    NOTES
)
VALUES (
    source.FEATURE_SET_NAME,
    source.FEATURE_SET_VERSION,
    source.PREDICTION_TYPE,
    source.ENTITY_GRAIN,
    source.TARGET_COLUMN_NAME,
    source.SOURCE_OBJECT_NAME,
    source.STATUS,
    source.NOTES
);


CREATE OR REPLACE VIEW TDS_FEATURE_DATASET_V2 AS
SELECT
    OPERATION_RUN_ID AS ENTITY_ID,
    RUN_DATE AS FEATURE_AS_OF_DATE,
    TO_TIMESTAMP_NTZ(RUN_DATE) AS FEATURE_AS_OF_TIMESTAMP,

    DATA_SPLIT,
    'TDS_FEATURES' AS FEATURE_SET_NAME,
    'V2' AS FEATURE_SET_VERSION,
    'SYNTHETIC' AS SOURCE_DATA_CLASS,

    KMAT_ID,
    WORK_CENTER_ID,
    MACHINE_ID,
    OPERATION_ID,
    ENGINE,
    CAB,
    WHEEL,
    COLOR,

    MACHINE_AGE_YEARS,
    MACHINE_HOURS_RUN,
    PRE_RUN_VIBRATION_MM_S,
    PRE_RUN_TEMPERATURE_C,
    DAYS_SINCE_MAINTENANCE,
    TOOL_USAGE_CYCLES_PRE_RUN,
    SETUP_TIME_MINUTES,
    CONFIG_COMPLEXITY_SCORE,
    STANDARD_MAINTENANCE_COST_USD,

    SHIFT_LOAD_PCT,
    OPERATOR_EXPERIENCE_YEARS,
    RECENT_30D_DOWNTIME_MIN,
    PRIOR_30D_MAINTENANCE_COUNT,
    MACHINE_HEALTH_SCORE,
    PRIOR_30D_MEAN_VIBRATION_MM_S,
    PRIOR_WORK_CENTER_TDS_AVG,

    -- Development deterministic benchmark only.
    -- Do not replace the existing official TDS rule with this field.
    LEAST(
        3.5,
        GREATEST(
            1.0,

            1.0
            + IFF(ENGINE = 'V8', 0.10, 0)
            + IFF(CAB = 'PREMIUM', 0.08, 0)
            + IFF(WHEEL = 'OFFROAD', 0.12, 0)

            + IFF(PRE_RUN_VIBRATION_MM_S >= 6.5, 0.35,
                  IFF(PRE_RUN_VIBRATION_MM_S >= 4.5, 0.18, 0))

            + IFF(PRE_RUN_TEMPERATURE_C >= 82, 0.25,
                  IFF(PRE_RUN_TEMPERATURE_C >= 70, 0.12, 0))

            + IFF(DAYS_SINCE_MAINTENANCE >= 55, 0.25,
                  IFF(DAYS_SINCE_MAINTENANCE >= 35, 0.12, 0))

            + IFF(TOOL_USAGE_CYCLES_PRE_RUN >= 2200, 0.22,
                  IFF(TOOL_USAGE_CYCLES_PRE_RUN >= 1300, 0.10, 0))

            + IFF(MACHINE_HEALTH_SCORE < 55, 0.25,
                  IFF(MACHINE_HEALTH_SCORE < 70, 0.12, 0))

            + IFF(CONFIG_COMPLEXITY_SCORE >= 80, 0.18,
                  IFF(CONFIG_COMPLEXITY_SCORE >= 60, 0.08, 0))
        )
    ) AS DEVELOPMENT_RULE_BASELINE_FACTOR,

    ACTUAL_TDS_FACTOR AS TARGET_TDS_FACTOR,

    IFF(
        DATA_SPLIT IN ('TRAIN', 'VALIDATION', 'TEST')
        AND ACTUAL_TDS_FACTOR BETWEEN 1.0 AND 3.5,
        TRUE,
        FALSE
    ) AS TRAINING_ELIGIBLE_FLAG

FROM TDS_SYNTHETIC_SPLIT_V2;


-- Outcome columns deliberately excluded:
-- ACTUAL_MAINTENANCE_COST_USD
-- ACTUAL_TOOL_REPLACEMENT_COUNT
-- ACTUAL_DOWNTIME_MINUTES
CREATE OR REPLACE VIEW TDS_MODEL_DATASET_V2 AS
SELECT
    ENTITY_ID,
    FEATURE_AS_OF_DATE,
    DATA_SPLIT,

    KMAT_ID,
    WORK_CENTER_ID,
    MACHINE_ID,
    OPERATION_ID,
    ENGINE,
    CAB,
    WHEEL,
    COLOR,

    MACHINE_AGE_YEARS,
    MACHINE_HOURS_RUN,
    PRE_RUN_VIBRATION_MM_S,
    PRE_RUN_TEMPERATURE_C,
    DAYS_SINCE_MAINTENANCE,
    TOOL_USAGE_CYCLES_PRE_RUN,
    SETUP_TIME_MINUTES,
    CONFIG_COMPLEXITY_SCORE,
    STANDARD_MAINTENANCE_COST_USD,

    SHIFT_LOAD_PCT,
    OPERATOR_EXPERIENCE_YEARS,
    RECENT_30D_DOWNTIME_MIN,
    PRIOR_30D_MAINTENANCE_COUNT,
    MACHINE_HEALTH_SCORE,
    PRIOR_30D_MEAN_VIBRATION_MM_S,
    PRIOR_WORK_CENTER_TDS_AVG,

    DEVELOPMENT_RULE_BASELINE_FACTOR,
    TARGET_TDS_FACTOR

FROM TDS_FEATURE_DATASET_V2
WHERE TRAINING_ELIGIBLE_FLAG = TRUE;


-- ============================================================
-- VALIDATION GATES
-- ============================================================

-- Expected:
-- TOTAL_ROWS = 24000
-- DISTINCT_ENTITY_IDS = 24000
-- NULL_TARGETS = 0
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT ENTITY_ID) AS DISTINCT_ENTITY_IDS,
    COUNT_IF(TARGET_TDS_FACTOR IS NULL) AS NULL_TARGETS,
    MIN(FEATURE_AS_OF_DATE) AS MIN_RUN_DATE,
    MAX(FEATURE_AS_OF_DATE) AS MAX_RUN_DATE
FROM TDS_MODEL_DATASET_V2;


-- Expected zero rows.
SELECT
    ENTITY_ID,
    COUNT(*) AS DUPLICATE_COUNT
FROM TDS_MODEL_DATASET_V2
GROUP BY ENTITY_ID
HAVING COUNT(*) > 1;


-- Expected:
-- TRAIN about 18000
-- VALIDATION about 3000
-- TEST about 3000
SELECT
    DATA_SPLIT,
    COUNT(*) AS ROW_COUNT,
    MIN(FEATURE_AS_OF_DATE) AS MIN_DATE,
    MAX(FEATURE_AS_OF_DATE) AS MAX_DATE,

    MIN(TARGET_TDS_FACTOR) AS MIN_TDS_FACTOR,
    MAX(TARGET_TDS_FACTOR) AS MAX_TDS_FACTOR,
    AVG(TARGET_TDS_FACTOR) AS AVG_TDS_FACTOR,

    COUNT_IF(TARGET_TDS_FACTOR >= 2.0)
        AS HIGH_STRAIN_ROWS,

    ROUND(
        100.0
        * COUNT_IF(TARGET_TDS_FACTOR >= 2.0)
        / COUNT(*),
        3
    ) AS HIGH_STRAIN_PCT

FROM TDS_MODEL_DATASET_V2
GROUP BY DATA_SPLIT
ORDER BY
    CASE DATA_SPLIT
        WHEN 'TRAIN' THEN 1
        WHEN 'VALIDATION' THEN 2
        WHEN 'TEST' THEN 3
        ELSE 4
    END;


-- Expected all null counts = 0.
SELECT
    COUNT_IF(WORK_CENTER_ID IS NULL) AS NULL_WORK_CENTER,
    COUNT_IF(MACHINE_ID IS NULL) AS NULL_MACHINE,
    COUNT_IF(OPERATION_ID IS NULL) AS NULL_OPERATION,
    COUNT_IF(PRE_RUN_VIBRATION_MM_S IS NULL) AS NULL_VIBRATION,
    COUNT_IF(PRE_RUN_TEMPERATURE_C IS NULL) AS NULL_TEMPERATURE,
    COUNT_IF(DAYS_SINCE_MAINTENANCE IS NULL) AS NULL_MAINTENANCE_AGE,
    COUNT_IF(MACHINE_HEALTH_SCORE IS NULL) AS NULL_MACHINE_HEALTH,
    COUNT_IF(PRIOR_WORK_CENTER_TDS_AVG IS NULL) AS NULL_PRIOR_TDS
FROM TDS_MODEL_DATASET_V2;


-- Expected zero rows.
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE_ML'
  AND TABLE_NAME = 'TDS_MODEL_DATASET_V2'
  AND COLUMN_NAME IN (
      'ACTUAL_MAINTENANCE_COST_USD',
      'ACTUAL_TOOL_REPLACEMENT_COUNT',
      'ACTUAL_DOWNTIME_MINUTES'
  );


-- Review work-center coverage in all splits.
SELECT
    WORK_CENTER_ID,
    DATA_SPLIT,
    COUNT(*) AS ROW_COUNT,
    AVG(TARGET_TDS_FACTOR) AS AVG_TDS_FACTOR,
    COUNT_IF(TARGET_TDS_FACTOR >= 2.0)
        AS HIGH_STRAIN_ROWS
FROM TDS_MODEL_DATASET_V2
GROUP BY WORK_CENTER_ID, DATA_SPLIT
ORDER BY WORK_CENTER_ID, DATA_SPLIT;


-- Benchmark deterministic rule performance.
SELECT
    DATA_SPLIT,

    AVG(
        ABS(
            DEVELOPMENT_RULE_BASELINE_FACTOR
            - TARGET_TDS_FACTOR
        )
    ) AS RULE_BASELINE_MAE,

    SQRT(
        AVG(
            POWER(
                DEVELOPMENT_RULE_BASELINE_FACTOR
                - TARGET_TDS_FACTOR,
                2
            )
        )
    ) AS RULE_BASELINE_RMSE,

    AVG(
        IFF(
            DEVELOPMENT_RULE_BASELINE_FACTOR
            < TARGET_TDS_FACTOR,
            1,
            0
        )
    ) AS RULE_UNDERPREDICTION_RATE

FROM TDS_MODEL_DATASET_V2
GROUP BY DATA_SPLIT
ORDER BY
    CASE DATA_SPLIT
        WHEN 'TRAIN' THEN 1
        WHEN 'VALIDATION' THEN 2
        WHEN 'TEST' THEN 3
        ELSE 4
    END;


-- AFTER RUNNING XGBOOST
SELECT
    TABLE_NAME,
    TABLE_TYPE
FROM KMAT_COST_MODEL_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'CORE_ML'
  AND TABLE_NAME IN (
      'TDS_VALIDATION_MODEL_METRICS_V2',
      'TDS_VALIDATION_PREDICTIONS_V2',
      'TDS_SELECTED_MODEL_DECISION_V2',
      'TDS_TEST_PREDICTIONS_V2',
      'TDS_TEST_EVALUATION_V2',
      'TDS_TEST_SEGMENT_METRICS_V2'
  )
ORDER BY TABLE_NAME;

SELECT *
FROM KMAT_COST_MODEL_DB.CORE_ML.TDS_SELECTED_MODEL_DECISION_V2;

SELECT *
FROM KMAT_COST_MODEL_DB.CORE_ML.TDS_TEST_EVALUATION_V2;

SELECT *
FROM KMAT_COST_MODEL_DB.CORE_ML.TDS_TEST_SEGMENT_METRICS_V2
ORDER BY MAE DESC;