USE ROLE SYSADMIN;
USE WAREHOUSE KMAT_WH;
USE DATABASE KMAT_COST_MODEL_DB;

CREATE SCHEMA IF NOT EXISTS CORE_ML;
USE SCHEMA CORE_ML;

CREATE FILE FORMAT IF NOT EXISTS CORE_ML.PHASE8_CSV_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL', 'null')
    TRIM_SPACE = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
    DATE_FORMAT = 'YYYY-MM-DD';

CREATE STAGE IF NOT EXISTS CORE_ML.ML_SYNTHETIC_STAGE
    FILE_FORMAT = CORE_ML.PHASE8_CSV_FORMAT
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

SHOW SCHEMAS LIKE 'CORE_ML'
IN DATABASE KMAT_COST_MODEL_DB;

SHOW FILE FORMATS LIKE 'PHASE8_CSV_FORMAT'
IN SCHEMA CORE_ML;

SHOW STAGES LIKE 'ML_SYNTHETIC_STAGE'
IN SCHEMA CORE_ML;

CREATE SCHEMA IF NOT EXISTS KMAT_COST_MODEL_DB.CORE_ML;

CREATE OR REPLACE TABLE CSS_SYNTHETIC_RAW_V2 (
    PRODUCTION_BATCH_ID VARCHAR,KMAT_ID VARCHAR,PRODUCTION_DATE DATE,
    PLANT_ID VARCHAR,PRODUCTION_LINE_ID VARCHAR,ENGINE VARCHAR,CAB VARCHAR,
    WHEEL VARCHAR,COLOR VARCHAR,BATCH_QUANTITY NUMBER,COMPONENT_COUNT NUMBER,
    ROUTING_OPERATION_COUNT NUMBER,CRITICAL_COMPONENT_COUNT NUMBER,BULK_MATERIAL_PCT FLOAT,
    AVG_TEMPERATURE_C FLOAT,AVG_HUMIDITY_PCT FLOAT,AUTOMATION_LEVEL_PCT FLOAT,
    SUPPLIER_QUALITY_SCORE FLOAT,CHANGEOVER_COUNT NUMBER,OPERATOR_EXPERIENCE_YEARS FLOAT,
    LINE_UTILIZATION_PCT FLOAT,RECENT_LINE_DOWNTIME_MIN FLOAT,MACHINE_HEALTH_SCORE FLOAT,
    PRIOR_LINE_SCRAP_RATE_PCT FLOAT,PRIOR_CONFIG_SCRAP_RATE_PCT FLOAT,CONFIG_NOVELTY_SCORE FLOAT,
    PRIOR_7D_REWORK_RATE_PCT FLOAT,SUPPLIER_30D_DEFECT_RATE_PCT FLOAT,ACTUAL_SCRAP_RATE_PCT FLOAT,
    HIGH_SCRAP_FLAG NUMBER
);

LIST @CORE_ML.ML_SYNTHETIC_STAGE;

COPY INTO CSS_SYNTHETIC_RAW_V2
FROM @CORE_ML.ML_SYNTHETIC_STAGE/css_v2_training_data.csv
FILE_FORMAT = (
    FORMAT_NAME = CORE_ML.PHASE8_CSV_FORMAT
)
ON_ERROR = 'ABORT_STATEMENT'
FORCE = TRUE;

-- Step 7: Validate primary identifiers and targets
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT PRODUCTION_BATCH_ID) AS DISTINCT_BATCHES,
    COUNT_IF(PRODUCTION_BATCH_ID IS NULL) AS MISSING_IDS,
    COUNT_IF(PRODUCTION_DATE IS NULL) AS MISSING_DATES,
    COUNT_IF(HIGH_SCRAP_FLAG IS NULL) AS MISSING_TARGETS,
    COUNT_IF(HIGH_SCRAP_FLAG NOT IN (0, 1)) AS INVALID_TARGETS,
    MIN(ACTUAL_SCRAP_RATE_PCT) AS MIN_SCRAP_PCT,
    MAX(ACTUAL_SCRAP_RATE_PCT) AS MAX_SCRAP_PCT
FROM CORE_ML.CSS_SYNTHETIC_RAW_V2;

-- Step 8: Inspect target distributions
SELECT
    HIGH_SCRAP_FLAG,
    COUNT(*) AS ROW_COUNT,
    ROUND(
        100.0 * COUNT(*) / SUM(COUNT(*)) OVER (),
        3
    ) AS PERCENTAGE
FROM KMAT_COST_MODEL_DB.CORE_ML.CSS_SYNTHETIC_RAW_V2
GROUP BY HIGH_SCRAP_FLAG
ORDER BY HIGH_SCRAP_FLAG;

USE DATABASE KMAT_COST_MODEL_DB;
USE SCHEMA CORE_ML;

CREATE TABLE IF NOT EXISTS DATASET_SPLIT_CONFIG (
    DATASET_NAME VARCHAR NOT NULL,
    SPLIT_VERSION VARCHAR NOT NULL,
    DATE_COLUMN_NAME VARCHAR NOT NULL,
    TRAIN_END_DATE DATE NOT NULL,
    VALIDATION_END_DATE DATE NOT NULL,
    TEST_END_DATE DATE NOT NULL,
    SPLIT_METHOD VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    NOTES VARCHAR,
    CONSTRAINT PK_DATASET_SPLIT_CONFIG
        PRIMARY KEY (DATASET_NAME, SPLIT_VERSION)
);

MERGE INTO DATASET_SPLIT_CONFIG t
USING (
    SELECT 'CSS' DATASET_NAME, 'SPLIT_V1' SPLIT_VERSION,
           'PRODUCTION_DATE' DATE_COLUMN_NAME,
           TO_DATE('2024-12-31') TRAIN_END_DATE,
           TO_DATE('2025-06-30') VALIDATION_END_DATE,
           TO_DATE('2025-12-31') TEST_END_DATE,
           'CHRONOLOGICAL' SPLIT_METHOD,
           'ACTIVE' STATUS,
           'Synthetic development split. No random sampling.' NOTES
    UNION ALL
    SELECT 'TDS', 'SPLIT_V1', 'RUN_DATE',
           TO_DATE('2024-12-31'), TO_DATE('2025-06-30'), TO_DATE('2025-12-31'),
           'CHRONOLOGICAL', 'ACTIVE',
           'Synthetic development split. No random sampling.'
    UNION ALL
    SELECT 'BMCS', 'SPLIT_V1', 'RFQ_DATE',
           TO_DATE('2024-12-31'), TO_DATE('2025-06-30'), TO_DATE('2025-12-31'),
           'CHRONOLOGICAL', 'ACTIVE',
           'Synthetic development split. No random sampling.'
    UNION ALL
    SELECT 'FMIS', 'SPLIT_V1', 'AS_OF_DATE',
           TO_DATE('2024-10-01'), TO_DATE('2025-08-01'), TO_DATE('2026-06-01'),
           'CHRONOLOGICAL', 'ACTIVE',
           'Split by forecast as-of month, not by individual rows.'
) s
ON t.DATASET_NAME = s.DATASET_NAME
AND t.SPLIT_VERSION = s.SPLIT_VERSION
WHEN MATCHED THEN UPDATE SET
    DATE_COLUMN_NAME = s.DATE_COLUMN_NAME,
    TRAIN_END_DATE = s.TRAIN_END_DATE,
    VALIDATION_END_DATE = s.VALIDATION_END_DATE,
    TEST_END_DATE = s.TEST_END_DATE,
    SPLIT_METHOD = s.SPLIT_METHOD,
    STATUS = s.STATUS,
    NOTES = s.NOTES
WHEN NOT MATCHED THEN INSERT (
    DATASET_NAME, SPLIT_VERSION, DATE_COLUMN_NAME,
    TRAIN_END_DATE, VALIDATION_END_DATE, TEST_END_DATE,
    SPLIT_METHOD, STATUS, NOTES
) VALUES (
    s.DATASET_NAME, s.SPLIT_VERSION, s.DATE_COLUMN_NAME,
    s.TRAIN_END_DATE, s.VALIDATION_END_DATE, s.TEST_END_DATE,
    s.SPLIT_METHOD, s.STATUS, s.NOTES
);


CREATE OR REPLACE VIEW CSS_SYNTHETIC_SPLIT_V2 AS
SELECT
    r.*,
    CASE
        WHEN PRODUCTION_DATE <= TO_DATE('2024-12-31') THEN 'TRAIN'
        WHEN PRODUCTION_DATE <= TO_DATE('2025-06-30') THEN 'VALIDATION'
        WHEN PRODUCTION_DATE <= TO_DATE('2025-12-31') THEN 'TEST'
        ELSE 'EXCLUDED'
    END AS DATA_SPLIT,
    'SPLIT_V2' AS SPLIT_VERSION
FROM CSS_SYNTHETIC_RAW_V2 r;

USE DATABASE KMAT_COST_MODEL_DB;
USE SCHEMA CORE_ML;

-- ============================================================
-- PHASE 8B - CSS LEAKAGE-SAFE FEATURE DATASET V1
-- Prerequisite:
--   CORE_ML.CSS_SYNTHETIC_SPLIT_V2
-- ============================================================

CREATE TABLE IF NOT EXISTS FEATURE_SET_REGISTRY (
    FEATURE_SET_NAME          VARCHAR NOT NULL,
    FEATURE_SET_VERSION       VARCHAR NOT NULL,
    PREDICTION_TYPE           VARCHAR NOT NULL,
    ENTITY_GRAIN              VARCHAR NOT NULL,
    TARGET_COLUMN_NAME        VARCHAR,
    SOURCE_OBJECT_NAME        VARCHAR NOT NULL,
    STATUS                    VARCHAR NOT NULL,
    CREATED_AT                TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    NOTES                     VARCHAR,
    CONSTRAINT PK_FEATURE_SET_REGISTRY
        PRIMARY KEY (FEATURE_SET_NAME, FEATURE_SET_VERSION)
);

MERGE INTO FEATURE_SET_REGISTRY t
USING (
    SELECT
        'CSS_FEATURES' AS FEATURE_SET_NAME,
        'V2' AS FEATURE_SET_VERSION,
        'BINARY_CLASSIFICATION' AS PREDICTION_TYPE,
        'ONE_PRODUCTION_BATCH' AS ENTITY_GRAIN,
        'TARGET_HIGH_SCRAP_FLAG' AS TARGET_COLUMN_NAME,
        'CORE_ML.CSS_SYNTHETIC_SPLIT_V2' AS SOURCE_OBJECT_NAME,
        'DEVELOPMENT' AS STATUS,
        'Stronger synthetic CSS data with point-in-time production-history features.'
            AS NOTES
) s
ON t.FEATURE_SET_NAME = s.FEATURE_SET_NAME
AND t.FEATURE_SET_VERSION = s.FEATURE_SET_VERSION
WHEN MATCHED THEN UPDATE SET
    PREDICTION_TYPE = s.PREDICTION_TYPE,
    ENTITY_GRAIN = s.ENTITY_GRAIN,
    TARGET_COLUMN_NAME = s.TARGET_COLUMN_NAME,
    SOURCE_OBJECT_NAME = s.SOURCE_OBJECT_NAME,
    STATUS = s.STATUS,
    NOTES = s.NOTES
WHEN NOT MATCHED THEN INSERT (
    FEATURE_SET_NAME, FEATURE_SET_VERSION, PREDICTION_TYPE,
    ENTITY_GRAIN, TARGET_COLUMN_NAME, SOURCE_OBJECT_NAME,
    STATUS, NOTES
) VALUES (
    s.FEATURE_SET_NAME, s.FEATURE_SET_VERSION, s.PREDICTION_TYPE,
    s.ENTITY_GRAIN, s.TARGET_COLUMN_NAME, s.SOURCE_OBJECT_NAME,
    s.STATUS, s.NOTES
);

CREATE TABLE IF NOT EXISTS FEATURE_PREPROCESSING_STATS (
    FEATURE_SET_NAME      VARCHAR NOT NULL,
    FEATURE_SET_VERSION   VARCHAR NOT NULL,
    FEATURE_NAME          VARCHAR NOT NULL,
    STATISTIC_NAME        VARCHAR NOT NULL,
    STATISTIC_VALUE       FLOAT,
    CALCULATED_FROM_SPLIT VARCHAR NOT NULL,
    SOURCE_ROW_COUNT      NUMBER,
    CALCULATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_FEATURE_PREPROCESSING_STATS
        PRIMARY KEY (
            FEATURE_SET_NAME,
            FEATURE_SET_VERSION,
            FEATURE_NAME,
            STATISTIC_NAME
        )
);

DELETE FROM FEATURE_PREPROCESSING_STATS
WHERE FEATURE_SET_NAME = 'CSS_FEATURES'
  AND FEATURE_SET_VERSION = 'V2';

INSERT INTO FEATURE_PREPROCESSING_STATS (
    FEATURE_SET_NAME,
    FEATURE_SET_VERSION,
    FEATURE_NAME,
    STATISTIC_NAME,
    STATISTIC_VALUE,
    CALCULATED_FROM_SPLIT,
    SOURCE_ROW_COUNT
)
SELECT
    'CSS_FEATURES',
    'V1',
    'AVG_TEMPERATURE_C',
    'MEDIAN',
    MEDIAN(AVG_TEMPERATURE_C),
    'TRAIN',
    COUNT(AVG_TEMPERATURE_C)
FROM CSS_SYNTHETIC_SPLIT_V2
WHERE DATA_SPLIT = 'TRAIN'

UNION ALL

SELECT
    'CSS_FEATURES',
    'V1',
    'AVG_HUMIDITY_PCT',
    'MEDIAN',
    MEDIAN(AVG_HUMIDITY_PCT),
    'TRAIN',
    COUNT(AVG_HUMIDITY_PCT)
FROM CSS_SYNTHETIC_SPLIT_V2
WHERE DATA_SPLIT = 'TRAIN';

CREATE OR REPLACE VIEW CSS_FEATURE_DATASET_V2 AS
SELECT
    PRODUCTION_BATCH_ID AS ENTITY_ID,
    PRODUCTION_DATE AS FEATURE_AS_OF_DATE,
    TO_TIMESTAMP_NTZ(PRODUCTION_DATE) AS FEATURE_AS_OF_TIMESTAMP,
    DATA_SPLIT,
    'CSS_FEATURES' AS FEATURE_SET_NAME,
    'V2' AS FEATURE_SET_VERSION,
    'SYNTHETIC' AS SOURCE_DATA_CLASS,

    PLANT_ID,
    PRODUCTION_LINE_ID,
    ENGINE,
    CAB,
    WHEEL,
    COLOR,

    BATCH_QUANTITY,
    COMPONENT_COUNT,
    ROUTING_OPERATION_COUNT,
    CRITICAL_COMPONENT_COUNT,
    BULK_MATERIAL_PCT,
    AVG_TEMPERATURE_C,
    AVG_HUMIDITY_PCT,
    AUTOMATION_LEVEL_PCT,
    SUPPLIER_QUALITY_SCORE,
    CHANGEOVER_COUNT,
    OPERATOR_EXPERIENCE_YEARS,

    LINE_UTILIZATION_PCT,
    RECENT_LINE_DOWNTIME_MIN,
    MACHINE_HEALTH_SCORE,
    PRIOR_LINE_SCRAP_RATE_PCT,
    PRIOR_CONFIG_SCRAP_RATE_PCT,
    CONFIG_NOVELTY_SCORE,
    PRIOR_7D_REWORK_RATE_PCT,
    SUPPLIER_30D_DEFECT_RATE_PCT,

    MONTH(PRODUCTION_DATE) AS PRODUCTION_MONTH,
    QUARTER(PRODUCTION_DATE) AS PRODUCTION_QUARTER,
    DAYOFWEEKISO(PRODUCTION_DATE) AS PRODUCTION_DAY_OF_WEEK,

    HIGH_SCRAP_FLAG AS TARGET_HIGH_SCRAP_FLAG,
    IFF(DATA_SPLIT IN ('TRAIN', 'VALIDATION', 'TEST'), TRUE, FALSE)
        AS TRAINING_ELIGIBLE_FLAG
FROM CSS_SYNTHETIC_SPLIT_V2;

-- Explicit model-ready view.
-- Leakage columns are deliberately excluded:
-- ACTUAL_SCRAP_RATE_PCT
-- ACTUAL_DEFECT_COUNT
-- ACTUAL_REWORK_COUNT
CREATE OR REPLACE VIEW CSS_MODEL_DATASET_V2 AS
SELECT
    ENTITY_ID,
    DATA_SPLIT,

    PLANT_ID,
    PRODUCTION_LINE_ID,
    ENGINE,
    CAB,
    WHEEL,
    COLOR,

    BATCH_QUANTITY,
    COMPONENT_COUNT,
    ROUTING_OPERATION_COUNT,
    CRITICAL_COMPONENT_COUNT,
    BULK_MATERIAL_PCT,
    AVG_TEMPERATURE_C,
    AVG_HUMIDITY_PCT,
    AUTOMATION_LEVEL_PCT,
    SUPPLIER_QUALITY_SCORE,
    CHANGEOVER_COUNT,
    OPERATOR_EXPERIENCE_YEARS,

    LINE_UTILIZATION_PCT,
    RECENT_LINE_DOWNTIME_MIN,
    MACHINE_HEALTH_SCORE,
    PRIOR_LINE_SCRAP_RATE_PCT,
    PRIOR_CONFIG_SCRAP_RATE_PCT,
    CONFIG_NOVELTY_SCORE,
    PRIOR_7D_REWORK_RATE_PCT,
    SUPPLIER_30D_DEFECT_RATE_PCT,

    PRODUCTION_MONTH,
    PRODUCTION_QUARTER,
    PRODUCTION_DAY_OF_WEEK,

    TARGET_HIGH_SCRAP_FLAG
FROM CSS_FEATURE_DATASET_V2
WHERE TRAINING_ELIGIBLE_FLAG = TRUE;

-- ============================================================
-- VALIDATION GATES
-- ============================================================

-- 1. Row counts and class balance.
SELECT
    DATA_SPLIT,
    COUNT(*) AS ROW_COUNT,
    COUNT_IF(TARGET_HIGH_SCRAP_FLAG = 1) AS HIGH_SCRAP_ROWS,
    ROUND(100.0 * AVG(TARGET_HIGH_SCRAP_FLAG), 3)
        AS HIGH_SCRAP_PCT
FROM CSS_MODEL_DATASET_V2
GROUP BY DATA_SPLIT
ORDER BY
    CASE DATA_SPLIT
        WHEN 'TRAIN' THEN 1
        WHEN 'VALIDATION' THEN 2
        WHEN 'TEST' THEN 3
        ELSE 4
    END;

-- 2. No null values after preprocessing.
SELECT
    COUNT_IF(AVG_TEMPERATURE_C IS NULL) AS NULL_TEMPERATURE,
    COUNT_IF(AVG_HUMIDITY_PCT IS NULL) AS NULL_HUMIDITY,
    COUNT_IF(TARGET_HIGH_SCRAP_FLAG IS NULL) AS NULL_TARGET,
    COUNT_IF(ENTITY_ID IS NULL) AS NULL_ENTITY_ID
FROM CSS_MODEL_DATASET_V2;

-- 3. Training-derived preprocessing values.
SELECT *
FROM FEATURE_PREPROCESSING_STATS
WHERE FEATURE_SET_NAME = 'CSS_FEATURES'
  AND FEATURE_SET_VERSION = 'V1'
ORDER BY FEATURE_NAME;

-- 4. Unique entity check.
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT ENTITY_ID) AS DISTINCT_ENTITY_IDS,
    COUNT(*) - COUNT(DISTINCT ENTITY_ID) AS DUPLICATE_ENTITY_ROWS
FROM CSS_MODEL_DATASET_V2;

-- 5. Feature range review.
SELECT
    MIN(BATCH_QUANTITY) AS MIN_BATCH_QUANTITY,
    MAX(BATCH_QUANTITY) AS MAX_BATCH_QUANTITY,
    MIN(COMPONENT_COUNT) AS MIN_COMPONENT_COUNT,
    MAX(COMPONENT_COUNT) AS MAX_COMPONENT_COUNT,
    MIN(AVG_TEMPERATURE_C) AS MIN_TEMPERATURE_C,
    MAX(AVG_TEMPERATURE_C) AS MAX_TEMPERATURE_C,
    MIN(AVG_HUMIDITY_PCT) AS MIN_HUMIDITY_PCT,
    MAX(AVG_HUMIDITY_PCT) AS MAX_HUMIDITY_PCT,
    MIN(AUTOMATION_LEVEL_PCT) AS MIN_AUTOMATION_PCT,
    MAX(AUTOMATION_LEVEL_PCT) AS MAX_AUTOMATION_PCT,
    MIN(SUPPLIER_QUALITY_SCORE) AS MIN_SUPPLIER_QUALITY,
    MAX(SUPPLIER_QUALITY_SCORE) AS MAX_SUPPLIER_QUALITY
FROM CSS_MODEL_DATASET_V2;

-- 6. Confirm that prohibited outcome columns do not exist
--    in the model-ready view. Expected result: zero rows.
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'CORE_ML'
  AND TABLE_NAME = 'CSS_MODEL_DATASET_V2'
  AND COLUMN_NAME IN (
      'ACTUAL_SCRAP_RATE_PCT',
      'ACTUAL_DEFECT_COUNT',
      'ACTUAL_REWORK_COUNT'
  );


USE DATABASE KMAT_COST_MODEL_DB;
USE SCHEMA CORE_ML;

-- ============================================================
-- PHASE 8C - CSS CLASSIFIER V2
-- Purpose:
--   Train a synthetic-data CSS classifier and evaluate it using
--   chronological TRAIN / VALIDATION / TEST partitions.
--
-- Deployment authority:
--   SHADOW ONLY. This model must not affect official cost.
--
-- Prerequisite:
--   CORE_ML.CSS_MODEL_DATASET_V2
-- ============================================================


-- ============================================================
-- 1. CREATE LEAKAGE-SAFE TRAINING AND SCORING VIEWS
-- ============================================================

-- The training view contains only prediction-time features and the target.
-- ENTITY_ID and DATA_SPLIT are not included because Snowflake treats every
-- non-target column in INPUT_DATA as a model feature.

CREATE OR REPLACE VIEW CSS_TRAIN_INPUT_V2 AS
SELECT * EXCLUDE (ENTITY_ID, DATA_SPLIT)
FROM CSS_MODEL_DATASET_V2
WHERE DATA_SPLIT = 'TRAIN';

CREATE OR REPLACE VIEW CSS_VALIDATION_INPUT_V2 AS
SELECT *
FROM CSS_MODEL_DATASET_V2
WHERE DATA_SPLIT = 'VALIDATION';

CREATE OR REPLACE VIEW CSS_TEST_INPUT_V2 AS
SELECT *
FROM CSS_MODEL_DATASET_V2
WHERE DATA_SPLIT = 'TEST';
-- ============================================================
-- 2. PRE-TRAINING GATES
-- ============================================================

-- Gate A: training data must contain both target classes.
SELECT
    TARGET_HIGH_SCRAP_FLAG,
    COUNT(*) AS ROW_COUNT
FROM CSS_TRAIN_INPUT_V2
GROUP BY TARGET_HIGH_SCRAP_FLAG
ORDER BY TARGET_HIGH_SCRAP_FLAG;


-- Gate B: no null targets.
SELECT
    COUNT(*) AS TRAIN_ROWS,
    COUNT_IF(TARGET_HIGH_SCRAP_FLAG IS NULL) AS NULL_TARGET_ROWS,
    COUNT(DISTINCT TARGET_HIGH_SCRAP_FLAG) AS TARGET_CLASS_COUNT
FROM CSS_TRAIN_INPUT_V2;


-- Gate C: chronological datasets must not overlap.
SELECT
    (SELECT COUNT(*) FROM CSS_TRAIN_INPUT_V2) AS TRAIN_ROWS,
    (SELECT COUNT(*) FROM CSS_VALIDATION_INPUT_V2) AS VALIDATION_ROWS,
    (SELECT COUNT(*) FROM CSS_TEST_INPUT_V2) AS TEST_ROWS;


-- ============================================================
-- 3. TRAIN THE CLASSIFIER
-- ============================================================

-- Built-in evaluation is disabled because it uses an internal holdout.
-- This project uses the already-governed chronological validation/test sets.
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION CSS_CLASSIFIER_V2 (
    INPUT_DATA => SYSTEM$REFERENCE(
        'VIEW',
        'KMAT_COST_MODEL_DB.CORE_ML.CSS_TRAIN_INPUT_V2'
    ),
    TARGET_COLNAME => 'TARGET_HIGH_SCRAP_FLAG',
    CONFIG_OBJECT => {
        'evaluate': FALSE,
        'on_error': 'ABORT'
    }
)
COMMENT = 'Stronger synthetic CSS classifier V2. SHADOW ONLY.';



-- Confirm model creation.
SHOW SNOWFLAKE.ML.CLASSIFICATION
LIKE 'CSS_CLASSIFIER_V2'
IN SCHEMA KMAT_COST_MODEL_DB.CORE_ML;


-- ============================================================
-- 4. SCORE THE CHRONOLOGICAL VALIDATION SET
-- ============================================================

CREATE OR REPLACE TABLE CSS_VALIDATION_PREDICTIONS_V2 AS
WITH scored AS (
    SELECT
        ENTITY_ID,
        TARGET_HIGH_SCRAP_FLAG,
        CSS_CLASSIFIER_V2!PREDICT(
            INPUT_DATA => OBJECT_CONSTRUCT_KEEP_NULL(
                * EXCLUDE (
                    ENTITY_ID,
                    DATA_SPLIT,
                    TARGET_HIGH_SCRAP_FLAG
                )
            ),
            CONFIG_OBJECT => {'on_error': 'ABORT'}
        ) AS PREDICTION
    FROM CSS_VALIDATION_INPUT_V2
)
SELECT
    ENTITY_ID,
    TARGET_HIGH_SCRAP_FLAG,
    GET(PREDICTION, 'class')::VARCHAR
        AS MODEL_DEFAULT_PREDICTED_CLASS,
    GET(GET(PREDICTION, 'probability'), '1')::FLOAT
        AS CSS_HIGH_SCRAP_PROBABILITY,
    ROUND(
        100 * GET(GET(PREDICTION, 'probability'), '1')::FLOAT,
        4
    ) AS CSS_SCORE,
    PREDICTION AS RAW_PREDICTION,
    CURRENT_TIMESTAMP() AS PREDICTED_AT
FROM scored;


-- Prediction parsing gate.
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(CSS_HIGH_SCRAP_PROBABILITY IS NULL) AS NULL_PROBABILITY_ROWS,
    MIN(CSS_HIGH_SCRAP_PROBABILITY) AS MIN_PROBABILITY,
    MAX(CSS_HIGH_SCRAP_PROBABILITY) AS MAX_PROBABILITY
FROM CSS_VALIDATION_PREDICTIONS_V2;


-- ============================================================
-- 5. CALCULATE VALIDATION METRICS ACROSS THRESHOLDS
-- ============================================================

CREATE OR REPLACE TABLE CSS_VALIDATION_PREDICTIONS_V2 AS
WITH scored AS (
    SELECT
        ENTITY_ID,
        TARGET_HIGH_SCRAP_FLAG,
        CSS_CLASSIFIER_V2!PREDICT(
            INPUT_DATA => OBJECT_CONSTRUCT_KEEP_NULL(
                * EXCLUDE (
                    ENTITY_ID,
                    DATA_SPLIT,
                    TARGET_HIGH_SCRAP_FLAG
                )
            ),
            CONFIG_OBJECT => {'on_error': 'ABORT'}
        ) AS PREDICTION
    FROM CSS_VALIDATION_INPUT_V2
)
SELECT
    ENTITY_ID,
    TARGET_HIGH_SCRAP_FLAG,
    GET(PREDICTION, 'class')::VARCHAR
        AS MODEL_DEFAULT_PREDICTED_CLASS,
    GET(GET(PREDICTION, 'probability'), '1')::FLOAT
        AS CSS_HIGH_SCRAP_PROBABILITY,
    ROUND(
        100 * GET(GET(PREDICTION, 'probability'), '1')::FLOAT,
        4
    ) AS CSS_SCORE,
    PREDICTION AS RAW_PREDICTION,
    CURRENT_TIMESTAMP() AS PREDICTED_AT
FROM scored;

CREATE OR REPLACE TABLE CSS_VALIDATION_THRESHOLD_METRICS_V2 AS
WITH thresholds AS (
    SELECT ROUND(0.05 + SEQ4() * 0.01, 2) AS THRESHOLD
    FROM TABLE(GENERATOR(ROWCOUNT => 91))
),
counts AS (
    SELECT
        t.THRESHOLD,
        COUNT_IF(
            p.TARGET_HIGH_SCRAP_FLAG = 1
            AND p.CSS_HIGH_SCRAP_PROBABILITY >= t.THRESHOLD
        ) AS TP,
        COUNT_IF(
            p.TARGET_HIGH_SCRAP_FLAG = 0
            AND p.CSS_HIGH_SCRAP_PROBABILITY >= t.THRESHOLD
        ) AS FP,
        COUNT_IF(
            p.TARGET_HIGH_SCRAP_FLAG = 0
            AND p.CSS_HIGH_SCRAP_PROBABILITY < t.THRESHOLD
        ) AS TN,
        COUNT_IF(
            p.TARGET_HIGH_SCRAP_FLAG = 1
            AND p.CSS_HIGH_SCRAP_PROBABILITY < t.THRESHOLD
        ) AS FN
    FROM thresholds t
    CROSS JOIN CSS_VALIDATION_PREDICTIONS_V2 p
    GROUP BY t.THRESHOLD
),
metrics AS (
    SELECT
        THRESHOLD, TP, FP, TN, FN,
        TP::FLOAT / NULLIF(TP + FP, 0) AS PRECISION,
        TP::FLOAT / NULLIF(TP + FN, 0) AS RECALL,
        TN::FLOAT / NULLIF(TN + FP, 0) AS SPECIFICITY,
        FP::FLOAT / NULLIF(FP + TN, 0) AS FALSE_POSITIVE_RATE,
        FN::FLOAT / NULLIF(TP + FN, 0) AS FALSE_NEGATIVE_RATE
    FROM counts
)
SELECT
    *,
    2 * PRECISION * RECALL
        / NULLIF(PRECISION + RECALL, 0) AS F1_SCORE,
    5 * PRECISION * RECALL
        / NULLIF(4 * PRECISION + RECALL, 0) AS F2_SCORE,
    (RECALL + SPECIFICITY) / 2 AS BALANCED_ACCURACY
FROM metrics;


-- ============================================================
-- 6. SELECT A CANDIDATE SHADOW THRESHOLD
-- ============================================================

-- This threshold is selected only for synthetic shadow evaluation.
-- It is not an approved business decision threshold.
CREATE OR REPLACE TABLE CSS_SELECTED_THRESHOLD_V2 AS
SELECT
    'CSS_CLASSIFIER_V2' AS MODEL_NAME,
    'V2' AS MODEL_VERSION,
    THRESHOLD AS CANDIDATE_THRESHOLD,
    PRECISION,
    RECALL,
    SPECIFICITY,
    FALSE_POSITIVE_RATE,
    FALSE_NEGATIVE_RATE,
    F1_SCORE,
    F2_SCORE,
    BALANCED_ACCURACY,
    IFF(
        RECALL >= 0.70 AND SPECIFICITY >= 0.60,
        'CONSTRAINED_THRESHOLD_SELECTED',
        'FALLBACK_NO_THRESHOLD_MET_CONSTRAINTS'
    ) AS SELECTION_STATUS,
    'RECALL >= 0.70 AND SPECIFICITY >= 0.60; maximize F2'
        AS SELECTION_POLICY,
    'SHADOW' AS DEPLOYMENT_MODE,
    CURRENT_TIMESTAMP() AS SELECTED_AT
FROM CSS_VALIDATION_THRESHOLD_METRICS_V2
QUALIFY ROW_NUMBER() OVER (
    ORDER BY
        IFF(RECALL >= 0.70 AND SPECIFICITY >= 0.60, 1, 0) DESC,
        F2_SCORE DESC NULLS LAST,
        BALANCED_ACCURACY DESC NULLS LAST,
        PRECISION DESC NULLS LAST
) = 1;


SELECT *
FROM CSS_SELECTED_THRESHOLD_V2;


-- ============================================================
-- 7. SCORE THE UNTOUCHED TEST SET
-- ============================================================

CREATE OR REPLACE TABLE CSS_TEST_PREDICTIONS_V2 AS
WITH scored AS (
    SELECT
        ENTITY_ID,
        TARGET_HIGH_SCRAP_FLAG,
        CSS_CLASSIFIER_V2!PREDICT(
            INPUT_DATA => OBJECT_CONSTRUCT_KEEP_NULL(
                * EXCLUDE (
                    ENTITY_ID,
                    DATA_SPLIT,
                    TARGET_HIGH_SCRAP_FLAG
                )
            ),
            CONFIG_OBJECT => {'on_error': 'ABORT'}
        ) AS PREDICTION
    FROM CSS_TEST_INPUT_V2
)
SELECT
    ENTITY_ID,
    TARGET_HIGH_SCRAP_FLAG,
    GET(PREDICTION, 'class')::VARCHAR
        AS MODEL_DEFAULT_PREDICTED_CLASS,
    GET(GET(PREDICTION, 'probability'), '1')::FLOAT
        AS CSS_HIGH_SCRAP_PROBABILITY,
    ROUND(
        100 * GET(GET(PREDICTION, 'probability'), '1')::FLOAT,
        4
    ) AS CSS_SCORE,
    PREDICTION AS RAW_PREDICTION,
    CURRENT_TIMESTAMP() AS PREDICTED_AT
FROM scored;


-- ============================================================
-- 8. FINAL TEST METRICS AT THE LOCKED VALIDATION THRESHOLD
-- ============================================================

CREATE OR REPLACE TABLE CSS_TEST_EVALUATION_V2 AS
WITH classified AS (
    SELECT
        p.*,
        t.CANDIDATE_THRESHOLD,
        IFF(
            p.CSS_HIGH_SCRAP_PROBABILITY >= t.CANDIDATE_THRESHOLD,
            1,
            0
        ) AS PREDICTED_HIGH_SCRAP_FLAG
    FROM CSS_TEST_PREDICTIONS_V2 p
    CROSS JOIN CSS_SELECTED_THRESHOLD_V2 t
),
counts AS (
    SELECT
        MAX(CANDIDATE_THRESHOLD) AS CANDIDATE_THRESHOLD,
        COUNT_IF(
            TARGET_HIGH_SCRAP_FLAG = 1
            AND PREDICTED_HIGH_SCRAP_FLAG = 1
        ) AS TP,
        COUNT_IF(
            TARGET_HIGH_SCRAP_FLAG = 0
            AND PREDICTED_HIGH_SCRAP_FLAG = 1
        ) AS FP,
        COUNT_IF(
            TARGET_HIGH_SCRAP_FLAG = 0
            AND PREDICTED_HIGH_SCRAP_FLAG = 0
        ) AS TN,
        COUNT_IF(
            TARGET_HIGH_SCRAP_FLAG = 1
            AND PREDICTED_HIGH_SCRAP_FLAG = 0
        ) AS FN
    FROM classified
),
metrics AS (
    SELECT
        CANDIDATE_THRESHOLD, TP, FP, TN, FN,
        TP::FLOAT / NULLIF(TP + FP, 0) AS PRECISION,
        TP::FLOAT / NULLIF(TP + FN, 0) AS RECALL,
        TN::FLOAT / NULLIF(TN + FP, 0) AS SPECIFICITY,
        FP::FLOAT / NULLIF(FP + TN, 0) AS FALSE_POSITIVE_RATE,
        FN::FLOAT / NULLIF(TP + FN, 0) AS FALSE_NEGATIVE_RATE,
        (TP + TN)::FLOAT / NULLIF(TP + FP + TN + FN, 0)
            AS ACCURACY
    FROM counts
)
SELECT
    'CSS_CLASSIFIER_V2' AS MODEL_NAME,
    'V2' AS MODEL_VERSION,
    'TEST' AS DATA_SPLIT,
    CANDIDATE_THRESHOLD,
    TP AS TRUE_POSITIVES,
    FP AS FALSE_POSITIVES,
    TN AS TRUE_NEGATIVES,
    FN AS FALSE_NEGATIVES,
    PRECISION,
    RECALL,
    SPECIFICITY,
    FALSE_POSITIVE_RATE,
    FALSE_NEGATIVE_RATE,
    ACCURACY,
    2 * PRECISION * RECALL
        / NULLIF(PRECISION + RECALL, 0) AS F1_SCORE,
    5 * PRECISION * RECALL
        / NULLIF(4 * PRECISION + RECALL, 0) AS F2_SCORE,
    (RECALL + SPECIFICITY) / 2 AS BALANCED_ACCURACY,
    'SHADOW' AS DEPLOYMENT_MODE,
    FALSE AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM metrics;


SELECT *
FROM CSS_TEST_EVALUATION_V2;

-- ============================================================
-- 9. CREATE SHADOW OUTPUT VIEW
-- ============================================================

CREATE OR REPLACE VIEW CSS_TEST_SHADOW_OUTPUT_V2 AS
SELECT
    p.ENTITY_ID,

    p.CSS_HIGH_SCRAP_PROBABILITY,
    p.CSS_SCORE,

    t.CANDIDATE_THRESHOLD,
    t.SELECTION_STATUS,
    t.SELECTION_POLICY,

    IFF(
        p.CSS_HIGH_SCRAP_PROBABILITY >= t.CANDIDATE_THRESHOLD,
        1,
        0
    ) AS PREDICTED_HIGH_SCRAP_FLAG,

    p.TARGET_HIGH_SCRAP_FLAG AS ACTUAL_HIGH_SCRAP_FLAG,

    CASE
        WHEN p.TARGET_HIGH_SCRAP_FLAG = 1
         AND p.CSS_HIGH_SCRAP_PROBABILITY >= t.CANDIDATE_THRESHOLD
            THEN 'TRUE_POSITIVE'

        WHEN p.TARGET_HIGH_SCRAP_FLAG = 0
         AND p.CSS_HIGH_SCRAP_PROBABILITY >= t.CANDIDATE_THRESHOLD
            THEN 'FALSE_POSITIVE'

        WHEN p.TARGET_HIGH_SCRAP_FLAG = 0
         AND p.CSS_HIGH_SCRAP_PROBABILITY < t.CANDIDATE_THRESHOLD
            THEN 'TRUE_NEGATIVE'

        WHEN p.TARGET_HIGH_SCRAP_FLAG = 1
         AND p.CSS_HIGH_SCRAP_PROBABILITY < t.CANDIDATE_THRESHOLD
            THEN 'FALSE_NEGATIVE'

        ELSE 'UNKNOWN'
    END AS OUTCOME_TYPE,

    'CSS_CLASSIFIER_V2' AS MODEL_NAME,
    'V2' AS MODEL_VERSION,
    'CSS_FEATURES_V2' AS FEATURE_SET_VERSION,
    'TEST' AS DATA_SPLIT,

    'SHADOW' AS DEPLOYMENT_MODE,
    FALSE AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    FALSE AS BUSINESS_DECISION_ALLOWED_FLAG,

    CASE
        WHEN t.SELECTION_STATUS = 'CONSTRAINED_THRESHOLD_SELECTED'
            THEN 'SHADOW_EVALUATION_READY'
        ELSE 'THRESHOLD_NOT_ACCEPTABLE'
    END AS SHADOW_STATUS,

    p.PREDICTED_AT

FROM CSS_TEST_PREDICTIONS_V2 p
CROSS JOIN CSS_SELECTED_THRESHOLD_V2 t;

-- ============================================================
-- 10. FINAL ACCEPTANCE CHECKS
-- ============================================================

-- Expected:
--   TOTAL_ROWS = DISTINCT_ENTITY_IDS
--   NULL_PROBABILITIES = 0
--   OUT_OF_RANGE_PROBABILITIES = 0
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT ENTITY_ID) AS DISTINCT_ENTITY_IDS,
    COUNT(*) - COUNT(DISTINCT ENTITY_ID) AS DUPLICATE_ROWS,
    COUNT_IF(CSS_HIGH_SCRAP_PROBABILITY IS NULL)
        AS NULL_PROBABILITIES
FROM CSS_TEST_SHADOW_OUTPUT_V2;


-- Review the distribution of shadow outcomes.
SELECT
    OUTCOME_TYPE,
    COUNT(*) AS ROW_COUNT,
    ROUND(
        100.0 * COUNT(*) / SUM(COUNT(*)) OVER (),
        2
    ) AS PERCENTAGE
FROM CSS_TEST_SHADOW_OUTPUT_V2
GROUP BY OUTCOME_TYPE
ORDER BY OUTCOME_TYPE;

SELECT
    DEPLOYMENT_MODE,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG,
    SHADOW_STATUS,
    COUNT(*) AS ROW_COUNT
FROM CSS_TEST_SHADOW_OUTPUT_V2
GROUP BY
    DEPLOYMENT_MODE,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG,
    SHADOW_STATUS;
-- Feature importance is diagnostic only.
CALL CSS_CLASSIFIER_V2!SHOW_FEATURE_IMPORTANCE();


-- Training logs are useful for audit and troubleshooting.
CALL CSS_CLASSIFIER_V2!SHOW_TRAINING_LOGS();


CALL CSS_CLASSIFIER_V2!SHOW_FEATURE_IMPORTANCE();

SELECT *
FROM CSS_SELECTED_THRESHOLD_V2;

SELECT *
FROM CSS_TEST_EVALUATION_V2;

CREATE TABLE IF NOT EXISTS MODEL_VALIDATION_DECISIONS (
    MODEL_NAME                  VARCHAR NOT NULL,
    MODEL_VERSION               VARCHAR NOT NULL,
    VALIDATION_STATUS           VARCHAR NOT NULL,
    DEPLOYMENT_MODE             VARCHAR NOT NULL,
    OFFICIAL_COST_ALLOWED_FLAG  BOOLEAN NOT NULL,
    BUSINESS_DECISION_ALLOWED_FLAG BOOLEAN NOT NULL,
    DECISION_REASON             VARCHAR,
    TEST_PRECISION              FLOAT,
    TEST_RECALL                 FLOAT,
    TEST_SPECIFICITY            FLOAT,
    TEST_FALSE_POSITIVE_RATE    FLOAT,
    TEST_FALSE_NEGATIVE_RATE    FLOAT,
    TEST_BALANCED_ACCURACY      FLOAT,
    DECIDED_AT                  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (MODEL_NAME, MODEL_VERSION)
);

MERGE INTO MODEL_VALIDATION_DECISIONS target
USING (
    SELECT
        MODEL_NAME,
        MODEL_VERSION,
        'ACCEPTED_FOR_SHADOW' AS VALIDATION_STATUS,
        'SHADOW' AS DEPLOYMENT_MODE,
        FALSE AS OFFICIAL_COST_ALLOWED_FLAG,
        FALSE AS BUSINESS_DECISION_ALLOWED_FLAG,
        'CSS V2 achieved strong recall and balanced accuracy, but uses synthetic data and remains shadow-only.'
            AS DECISION_REASON,
        PRECISION AS TEST_PRECISION,
        RECALL AS TEST_RECALL,
        SPECIFICITY AS TEST_SPECIFICITY,
        FALSE_POSITIVE_RATE AS TEST_FALSE_POSITIVE_RATE,
        FALSE_NEGATIVE_RATE AS TEST_FALSE_NEGATIVE_RATE,
        BALANCED_ACCURACY AS TEST_BALANCED_ACCURACY
    FROM CSS_TEST_EVALUATION_V2
) source
ON target.MODEL_NAME = source.MODEL_NAME
AND target.MODEL_VERSION = source.MODEL_VERSION

WHEN MATCHED THEN UPDATE SET
    VALIDATION_STATUS = source.VALIDATION_STATUS,
    DEPLOYMENT_MODE = source.DEPLOYMENT_MODE,
    OFFICIAL_COST_ALLOWED_FLAG =
        source.OFFICIAL_COST_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG =
        source.BUSINESS_DECISION_ALLOWED_FLAG,
    DECISION_REASON = source.DECISION_REASON,
    TEST_PRECISION = source.TEST_PRECISION,
    TEST_RECALL = source.TEST_RECALL,
    TEST_SPECIFICITY = source.TEST_SPECIFICITY,
    TEST_FALSE_POSITIVE_RATE =
        source.TEST_FALSE_POSITIVE_RATE,
    TEST_FALSE_NEGATIVE_RATE =
        source.TEST_FALSE_NEGATIVE_RATE,
    TEST_BALANCED_ACCURACY =
        source.TEST_BALANCED_ACCURACY,
    DECIDED_AT = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT (
    MODEL_NAME,
    MODEL_VERSION,
    VALIDATION_STATUS,
    DEPLOYMENT_MODE,
    OFFICIAL_COST_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG,
    DECISION_REASON,
    TEST_PRECISION,
    TEST_RECALL,
    TEST_SPECIFICITY,
    TEST_FALSE_POSITIVE_RATE,
    TEST_FALSE_NEGATIVE_RATE,
    TEST_BALANCED_ACCURACY
)
VALUES (
    source.MODEL_NAME,
    source.MODEL_VERSION,
    source.VALIDATION_STATUS,
    source.DEPLOYMENT_MODE,
    source.OFFICIAL_COST_ALLOWED_FLAG,
    source.BUSINESS_DECISION_ALLOWED_FLAG,
    source.DECISION_REASON,
    source.TEST_PRECISION,
    source.TEST_RECALL,
    source.TEST_SPECIFICITY,
    source.TEST_FALSE_POSITIVE_RATE,
    source.TEST_FALSE_NEGATIVE_RATE,
    source.TEST_BALANCED_ACCURACY
);


-- ============================================================
-- PHASE 8B - FMIS V2 INGESTION AND LEAKAGE-SAFE FEATURE DATASET
-- Upload fmis_v2_monthly_series.csv to:
-- @CORE_ML.ML_SYNTHETIC_STAGE/fmis_v2_monthly_series.csv
-- ============================================================

CREATE OR REPLACE TABLE FMIS_SYNTHETIC_RAW_V2 (
    OBSERVATION_ID VARCHAR,
    SERIES_KEY VARCHAR,
    COMMODITY_GROUP VARCHAR,
    SUPPLIER_REGION VARCHAR,
    SUPPLIER_ID VARCHAR,
    INDEX_MONTH DATE,
    FEATURE_AS_OF_DATE DATE,
    APPROVED_ENERGY_FORECAST_INDEX FLOAT,
    APPROVED_FREIGHT_FORECAST_INDEX FLOAT,
    APPROVED_FX_FORECAST_INDEX FLOAT,
    APPROVED_MARKET_PMI FLOAT,
    APPROVED_PORT_CONGESTION_INDEX FLOAT,
    SUPPLIER_LEAD_TIME_DAYS FLOAT,
    SUPPLIER_RELIABILITY_SCORE FLOAT,
    CONTRACT_ESCALATION_PCT FLOAT,
    REALIZED_MATERIAL_INDEX FLOAT
);
COPY INTO FMIS_SYNTHETIC_RAW_V2
FROM @CORE_ML.ML_SYNTHETIC_STAGE/fmis_v2_monthly_series.csv
FILE_FORMAT = (
    FORMAT_NAME = CORE_ML.PHASE8_CSV_FORMAT
)
ON_ERROR = 'ABORT_STATEMENT'
FORCE = TRUE;
CREATE OR REPLACE VIEW FMIS_SYNTHETIC_SPLIT_V2 AS
SELECT
    r.*,
    CASE
        WHEN INDEX_MONTH <= TO_DATE('2023-12-01')
            THEN 'TRAIN'
        WHEN INDEX_MONTH <= TO_DATE('2024-12-01')
            THEN 'VALIDATION'
        WHEN INDEX_MONTH <= TO_DATE('2025-12-01')
            THEN 'TEST'
        ELSE 'EXCLUDED'
    END AS DATA_SPLIT,
    'SPLIT_V2' AS SPLIT_VERSION
FROM FMIS_SYNTHETIC_RAW_V2 r;

MERGE INTO FEATURE_SET_REGISTRY t
USING (
    SELECT
        'FMIS_FEATURES' AS FEATURE_SET_NAME,
        'V2' AS FEATURE_SET_VERSION,
        'MULTI_SERIES_FORECASTING'
            AS PREDICTION_TYPE,
        'ONE_COMMODITY_REGION_SUPPLIER_MONTH'
            AS ENTITY_GRAIN,
        'REALIZED_MATERIAL_INDEX'
            AS TARGET_COLUMN_NAME,
        'CORE_ML.FMIS_SYNTHETIC_SPLIT_V2'
            AS SOURCE_OBJECT_NAME,
        'DEVELOPMENT' AS STATUS,
        'Monthly multi-series FMIS forecast dataset with prediction-time approved exogenous inputs.'
            AS NOTES
) s
ON t.FEATURE_SET_NAME = s.FEATURE_SET_NAME
AND t.FEATURE_SET_VERSION = s.FEATURE_SET_VERSION
WHEN MATCHED THEN UPDATE SET
    PREDICTION_TYPE = s.PREDICTION_TYPE,
    ENTITY_GRAIN = s.ENTITY_GRAIN,
    TARGET_COLUMN_NAME = s.TARGET_COLUMN_NAME,
    SOURCE_OBJECT_NAME = s.SOURCE_OBJECT_NAME,
    STATUS = s.STATUS,
    NOTES = s.NOTES
WHEN NOT MATCHED THEN INSERT (
    FEATURE_SET_NAME,
    FEATURE_SET_VERSION,
    PREDICTION_TYPE,
    ENTITY_GRAIN,
    TARGET_COLUMN_NAME,
    SOURCE_OBJECT_NAME,
    STATUS,
    NOTES
) VALUES (
    s.FEATURE_SET_NAME,
    s.FEATURE_SET_VERSION,
    s.PREDICTION_TYPE,
    s.ENTITY_GRAIN,
    s.TARGET_COLUMN_NAME,
    s.SOURCE_OBJECT_NAME,
    s.STATUS,
    s.NOTES
);

CREATE OR REPLACE VIEW FMIS_FEATURE_DATASET_V2 AS
SELECT
    OBSERVATION_ID AS ENTITY_ID,
    TO_VARIANT(
        ARRAY_CONSTRUCT(
            COMMODITY_GROUP,
            SUPPLIER_REGION,
            SUPPLIER_ID
        )
    ) AS SERIES_ID,
    SERIES_KEY,
    COMMODITY_GROUP,
    SUPPLIER_REGION,
    SUPPLIER_ID,

    TO_TIMESTAMP_NTZ(INDEX_MONTH) AS INDEX_TIMESTAMP,
    INDEX_MONTH,
    FEATURE_AS_OF_DATE,

    APPROVED_ENERGY_FORECAST_INDEX,
    APPROVED_FREIGHT_FORECAST_INDEX,
    APPROVED_FX_FORECAST_INDEX,
    APPROVED_MARKET_PMI,
    APPROVED_PORT_CONGESTION_INDEX,
    SUPPLIER_LEAD_TIME_DAYS,
    SUPPLIER_RELIABILITY_SCORE,
    CONTRACT_ESCALATION_PCT,

    REALIZED_MATERIAL_INDEX,

    DATA_SPLIT,
    'FMIS_FEATURES' AS FEATURE_SET_NAME,
    'V2' AS FEATURE_SET_VERSION,
    'SYNTHETIC' AS SOURCE_DATA_CLASS,

    IFF(
        FEATURE_AS_OF_DATE < INDEX_MONTH
        AND DATA_SPLIT IN (
            'TRAIN',
            'VALIDATION',
            'TEST'
        ),
        TRUE,
        FALSE
    ) AS TRAINING_ELIGIBLE_FLAG
FROM FMIS_SYNTHETIC_SPLIT_V2;

CREATE OR REPLACE VIEW FMIS_MODEL_DATASET_V2 AS
SELECT
    ENTITY_ID,
    SERIES_ID,
    SERIES_KEY,
    INDEX_TIMESTAMP,
    INDEX_MONTH,
    DATA_SPLIT,

    APPROVED_ENERGY_FORECAST_INDEX,
    APPROVED_FREIGHT_FORECAST_INDEX,
    APPROVED_FX_FORECAST_INDEX,
    APPROVED_MARKET_PMI,
    APPROVED_PORT_CONGESTION_INDEX,
    SUPPLIER_LEAD_TIME_DAYS,
    SUPPLIER_RELIABILITY_SCORE,
    CONTRACT_ESCALATION_PCT,

    REALIZED_MATERIAL_INDEX
FROM FMIS_FEATURE_DATASET_V2
WHERE TRAINING_ELIGIBLE_FLAG = TRUE;

-- 1. Expected:
--    2,880 rows, 30 series, 2018-01 through 2025-12.
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT SERIES_KEY) AS SERIES_COUNT,
    MIN(INDEX_MONTH) AS MIN_INDEX_MONTH,
    MAX(INDEX_MONTH) AS MAX_INDEX_MONTH,
    COUNT_IF(
        REALIZED_MATERIAL_INDEX IS NULL
    ) AS NULL_TARGETS
FROM FMIS_MODEL_DATASET_V2;

-- 2. Expected zero rows.
--    Every series must contain exactly 96 months.
SELECT
    SERIES_KEY,
    COUNT(*) AS MONTH_COUNT,
    MIN(INDEX_MONTH) AS MIN_MONTH,
    MAX(INDEX_MONTH) AS MAX_MONTH
FROM FMIS_MODEL_DATASET_V2
GROUP BY SERIES_KEY
HAVING COUNT(*) <> 96
ORDER BY SERIES_KEY;

-- 3. Expected zero rows.
SELECT
    SERIES_KEY,
    INDEX_MONTH,
    COUNT(*) AS DUPLICATE_COUNT
FROM FMIS_MODEL_DATASET_V2
GROUP BY SERIES_KEY, INDEX_MONTH
HAVING COUNT(*) > 1;

-- 4. Expected INVALID_AS_OF_ROWS = 0.
SELECT
    COUNT_IF(
        FEATURE_AS_OF_DATE >= INDEX_MONTH
    ) AS INVALID_AS_OF_ROWS
FROM FMIS_FEATURE_DATASET_V2;

-- 5. Expected:
--    TRAIN 2,160
--    VALIDATION 360
--    TEST 360
SELECT
    DATA_SPLIT,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT SERIES_KEY) AS SERIES_COUNT,
    MIN(INDEX_MONTH) AS MIN_MONTH,
    MAX(INDEX_MONTH) AS MAX_MONTH
FROM FMIS_MODEL_DATASET_V2
GROUP BY DATA_SPLIT
ORDER BY
    CASE DATA_SPLIT
        WHEN 'TRAIN' THEN 1
        WHEN 'VALIDATION' THEN 2
        WHEN 'TEST' THEN 3
        ELSE 4
    END;

-- 6. Expected zero rows.
WITH ordered AS (
    SELECT
        SERIES_KEY,
        INDEX_MONTH,
        LAG(INDEX_MONTH) OVER (
            PARTITION BY SERIES_KEY
            ORDER BY INDEX_MONTH
        ) AS PREVIOUS_MONTH
    FROM FMIS_MODEL_DATASET_V2
)
SELECT
    SERIES_KEY,
    PREVIOUS_MONTH,
    INDEX_MONTH,
    DATEDIFF(
        'month',
        PREVIOUS_MONTH,
        INDEX_MONTH
    ) AS MONTH_GAP
FROM ordered
WHERE PREVIOUS_MONTH IS NOT NULL
  AND DATEDIFF(
      'month',
      PREVIOUS_MONTH,
      INDEX_MONTH
  ) <> 1;

-- 7. All null counts should be zero.
SELECT
    MIN(REALIZED_MATERIAL_INDEX)
        AS MIN_TARGET_INDEX,
    MAX(REALIZED_MATERIAL_INDEX)
        AS MAX_TARGET_INDEX,
    COUNT_IF(
        APPROVED_ENERGY_FORECAST_INDEX IS NULL
    ) AS NULL_ENERGY,
    COUNT_IF(
        APPROVED_FREIGHT_FORECAST_INDEX IS NULL
    ) AS NULL_FREIGHT,
    COUNT_IF(
        APPROVED_FX_FORECAST_INDEX IS NULL
    ) AS NULL_FX,
    COUNT_IF(
        APPROVED_MARKET_PMI IS NULL
    ) AS NULL_PMI,
    COUNT_IF(
        APPROVED_PORT_CONGESTION_INDEX IS NULL
    ) AS NULL_CONGESTION,
    COUNT_IF(
        SUPPLIER_LEAD_TIME_DAYS IS NULL
    ) AS NULL_LEAD_TIME,
    COUNT_IF(
        SUPPLIER_RELIABILITY_SCORE IS NULL
    ) AS NULL_RELIABILITY,
    COUNT_IF(
        CONTRACT_ESCALATION_PCT IS NULL
    ) AS NULL_ESCALATION
FROM FMIS_MODEL_DATASET_V2;

-- ============================================================
-- PHASE 8C - FMIS FORECASTING V2
-- Development model: TRAIN only, validate on 2024.
-- Final shadow model: TRAIN + VALIDATION, test on 2025.
-- Synthetic data only. No official cost impact.
-- Prerequisite: FMIS_MODEL_DATASET_V2
-- ============================================================

CREATE OR REPLACE VIEW FMIS_TRAIN_INPUT_V2 AS
SELECT
    SERIES_ID,
    INDEX_TIMESTAMP,
    APPROVED_ENERGY_FORECAST_INDEX,
    APPROVED_FREIGHT_FORECAST_INDEX,
    APPROVED_FX_FORECAST_INDEX,
    APPROVED_MARKET_PMI,
    APPROVED_PORT_CONGESTION_INDEX,
    SUPPLIER_LEAD_TIME_DAYS,
    SUPPLIER_RELIABILITY_SCORE,
    CONTRACT_ESCALATION_PCT,
    REALIZED_MATERIAL_INDEX
FROM FMIS_MODEL_DATASET_V2
WHERE DATA_SPLIT = 'TRAIN';

CREATE OR REPLACE VIEW FMIS_VALIDATION_FUTURE_INPUT_V2 AS
SELECT
    SERIES_ID,
    INDEX_TIMESTAMP,
    APPROVED_ENERGY_FORECAST_INDEX,
    APPROVED_FREIGHT_FORECAST_INDEX,
    APPROVED_FX_FORECAST_INDEX,
    APPROVED_MARKET_PMI,
    APPROVED_PORT_CONGESTION_INDEX,
    SUPPLIER_LEAD_TIME_DAYS,
    SUPPLIER_RELIABILITY_SCORE,
    CONTRACT_ESCALATION_PCT
FROM FMIS_MODEL_DATASET_V2
WHERE DATA_SPLIT = 'VALIDATION';

CREATE OR REPLACE VIEW FMIS_TRAIN_VALIDATION_INPUT_V2 AS
SELECT
    SERIES_ID,
    INDEX_TIMESTAMP,
    APPROVED_ENERGY_FORECAST_INDEX,
    APPROVED_FREIGHT_FORECAST_INDEX,
    APPROVED_FX_FORECAST_INDEX,
    APPROVED_MARKET_PMI,
    APPROVED_PORT_CONGESTION_INDEX,
    SUPPLIER_LEAD_TIME_DAYS,
    SUPPLIER_RELIABILITY_SCORE,
    CONTRACT_ESCALATION_PCT,
    REALIZED_MATERIAL_INDEX
FROM FMIS_MODEL_DATASET_V2
WHERE DATA_SPLIT IN ('TRAIN', 'VALIDATION');

CREATE OR REPLACE VIEW FMIS_TEST_FUTURE_INPUT_V2 AS
SELECT
    SERIES_ID,
    INDEX_TIMESTAMP,
    APPROVED_ENERGY_FORECAST_INDEX,
    APPROVED_FREIGHT_FORECAST_INDEX,
    APPROVED_FX_FORECAST_INDEX,
    APPROVED_MARKET_PMI,
    APPROVED_PORT_CONGESTION_INDEX,
    SUPPLIER_LEAD_TIME_DAYS,
    SUPPLIER_RELIABILITY_SCORE,
    CONTRACT_ESCALATION_PCT
FROM FMIS_MODEL_DATASET_V2
WHERE DATA_SPLIT = 'TEST';

ALTER WAREHOUSE KMAT_WH SET WAREHOUSE_SIZE = 'MEDIUM';

CREATE OR REPLACE SNOWFLAKE.ML.FORECAST FMIS_FORECAST_DEV_V2 (
    INPUT_DATA => SYSTEM$REFERENCE(
        'VIEW',
        'KMAT_COST_MODEL_DB.CORE_ML.FMIS_TRAIN_INPUT_V2'
    ),
    SERIES_COLNAME => 'SERIES_ID',
    TIMESTAMP_COLNAME => 'INDEX_TIMESTAMP',
    TARGET_COLNAME => 'REALIZED_MATERIAL_INDEX',
    CONFIG_OBJECT => {
        'method': 'best',
        'evaluate': TRUE,
        'evaluation_config': {
            'n_splits': 3,
            'test_size': 6,
            'gap': 0
        },
        'on_error': 'ABORT'
    }
)
COMMENT = 'FMIS V2 development forecast trained on synthetic TRAIN data. SHADOW ONLY.';


CREATE OR REPLACE TABLE FMIS_DEV_CV_METRICS_V2 AS
SELECT *
FROM TABLE(FMIS_FORECAST_DEV_V2!SHOW_EVALUATION_METRICS());

CREATE OR REPLACE TABLE FMIS_VALIDATION_FORECASTS_V2 AS
SELECT
    SERIES,
    TS AS INDEX_TIMESTAMP,
    FORECAST AS FORECAST_MATERIAL_INDEX,
    LOWER_BOUND,
    UPPER_BOUND,
    'FMIS_FORECAST_DEV_V2' AS MODEL_NAME,
    'V2' AS MODEL_VERSION,
    'VALIDATION' AS DATA_SPLIT,
    'SHADOW' AS DEPLOYMENT_MODE,
    CURRENT_TIMESTAMP() AS FORECASTED_AT
FROM TABLE(
    FMIS_FORECAST_DEV_V2!FORECAST(
        INPUT_DATA => SYSTEM$REFERENCE(
            'VIEW',
            'KMAT_COST_MODEL_DB.CORE_ML.FMIS_VALIDATION_FUTURE_INPUT_V2'
        ),
        SERIES_COLNAME => 'SERIES_ID',
        TIMESTAMP_COLNAME => 'INDEX_TIMESTAMP',
        CONFIG_OBJECT => {
            'prediction_interval': 0.95,
            'on_error': 'ABORT'
        }
    )
);

CREATE OR REPLACE VIEW FMIS_VALIDATION_COMPARISON_V2 AS
WITH last_train AS (
    SELECT
        SERIES_ID,
        REALIZED_MATERIAL_INDEX AS LAST_TRAIN_INDEX
    FROM FMIS_MODEL_DATASET_V2
    WHERE DATA_SPLIT = 'TRAIN'
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY TO_JSON(SERIES_ID)
        ORDER BY INDEX_TIMESTAMP DESC
    ) = 1
)
SELECT
    a.SERIES_ID,
    a.SERIES_KEY,
    a.INDEX_TIMESTAMP,
    a.REALIZED_MATERIAL_INDEX AS ACTUAL_MATERIAL_INDEX,
    f.FORECAST_MATERIAL_INDEX,
    f.LOWER_BOUND,
    f.UPPER_BOUND,
    l.LAST_TRAIN_INDEX AS NAIVE_FORECAST_INDEX,
    ABS(f.FORECAST_MATERIAL_INDEX - a.REALIZED_MATERIAL_INDEX)
        AS ML_ABSOLUTE_ERROR,
    ABS(l.LAST_TRAIN_INDEX - a.REALIZED_MATERIAL_INDEX)
        AS NAIVE_ABSOLUTE_ERROR,
    IFF(
        a.REALIZED_MATERIAL_INDEX BETWEEN f.LOWER_BOUND AND f.UPPER_BOUND,
        1,
        0
    ) AS INTERVAL_COVERED_FLAG
FROM FMIS_MODEL_DATASET_V2 a
JOIN FMIS_VALIDATION_FORECASTS_V2 f
  ON TO_JSON(a.SERIES_ID) = TO_JSON(f.SERIES)
 AND a.INDEX_TIMESTAMP = f.INDEX_TIMESTAMP
JOIN last_train l
  ON TO_JSON(a.SERIES_ID) = TO_JSON(l.SERIES_ID)
WHERE a.DATA_SPLIT = 'VALIDATION';

CREATE OR REPLACE TABLE FMIS_VALIDATION_EVALUATION_V2 AS
SELECT
    'FMIS_FORECAST_DEV_V2' AS MODEL_NAME,
    'V2' AS MODEL_VERSION,
    'VALIDATION' AS DATA_SPLIT,
    COUNT(*) AS OBSERVATION_COUNT,
    AVG(ML_ABSOLUTE_ERROR) AS ML_MAE,
    AVG(NAIVE_ABSOLUTE_ERROR) AS NAIVE_MAE,
    SUM(ML_ABSOLUTE_ERROR)
        / NULLIF(SUM(ABS(ACTUAL_MATERIAL_INDEX)), 0)
        AS ML_WAPE,
    SUM(NAIVE_ABSOLUTE_ERROR)
        / NULLIF(SUM(ABS(ACTUAL_MATERIAL_INDEX)), 0)
        AS NAIVE_WAPE,
    AVG(
        ABS(FORECAST_MATERIAL_INDEX - ACTUAL_MATERIAL_INDEX)
        / NULLIF(ABS(ACTUAL_MATERIAL_INDEX), 0)
    ) AS ML_MAPE,
    AVG(INTERVAL_COVERED_FLAG) AS PREDICTION_INTERVAL_COVERAGE,
    1 - (
        AVG(ML_ABSOLUTE_ERROR)
        / NULLIF(AVG(NAIVE_ABSOLUTE_ERROR), 0)
    ) AS MAE_IMPROVEMENT_VS_NAIVE,
    'SHADOW' AS DEPLOYMENT_MODE,
    FALSE AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM FMIS_VALIDATION_COMPARISON_V2;

SELECT * FROM FMIS_VALIDATION_EVALUATION_V2;

CREATE OR REPLACE SNOWFLAKE.ML.FORECAST FMIS_FORECAST_V2 (
    INPUT_DATA => SYSTEM$REFERENCE(
        'VIEW',
        'KMAT_COST_MODEL_DB.CORE_ML.FMIS_TRAIN_VALIDATION_INPUT_V2'
    ),
    SERIES_COLNAME => 'SERIES_ID',
    TIMESTAMP_COLNAME => 'INDEX_TIMESTAMP',
    TARGET_COLNAME => 'REALIZED_MATERIAL_INDEX',
    CONFIG_OBJECT => {
        'method': 'best',
        'evaluate': TRUE,
        'evaluation_config': {
            'n_splits': 3,
            'test_size': 6,
            'gap': 0
        },
        'on_error': 'ABORT'
    }
)
COMMENT = 'FMIS V2 final synthetic forecast trained on TRAIN+VALIDATION. SHADOW ONLY.';

CREATE OR REPLACE TABLE FMIS_FINAL_CV_METRICS_V2 AS
SELECT *
FROM TABLE(FMIS_FORECAST_V2!SHOW_EVALUATION_METRICS());

CREATE OR REPLACE TABLE FMIS_TEST_FORECASTS_V2 AS
SELECT
    SERIES,
    TS AS INDEX_TIMESTAMP,
    FORECAST AS FORECAST_MATERIAL_INDEX,
    LOWER_BOUND,
    UPPER_BOUND,
    'FMIS_FORECAST_V2' AS MODEL_NAME,
    'V2' AS MODEL_VERSION,
    'TEST' AS DATA_SPLIT,
    'SHADOW' AS DEPLOYMENT_MODE,
    FALSE AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    CURRENT_TIMESTAMP() AS FORECASTED_AT
FROM TABLE(
    FMIS_FORECAST_V2!FORECAST(
        INPUT_DATA => SYSTEM$REFERENCE(
            'VIEW',
            'KMAT_COST_MODEL_DB.CORE_ML.FMIS_TEST_FUTURE_INPUT_V2'
        ),
        SERIES_COLNAME => 'SERIES_ID',
        TIMESTAMP_COLNAME => 'INDEX_TIMESTAMP',
        CONFIG_OBJECT => {
            'prediction_interval': 0.95,
            'on_error': 'ABORT'
        }
    )
);

CREATE OR REPLACE VIEW FMIS_TEST_SHADOW_OUTPUT_V2 AS
WITH last_available AS (
    SELECT
        SERIES_ID,
        REALIZED_MATERIAL_INDEX AS CURRENT_APPROVED_INDEX
    FROM FMIS_MODEL_DATASET_V2
    WHERE DATA_SPLIT IN ('TRAIN', 'VALIDATION')
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY TO_JSON(SERIES_ID)
        ORDER BY INDEX_TIMESTAMP DESC
    ) = 1
)
SELECT
    a.ENTITY_ID,
    a.SERIES_ID,
    a.SERIES_KEY,
    a.INDEX_TIMESTAMP,
    l.CURRENT_APPROVED_INDEX,
    f.FORECAST_MATERIAL_INDEX,
    f.LOWER_BOUND,
    f.UPPER_BOUND,
    f.FORECAST_MATERIAL_INDEX
        / NULLIF(l.CURRENT_APPROVED_INDEX, 0)
        AS FMIS_MULTIPLIER,
    f.LOWER_BOUND
        / NULLIF(l.CURRENT_APPROVED_INDEX, 0)
        AS FMIS_MULTIPLIER_LOWER_BOUND,
    f.UPPER_BOUND
        / NULLIF(l.CURRENT_APPROVED_INDEX, 0)
        AS FMIS_MULTIPLIER_UPPER_BOUND,
    a.REALIZED_MATERIAL_INDEX AS ACTUAL_MATERIAL_INDEX,
    ABS(f.FORECAST_MATERIAL_INDEX - a.REALIZED_MATERIAL_INDEX)
        AS ML_ABSOLUTE_ERROR,
    ABS(l.CURRENT_APPROVED_INDEX - a.REALIZED_MATERIAL_INDEX)
        AS NAIVE_ABSOLUTE_ERROR,
    IFF(
        a.REALIZED_MATERIAL_INDEX BETWEEN f.LOWER_BOUND AND f.UPPER_BOUND,
        1,
        0
    ) AS INTERVAL_COVERED_FLAG,
    'FMIS_FORECAST_V2' AS MODEL_NAME,
    'V2' AS MODEL_VERSION,
    'FMIS_FEATURES_V2' AS FEATURE_SET_VERSION,
    'TEST' AS DATA_SPLIT,
    'SHADOW' AS DEPLOYMENT_MODE,
    FALSE AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    FALSE AS BUSINESS_DECISION_ALLOWED_FLAG,
    CURRENT_TIMESTAMP() AS CREATED_AT
FROM FMIS_MODEL_DATASET_V2 a
JOIN FMIS_TEST_FORECASTS_V2 f
  ON TO_JSON(a.SERIES_ID) = TO_JSON(f.SERIES)
 AND a.INDEX_TIMESTAMP = f.INDEX_TIMESTAMP
JOIN last_available l
  ON TO_JSON(a.SERIES_ID) = TO_JSON(l.SERIES_ID)
WHERE a.DATA_SPLIT = 'TEST';

CREATE OR REPLACE TABLE FMIS_TEST_EVALUATION_V2 AS
SELECT
    'FMIS_FORECAST_V2' AS MODEL_NAME,
    'V2' AS MODEL_VERSION,
    'TEST' AS DATA_SPLIT,
    COUNT(*) AS OBSERVATION_COUNT,
    AVG(ML_ABSOLUTE_ERROR) AS ML_MAE,
    AVG(NAIVE_ABSOLUTE_ERROR) AS NAIVE_MAE,
    SUM(ML_ABSOLUTE_ERROR)
        / NULLIF(SUM(ABS(ACTUAL_MATERIAL_INDEX)), 0)
        AS ML_WAPE,
    SUM(NAIVE_ABSOLUTE_ERROR)
        / NULLIF(SUM(ABS(ACTUAL_MATERIAL_INDEX)), 0)
        AS NAIVE_WAPE,
    AVG(
        ML_ABSOLUTE_ERROR
        / NULLIF(ABS(ACTUAL_MATERIAL_INDEX), 0)
    ) AS ML_MAPE,
    AVG(INTERVAL_COVERED_FLAG)
        AS PREDICTION_INTERVAL_COVERAGE,
    1 - (
        AVG(ML_ABSOLUTE_ERROR)
        / NULLIF(AVG(NAIVE_ABSOLUTE_ERROR), 0)
    ) AS MAE_IMPROVEMENT_VS_NAIVE,
    COUNT_IF(FMIS_MULTIPLIER <= 0)
        AS INVALID_MULTIPLIER_ROWS,
    MIN(FMIS_MULTIPLIER) AS MIN_FMIS_MULTIPLIER,
    MAX(FMIS_MULTIPLIER) AS MAX_FMIS_MULTIPLIER,
    'SHADOW' AS DEPLOYMENT_MODE,
    FALSE AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    CURRENT_TIMESTAMP() AS EVALUATED_AT
FROM FMIS_TEST_SHADOW_OUTPUT_V2;

SELECT * FROM FMIS_TEST_EVALUATION_V2;

CREATE OR REPLACE VIEW FMIS_TEST_SERIES_METRICS_V2 AS
SELECT
    SERIES_KEY,
    COUNT(*) AS OBSERVATION_COUNT,
    AVG(ML_ABSOLUTE_ERROR) AS ML_MAE,
    AVG(NAIVE_ABSOLUTE_ERROR) AS NAIVE_MAE,
    SUM(ML_ABSOLUTE_ERROR)
        / NULLIF(SUM(ABS(ACTUAL_MATERIAL_INDEX)), 0)
        AS ML_WAPE,
    AVG(INTERVAL_COVERED_FLAG)
        AS PREDICTION_INTERVAL_COVERAGE
FROM FMIS_TEST_SHADOW_OUTPUT_V2
GROUP BY SERIES_KEY;

CREATE OR REPLACE VIEW FMIS_V2_SHADOW_DECISION AS
SELECT
    MODEL_NAME,
    MODEL_VERSION,
    CASE
        WHEN ML_MAE < NAIVE_MAE
         AND ML_WAPE < NAIVE_WAPE
         AND PREDICTION_INTERVAL_COVERAGE >= 0.80
         AND INVALID_MULTIPLIER_ROWS = 0
            THEN 'ACCEPTED_FOR_SHADOW'
        ELSE 'REQUIRES_MODEL_CORRECTION'
    END AS VALIDATION_STATUS,
    CASE
        WHEN ML_MAE < NAIVE_MAE
         AND ML_WAPE < NAIVE_WAPE
            THEN 'ML_OUTPERFORMS_NAIVE_BASELINE'
        ELSE 'ML_DOES_NOT_OUTPERFORM_NAIVE_BASELINE'
    END AS BASELINE_COMPARISON_STATUS,
    ML_MAE,
    NAIVE_MAE,
    ML_WAPE,
    NAIVE_WAPE,
    ML_MAPE,
    PREDICTION_INTERVAL_COVERAGE,
    MAE_IMPROVEMENT_VS_NAIVE,
    'SHADOW' AS DEPLOYMENT_MODE,
    FALSE AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    FALSE AS BUSINESS_DECISION_ALLOWED_FLAG
FROM FMIS_TEST_EVALUATION_V2;

SELECT * FROM FMIS_V2_SHADOW_DECISION;

CALL FMIS_FORECAST_V2!EXPLAIN_FEATURE_IMPORTANCE();
CALL FMIS_FORECAST_V2!SHOW_TRAINING_LOGS();

SELECT
    COUNT(*) AS TOTAL_TEST_ROWS,
    COUNT(DISTINCT ENTITY_ID) AS DISTINCT_ENTITY_IDS,
    COUNT_IF(FORECAST_MATERIAL_INDEX IS NULL)
        AS NULL_FORECAST_ROWS,
    COUNT_IF(FMIS_MULTIPLIER IS NULL)
        AS NULL_MULTIPLIER_ROWS,
    COUNT_IF(FMIS_MULTIPLIER <= 0)
        AS NON_POSITIVE_MULTIPLIER_ROWS
FROM FMIS_TEST_SHADOW_OUTPUT_V2;

SELECT * FROM FMIS_VALIDATION_EVALUATION_V2;

SELECT * FROM FMIS_TEST_EVALUATION_V2;

SELECT * FROM FMIS_V2_SHADOW_DECISION;

SELECT * FROM FMIS_TEST_SERIES_METRICS_V2
ORDER BY ML_WAPE DESC;

CALL FMIS_FORECAST_V2!EXPLAIN_FEATURE_IMPORTANCE();

SELECT
    TABLE_NAME,
    TABLE_TYPE
FROM KMAT_COST_MODEL_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'CORE_ML'
  AND TABLE_NAME IN (
      'FMIS_VALIDATION_COMPARISON_V2',
      'FMIS_TEST_SHADOW_OUTPUT_V2',
      'FMIS_TEST_EVALUATION_V2'
  )
ORDER BY TABLE_NAME;

CREATE OR REPLACE TABLE
    KMAT_COST_MODEL_DB.CORE_ML.FMIS_SERIES_SHADOW_POLICY_V2
AS
SELECT
    SERIES_KEY,
    COUNT(*) AS OBSERVATION_COUNT,

    AVG(ML_ABSOLUTE_ERROR) AS ML_MAE,
    AVG(NAIVE_ABSOLUTE_ERROR) AS NAIVE_MAE,

    SUM(ML_ABSOLUTE_ERROR)
        / NULLIF(SUM(ABS(ACTUAL_MATERIAL_INDEX)), 0)
        AS ML_WAPE,

    SUM(NAIVE_ABSOLUTE_ERROR)
        / NULLIF(SUM(ABS(ACTUAL_MATERIAL_INDEX)), 0)
        AS NAIVE_WAPE,

    AVG(INTERVAL_COVERED_FLAG)
        AS PREDICTION_INTERVAL_COVERAGE,

    1 - (
        AVG(ML_ABSOLUTE_ERROR)
        / NULLIF(AVG(NAIVE_ABSOLUTE_ERROR), 0)
    ) AS MAE_IMPROVEMENT_VS_NAIVE,

    CASE
        WHEN AVG(ML_ABSOLUTE_ERROR)
             < AVG(NAIVE_ABSOLUTE_ERROR)
         AND
             SUM(ML_ABSOLUTE_ERROR)
             / NULLIF(SUM(ABS(ACTUAL_MATERIAL_INDEX)), 0)
             <
             SUM(NAIVE_ABSOLUTE_ERROR)
             / NULLIF(SUM(ABS(ACTUAL_MATERIAL_INDEX)), 0)
            THEN 'ML_FORECAST'

        ELSE 'NAIVE_FALLBACK'
    END AS SELECTED_FORECAST_METHOD,

    IFF(
        AVG(INTERVAL_COVERED_FLAG) >= 0.80,
        'INTERVAL_COVERAGE_ACCEPTABLE',
        'INTERVAL_COVERAGE_REVIEW'
    ) AS INTERVAL_MONITORING_STATUS,

    'VALIDATION_2024' AS POLICY_SELECTION_DATASET,
    'V2' AS POLICY_VERSION,
    'LOCKED_FOR_SYNTHETIC_TEST' AS POLICY_STATUS,
    CURRENT_TIMESTAMP() AS POLICY_LOCKED_AT

FROM KMAT_COST_MODEL_DB.CORE_ML.FMIS_VALIDATION_COMPARISON_V2
GROUP BY SERIES_KEY;

CREATE OR REPLACE VIEW
    KMAT_COST_MODEL_DB.CORE_ML.FMIS_HYBRID_TEST_SHADOW_OUTPUT_V2
AS
SELECT
    t.ENTITY_ID,
    t.SERIES_ID,
    t.SERIES_KEY,
    t.INDEX_TIMESTAMP,

    p.SELECTED_FORECAST_METHOD,
    p.INTERVAL_MONITORING_STATUS,
    p.POLICY_VERSION,

    t.CURRENT_APPROVED_INDEX,

    t.FORECAST_MATERIAL_INDEX
        AS RAW_ML_FORECAST_INDEX,

    t.LOWER_BOUND
        AS RAW_ML_LOWER_BOUND,

    t.UPPER_BOUND
        AS RAW_ML_UPPER_BOUND,

    CASE
        WHEN p.SELECTED_FORECAST_METHOD = 'ML_FORECAST'
            THEN t.FORECAST_MATERIAL_INDEX
        ELSE t.CURRENT_APPROVED_INDEX
    END AS SELECTED_FORECAST_INDEX,

    CASE
        WHEN p.SELECTED_FORECAST_METHOD = 'ML_FORECAST'
            THEN t.FORECAST_MATERIAL_INDEX
                 / NULLIF(t.CURRENT_APPROVED_INDEX, 0)
        ELSE 1.0
    END AS SELECTED_FMIS_MULTIPLIER,

    t.ACTUAL_MATERIAL_INDEX,

    ABS(
        CASE
            WHEN p.SELECTED_FORECAST_METHOD = 'ML_FORECAST'
                THEN t.FORECAST_MATERIAL_INDEX
            ELSE t.CURRENT_APPROVED_INDEX
        END
        - t.ACTUAL_MATERIAL_INDEX
    ) AS SELECTED_ABSOLUTE_ERROR,

    t.ML_ABSOLUTE_ERROR,
    t.NAIVE_ABSOLUTE_ERROR,

    'FMIS_FORECAST_V2' AS MODEL_NAME,
    'V2' AS MODEL_VERSION,
    'TEST' AS DATA_SPLIT,
    'SHADOW' AS DEPLOYMENT_MODE,

    FALSE AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    FALSE AS BUSINESS_DECISION_ALLOWED_FLAG,

    CURRENT_TIMESTAMP() AS CREATED_AT

FROM KMAT_COST_MODEL_DB.CORE_ML.FMIS_TEST_SHADOW_OUTPUT_V2 t
JOIN KMAT_COST_MODEL_DB.CORE_ML.FMIS_SERIES_SHADOW_POLICY_V2 p
  ON t.SERIES_KEY = p.SERIES_KEY;

CREATE OR REPLACE VIEW
    KMAT_COST_MODEL_DB.CORE_ML.FMIS_HYBRID_TEST_SHADOW_OUTPUT_V2
AS
SELECT
    t.ENTITY_ID,
    t.SERIES_ID,
    t.SERIES_KEY,
    t.INDEX_TIMESTAMP,

    p.SELECTED_FORECAST_METHOD,
    p.INTERVAL_MONITORING_STATUS,
    p.POLICY_VERSION,

    t.CURRENT_APPROVED_INDEX,

    t.FORECAST_MATERIAL_INDEX
        AS RAW_ML_FORECAST_INDEX,

    t.LOWER_BOUND
        AS RAW_ML_LOWER_BOUND,

    t.UPPER_BOUND
        AS RAW_ML_UPPER_BOUND,

    CASE
        WHEN p.SELECTED_FORECAST_METHOD = 'ML_FORECAST'
            THEN t.FORECAST_MATERIAL_INDEX
        ELSE t.CURRENT_APPROVED_INDEX
    END AS SELECTED_FORECAST_INDEX,

    CASE
        WHEN p.SELECTED_FORECAST_METHOD = 'ML_FORECAST'
            THEN t.FORECAST_MATERIAL_INDEX
                 / NULLIF(t.CURRENT_APPROVED_INDEX, 0)
        ELSE 1.0
    END AS SELECTED_FMIS_MULTIPLIER,

    t.ACTUAL_MATERIAL_INDEX,

    ABS(
        CASE
            WHEN p.SELECTED_FORECAST_METHOD = 'ML_FORECAST'
                THEN t.FORECAST_MATERIAL_INDEX
            ELSE t.CURRENT_APPROVED_INDEX
        END
        - t.ACTUAL_MATERIAL_INDEX
    ) AS SELECTED_ABSOLUTE_ERROR,

    t.ML_ABSOLUTE_ERROR,
    t.NAIVE_ABSOLUTE_ERROR,

    'FMIS_FORECAST_V2' AS MODEL_NAME,
    'V2' AS MODEL_VERSION,
    'TEST' AS DATA_SPLIT,
    'SHADOW' AS DEPLOYMENT_MODE,

    FALSE AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    FALSE AS BUSINESS_DECISION_ALLOWED_FLAG,

    CURRENT_TIMESTAMP() AS CREATED_AT

FROM KMAT_COST_MODEL_DB.CORE_ML.FMIS_TEST_SHADOW_OUTPUT_V2 t
JOIN KMAT_COST_MODEL_DB.CORE_ML.FMIS_SERIES_SHADOW_POLICY_V2 p
  ON t.SERIES_KEY = p.SERIES_KEY;

CREATE OR REPLACE TABLE
    KMAT_COST_MODEL_DB.CORE_ML.FMIS_HYBRID_TEST_EVALUATION_V2
AS
SELECT
    'FMIS_FORECAST_V2' AS MODEL_NAME,
    'V2' AS MODEL_VERSION,
    'TEST' AS DATA_SPLIT,

    COUNT(*) AS OBSERVATION_COUNT,
    COUNT(DISTINCT SERIES_KEY) AS SERIES_COUNT,

    COUNT_IF(
        SELECTED_FORECAST_METHOD = 'ML_FORECAST'
    ) AS ML_FORECAST_OBSERVATIONS,

    COUNT_IF(
        SELECTED_FORECAST_METHOD = 'NAIVE_FALLBACK'
    ) AS FALLBACK_OBSERVATIONS,

    AVG(SELECTED_ABSOLUTE_ERROR)
        AS HYBRID_MAE,

    AVG(ML_ABSOLUTE_ERROR)
        AS RAW_ML_MAE,

    AVG(NAIVE_ABSOLUTE_ERROR)
        AS NAIVE_MAE,

    SUM(SELECTED_ABSOLUTE_ERROR)
        / NULLIF(SUM(ABS(ACTUAL_MATERIAL_INDEX)), 0)
        AS HYBRID_WAPE,

    SUM(ML_ABSOLUTE_ERROR)
        / NULLIF(SUM(ABS(ACTUAL_MATERIAL_INDEX)), 0)
        AS RAW_ML_WAPE,

    SUM(NAIVE_ABSOLUTE_ERROR)
        / NULLIF(SUM(ABS(ACTUAL_MATERIAL_INDEX)), 0)
        AS NAIVE_WAPE,

    1 - (
        AVG(SELECTED_ABSOLUTE_ERROR)
        / NULLIF(AVG(NAIVE_ABSOLUTE_ERROR), 0)
    ) AS HYBRID_MAE_IMPROVEMENT_VS_NAIVE,

    COUNT_IF(
        SELECTED_FMIS_MULTIPLIER IS NULL
        OR SELECTED_FMIS_MULTIPLIER <= 0
    ) AS INVALID_SELECTED_MULTIPLIERS,

    MIN(SELECTED_FMIS_MULTIPLIER)
        AS MIN_SELECTED_FMIS_MULTIPLIER,

    MAX(SELECTED_FMIS_MULTIPLIER)
        AS MAX_SELECTED_FMIS_MULTIPLIER,

    'SHADOW' AS DEPLOYMENT_MODE,
    FALSE AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    FALSE AS BUSINESS_DECISION_ALLOWED_FLAG,

    CURRENT_TIMESTAMP() AS EVALUATED_AT

FROM KMAT_COST_MODEL_DB.CORE_ML.FMIS_HYBRID_TEST_SHADOW_OUTPUT_V2;

SELECT *
FROM KMAT_COST_MODEL_DB.CORE_ML.FMIS_HYBRID_TEST_EVALUATION_V2;

SELECT
    SELECTED_FORECAST_METHOD,
    COUNT(*) AS SERIES_COUNT
FROM KMAT_COST_MODEL_DB.CORE_ML.FMIS_SERIES_SHADOW_POLICY_V2
GROUP BY SELECTED_FORECAST_METHOD;

--
USE DATABASE KMAT_COST_MODEL_DB;
USE SCHEMA CORE_ML;

CREATE TABLE IF NOT EXISTS FMIS_POLICY_DECISION_V2 (
    MODEL_NAME VARCHAR NOT NULL,
    MODEL_VERSION VARCHAR NOT NULL,
    POLICY_NAME VARCHAR NOT NULL,
    POLICY_STATUS VARCHAR NOT NULL,
    RAW_ML_MAE FLOAT,
    HYBRID_MAE FLOAT,
    NAIVE_MAE FLOAT,
    RAW_ML_WAPE FLOAT,
    HYBRID_WAPE FLOAT,
    NAIVE_WAPE FLOAT,
    HYBRID_MAE_CHANGE_VS_RAW_ML FLOAT,
    DECISION_REASON VARCHAR,
    DEPLOYMENT_MODE VARCHAR NOT NULL,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG BOOLEAN NOT NULL,
    BUSINESS_DECISION_ALLOWED_FLAG BOOLEAN NOT NULL,
    DECIDED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

DELETE FROM FMIS_POLICY_DECISION_V2
WHERE MODEL_NAME = 'FMIS_FORECAST_V2'
  AND MODEL_VERSION = 'V2'
  AND POLICY_NAME = 'VALIDATION_DERIVED_SERIES_FALLBACK';

INSERT INTO FMIS_POLICY_DECISION_V2 (
    MODEL_NAME,
    MODEL_VERSION,
    POLICY_NAME,
    POLICY_STATUS,
    RAW_ML_MAE,
    HYBRID_MAE,
    NAIVE_MAE,
    RAW_ML_WAPE,
    HYBRID_WAPE,
    NAIVE_WAPE,
    HYBRID_MAE_CHANGE_VS_RAW_ML,
    DECISION_REASON,
    DEPLOYMENT_MODE,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG
)
SELECT
    'FMIS_FORECAST_V2',
    'V2',
    'VALIDATION_DERIVED_SERIES_FALLBACK',
    'REJECTED_AFTER_TEST',
    RAW_ML_MAE,
    HYBRID_MAE,
    NAIVE_MAE,
    RAW_ML_WAPE,
    HYBRID_WAPE,
    NAIVE_WAPE,
    HYBRID_MAE / NULLIF(RAW_ML_MAE, 0) - 1,
    'The validation-derived series fallback increased test MAE and WAPE compared with the raw ML forecast. Raw ML remains the selected shadow method.',
    'SHADOW',
    FALSE,
    FALSE
FROM FMIS_HYBRID_TEST_EVALUATION_V2;

CREATE OR REPLACE VIEW FMIS_FINAL_SHADOW_OUTPUT_V2 AS
SELECT
    ENTITY_ID,
    SERIES_ID,
    SERIES_KEY,
    INDEX_TIMESTAMP,
    CURRENT_APPROVED_INDEX,
    FORECAST_MATERIAL_INDEX AS SELECTED_FORECAST_INDEX,
    LOWER_BOUND AS SELECTED_FORECAST_LOWER_BOUND,
    UPPER_BOUND AS SELECTED_FORECAST_UPPER_BOUND,
    FMIS_MULTIPLIER AS SELECTED_FMIS_MULTIPLIER,
    FMIS_MULTIPLIER_LOWER_BOUND AS SELECTED_FMIS_MULTIPLIER_LOWER_BOUND,
    FMIS_MULTIPLIER_UPPER_BOUND AS SELECTED_FMIS_MULTIPLIER_UPPER_BOUND,
    ACTUAL_MATERIAL_INDEX,
    ML_ABSOLUTE_ERROR AS SELECTED_ABSOLUTE_ERROR,
    NAIVE_ABSOLUTE_ERROR,
    INTERVAL_COVERED_FLAG,
    'RAW_ML_FORECAST' AS SELECTED_FORECAST_METHOD,
    MODEL_NAME,
    MODEL_VERSION,
    FEATURE_SET_VERSION,
    DATA_SPLIT,
    'ACCEPTED_FOR_SHADOW_WITH_MONITORING' AS MODEL_VALIDATION_STATUS,
    'SHADOW' AS DEPLOYMENT_MODE,
    FALSE AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    FALSE AS BUSINESS_DECISION_ALLOWED_FLAG,
    CREATED_AT
FROM FMIS_TEST_SHADOW_OUTPUT_V2;

CREATE OR REPLACE TABLE FMIS_FINAL_TEST_EVALUATION_V2 AS
SELECT
    MODEL_NAME,
    MODEL_VERSION,
    DATA_SPLIT,
    OBSERVATION_COUNT,
    ML_MAE AS SELECTED_MAE,
    NAIVE_MAE,
    ML_WAPE AS SELECTED_WAPE,
    NAIVE_WAPE,
    ML_MAPE AS SELECTED_MAPE,
    PREDICTION_INTERVAL_COVERAGE,
    MAE_IMPROVEMENT_VS_NAIVE,
    INVALID_MULTIPLIER_ROWS,
    MIN_FMIS_MULTIPLIER AS MIN_SELECTED_FMIS_MULTIPLIER,
    MAX_FMIS_MULTIPLIER AS MAX_SELECTED_FMIS_MULTIPLIER,
    'RAW_ML_FORECAST' AS SELECTED_FORECAST_METHOD,
    'ACCEPTED_FOR_SHADOW_WITH_MONITORING' AS VALIDATION_STATUS,
    'SHADOW' AS DEPLOYMENT_MODE,
    FALSE AS OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    FALSE AS BUSINESS_DECISION_ALLOWED_FLAG,
    CURRENT_TIMESTAMP() AS FINALIZED_AT
FROM FMIS_TEST_EVALUATION_V2;

CREATE TABLE IF NOT EXISTS MODEL_REGISTRY (
    MODEL_NAME VARCHAR NOT NULL,
    MODEL_VERSION VARCHAR NOT NULL,
    MODEL_FAMILY VARCHAR NOT NULL,
    FEATURE_SET_VERSION VARCHAR NOT NULL,
    TRAINING_DATA_CLASS VARCHAR NOT NULL,
    VALIDATION_STATUS VARCHAR NOT NULL,
    DEPLOYMENT_MODE VARCHAR NOT NULL,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG BOOLEAN NOT NULL,
    BUSINESS_DECISION_ALLOWED_FLAG BOOLEAN NOT NULL,
    METRICS_JSON VARIANT,
    DECISION_REASON VARCHAR,
    MODEL_OWNER VARCHAR,
    BUSINESS_OWNER VARCHAR,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

MERGE INTO MODEL_REGISTRY target
USING (
    SELECT
        MODEL_NAME,
        MODEL_VERSION,
        'MULTI_SERIES_FORECASTING' AS MODEL_FAMILY,
        'FMIS_FEATURES_V2' AS FEATURE_SET_VERSION,
        'SYNTHETIC' AS TRAINING_DATA_CLASS,
        VALIDATION_STATUS,
        DEPLOYMENT_MODE,
        OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
        BUSINESS_DECISION_ALLOWED_FLAG,
        OBJECT_CONSTRUCT_KEEP_NULL(
            'selected_forecast_method', SELECTED_FORECAST_METHOD,
            'test_mae', SELECTED_MAE,
            'naive_mae', NAIVE_MAE,
            'test_wape', SELECTED_WAPE,
            'naive_wape', NAIVE_WAPE,
            'test_mape', SELECTED_MAPE,
            'prediction_interval_coverage', PREDICTION_INTERVAL_COVERAGE,
            'mae_improvement_vs_naive', MAE_IMPROVEMENT_VS_NAIVE,
            'invalid_multiplier_rows', INVALID_MULTIPLIER_ROWS,
            'minimum_fmis_multiplier', MIN_SELECTED_FMIS_MULTIPLIER,
            'maximum_fmis_multiplier', MAX_SELECTED_FMIS_MULTIPLIER
        ) AS METRICS_JSON,
        'Raw FMIS V2 outperformed the naive baseline and the validation-derived series fallback on the untouched synthetic test period. The model remains shadow-only and requires real historical validation before production use.' AS DECISION_REASON,
        'DATA_SCIENCE' AS MODEL_OWNER,
        'PROCUREMENT_FINANCE' AS BUSINESS_OWNER
    FROM FMIS_FINAL_TEST_EVALUATION_V2
) source
ON target.MODEL_NAME = source.MODEL_NAME
AND target.MODEL_VERSION = source.MODEL_VERSION
WHEN MATCHED THEN UPDATE SET
    MODEL_FAMILY = source.MODEL_FAMILY,
    FEATURE_SET_VERSION = source.FEATURE_SET_VERSION,
    TRAINING_DATA_CLASS = source.TRAINING_DATA_CLASS,
    VALIDATION_STATUS = source.VALIDATION_STATUS,
    DEPLOYMENT_MODE = source.DEPLOYMENT_MODE,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG = source.OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG = source.BUSINESS_DECISION_ALLOWED_FLAG,
    METRICS_JSON = source.METRICS_JSON,
    DECISION_REASON = source.DECISION_REASON,
    MODEL_OWNER = source.MODEL_OWNER,
    BUSINESS_OWNER = source.BUSINESS_OWNER,
    UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    MODEL_NAME,
    MODEL_VERSION,
    MODEL_FAMILY,
    FEATURE_SET_VERSION,
    TRAINING_DATA_CLASS,
    VALIDATION_STATUS,
    DEPLOYMENT_MODE,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG,
    METRICS_JSON,
    DECISION_REASON,
    MODEL_OWNER,
    BUSINESS_OWNER
)
VALUES (
    source.MODEL_NAME,
    source.MODEL_VERSION,
    source.MODEL_FAMILY,
    source.FEATURE_SET_VERSION,
    source.TRAINING_DATA_CLASS,
    source.VALIDATION_STATUS,
    source.DEPLOYMENT_MODE,
    source.OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    source.BUSINESS_DECISION_ALLOWED_FLAG,
    source.METRICS_JSON,
    source.DECISION_REASON,
    source.MODEL_OWNER,
    source.BUSINESS_OWNER
);

SELECT *
FROM FMIS_POLICY_DECISION_V2
WHERE MODEL_NAME = 'FMIS_FORECAST_V2'
  AND MODEL_VERSION = 'V2';

SELECT * FROM FMIS_FINAL_TEST_EVALUATION_V2;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT ENTITY_ID) AS DISTINCT_ENTITY_IDS,
    COUNT_IF(
        SELECTED_FMIS_MULTIPLIER IS NULL
        OR SELECTED_FMIS_MULTIPLIER <= 0
    ) AS INVALID_MULTIPLIER_ROWS,
    COUNT_IF(
        DEPLOYMENT_MODE <> 'SHADOW'
        OR OFFICIAL_COST_IMPACT_ALLOWED_FLAG <> FALSE
        OR BUSINESS_DECISION_ALLOWED_FLAG <> FALSE
    ) AS INVALID_AUTHORITY_ROWS
FROM FMIS_FINAL_SHADOW_OUTPUT_V2;

SELECT
    MODEL_NAME,
    MODEL_VERSION,
    MODEL_FAMILY,
    FEATURE_SET_VERSION,
    TRAINING_DATA_CLASS,
    VALIDATION_STATUS,
    DEPLOYMENT_MODE,
    OFFICIAL_COST_IMPACT_ALLOWED_FLAG,
    BUSINESS_DECISION_ALLOWED_FLAG,
    METRICS_JSON,
    DECISION_REASON
FROM MODEL_REGISTRY
WHERE MODEL_NAME = 'FMIS_FORECAST_V2'
  AND MODEL_VERSION = 'V2';
