-- ════════════════════════════════════════════════════════════════════
-- ENTERPRISE WORKFLOW & APPROVAL ENGINE — schema objects
-- All under the existing CORE_INTERNAL schema. Idempotent. No DROP.
-- ════════════════════════════════════════════════════════════════════

-- A. WORKFLOW_REQUESTS ------------------------------------------------
CREATE TABLE IF NOT EXISTS PRICING_ENGINE_DB.CORE_INTERNAL.WORKFLOW_REQUESTS (
    REQUEST_ID        VARCHAR NOT NULL,
    REQUEST_TYPE      VARCHAR,           -- PRICE_CHANGE / DISCOUNT_EXCEPTION / MARGIN_EXCEPTION /
                                         -- CONTRACT_APPROVAL / CONTRACT_RENEWAL /
                                         -- SIMULATION_RECOMMENDATION / MANUAL_REQUEST
    REFERENCE_ID      VARCHAR,
    TITLE             VARCHAR,
    DESCRIPTION       VARCHAR,
    REQUESTER         VARCHAR,
    REQUESTER_ROLE    VARCHAR,
    CUSTOMER_ID       VARCHAR,
    SKU               VARCHAR,
    CONTRACT_ID       VARCHAR,
    ORIGINAL_VALUE    FLOAT,
    PROPOSED_VALUE    FLOAT,
    FINANCIAL_IMPACT  FLOAT,
    MARGIN_PERCENT    FLOAT,
    DISCOUNT_PERCENT  FLOAT,
    RISK_LEVEL        VARCHAR,           -- LOW / MEDIUM / HIGH / CRITICAL
    CURRENT_STAGE     NUMBER,
    CURRENT_APPROVER  VARCHAR,           -- role responsible for the current stage
    STATUS            VARCHAR,           -- DRAFT / SUBMITTED / IN_REVIEW / APPROVED /
                                         -- REJECTED / RETURNED / CANCELLED / ESCALATED
    PRIORITY          VARCHAR,           -- LOW / NORMAL / HIGH / URGENT
    SUBMITTED_AT      TIMESTAMP_NTZ,
    UPDATED_AT        TIMESTAMP_NTZ,
    APPROVED_AT       TIMESTAMP_NTZ,
    REJECTED_AT       TIMESTAMP_NTZ,
    CANCELLED_AT      TIMESTAMP_NTZ,
    SLA_DUE_AT        TIMESTAMP_NTZ,
    AI_RISK_SUMMARY   VARCHAR,
    AI_RECOMMENDATION VARCHAR,
    METADATA_JSON     VARCHAR
);

-- B. WORKFLOW_STAGES (routing configuration) --------------------------
CREATE TABLE IF NOT EXISTS PRICING_ENGINE_DB.CORE_INTERNAL.WORKFLOW_STAGES (
    WORKFLOW_ID    VARCHAR,
    REQUEST_TYPE   VARCHAR,
    STAGE_NUMBER   NUMBER,
    STAGE_NAME     VARCHAR,
    APPROVER_ROLE  VARCHAR,
    MIN_AMOUNT     FLOAT,
    MAX_AMOUNT     FLOAT,
    MIN_DISCOUNT   FLOAT,
    MAX_DISCOUNT   FLOAT,
    MIN_MARGIN     FLOAT,
    MAX_MARGIN     FLOAT,
    SLA_HOURS      NUMBER,
    IS_REQUIRED    BOOLEAN,
    IS_ACTIVE      BOOLEAN
);

-- C. WORKFLOW_ACTIONS (immutable action history) ----------------------
CREATE TABLE IF NOT EXISTS PRICING_ENGINE_DB.CORE_INTERNAL.WORKFLOW_ACTIONS (
    ACTION_ID         VARCHAR,
    REQUEST_ID        VARCHAR,
    STAGE_NUMBER      NUMBER,
    ACTION_TYPE       VARCHAR,           -- SUBMITTED / APPROVED / REJECTED / RETURNED /
                                         -- COMMENTED / REASSIGNED / ESCALATED / CANCELLED / SIGNED
    ACTOR             VARCHAR,
    ACTOR_ROLE        VARCHAR,
    COMMENTS          VARCHAR,
    PREVIOUS_STATUS   VARCHAR,
    NEW_STATUS        VARCHAR,
    ACTION_TIMESTAMP  TIMESTAMP_NTZ,
    IP_OR_SESSION_INFO VARCHAR,
    METADATA_JSON     VARCHAR
);

-- D. USER_ROLES (application-level RBAC) ------------------------------
CREATE TABLE IF NOT EXISTS PRICING_ENGINE_DB.CORE_INTERNAL.USER_ROLES (
    USER_NAME     VARCHAR,               -- matches Snowflake CURRENT_USER()
    ROLE_NAME     VARCHAR,               -- PRICING_ANALYST / PRICING_MANAGER / FINANCE_MANAGER /
                                         -- FINANCE_DIRECTOR / LEGAL / SALES_MANAGER / CFO / ADMIN
    DISPLAY_NAME  VARCHAR,
    EMAIL         VARCHAR,
    IS_ACTIVE     BOOLEAN,
    CREATED_AT    TIMESTAMP_NTZ,
    UPDATED_AT    TIMESTAMP_NTZ
);

-- E. WORKFLOW_NOTIFICATIONS (outbox) ----------------------------------
CREATE TABLE IF NOT EXISTS PRICING_ENGINE_DB.CORE_INTERNAL.WORKFLOW_NOTIFICATIONS (
    NOTIFICATION_ID VARCHAR,
    REQUEST_ID      VARCHAR,
    RECIPIENT       VARCHAR,
    CHANNEL         VARCHAR,             -- EMAIL / TEAMS / SLACK / IN_APP
    EVENT_TYPE      VARCHAR,
    SUBJECT         VARCHAR,
    MESSAGE         VARCHAR,
    STATUS          VARCHAR,             -- PENDING / SENT / FAILED / NOT_CONFIGURED
    CREATED_AT      TIMESTAMP_NTZ,
    SENT_AT         TIMESTAMP_NTZ,
    ERROR_MESSAGE   VARCHAR,
    RETRY_COUNT     NUMBER
);

-- F. DIGITAL_SIGNATURES (provider-independent) ------------------------
CREATE TABLE IF NOT EXISTS PRICING_ENGINE_DB.CORE_INTERNAL.DIGITAL_SIGNATURES (
    SIGNATURE_ID        VARCHAR,
    REQUEST_ID          VARCHAR,
    SIGNER              VARCHAR,
    SIGNER_ROLE         VARCHAR,
    SIGNATURE_PROVIDER  VARCHAR,
    EXTERNAL_ENVELOPE_ID VARCHAR,
    SIGNATURE_STATUS    VARCHAR,         -- NOT_REQUIRED / PENDING / SENT / VIEWED /
                                         -- SIGNED / DECLINED / EXPIRED / FAILED / NOT_CONFIGURED
    SIGNED_AT           TIMESTAMP_NTZ,
    DOCUMENT_HASH       VARCHAR,
    CREATED_AT          TIMESTAMP_NTZ
);

-- G. WORKFLOW_COMMENTS ------------------------------------------------
CREATE TABLE IF NOT EXISTS PRICING_ENGINE_DB.CORE_INTERNAL.WORKFLOW_COMMENTS (
    COMMENT_ID    VARCHAR,
    REQUEST_ID    VARCHAR,
    USER_NAME     VARCHAR,
    USER_ROLE     VARCHAR,
    COMMENT_TEXT  VARCHAR,
    CREATED_AT    TIMESTAMP_NTZ
);

-- H. WORKFLOW_ESCALATIONS ---------------------------------------------
CREATE TABLE IF NOT EXISTS PRICING_ENGINE_DB.CORE_INTERNAL.WORKFLOW_ESCALATIONS (
    ESCALATION_ID VARCHAR,
    REQUEST_ID    VARCHAR,
    FROM_APPROVER VARCHAR,
    TO_APPROVER   VARCHAR,
    REASON        VARCHAR,
    ESCALATED_AT  TIMESTAMP_NTZ,
    RESOLVED_AT   TIMESTAMP_NTZ,
    STATUS        VARCHAR                -- OPEN / RESOLVED
);


-- ── Bootstrap YOUR identity as ADMIN so you can get into the app ──
-- Replace nothing; CURRENT_USER() is resolved by Snowflake.
INSERT INTO PRICING_ENGINE_DB.CORE_INTERNAL.USER_ROLES
    (USER_NAME, ROLE_NAME, DISPLAY_NAME, EMAIL, IS_ACTIVE, CREATED_AT, UPDATED_AT)
SELECT CURRENT_USER(), 'ADMIN', CURRENT_USER(), NULL, TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()
WHERE NOT EXISTS (
    SELECT 1 FROM PRICING_ENGINE_DB.CORE_INTERNAL.USER_ROLES WHERE USER_NAME = CURRENT_USER()
);

-- ── Default routing configuration (edit freely in Admin view) ──
INSERT INTO PRICING_ENGINE_DB.CORE_INTERNAL.WORKFLOW_STAGES
(WORKFLOW_ID, REQUEST_TYPE, STAGE_NUMBER, STAGE_NAME, APPROVER_ROLE,
 MIN_AMOUNT, MAX_AMOUNT, MIN_DISCOUNT, MAX_DISCOUNT, MIN_MARGIN, MAX_MARGIN,
 SLA_HOURS, IS_REQUIRED, IS_ACTIVE)
VALUES
-- PRICE_CHANGE
('WF_PRICE','PRICE_CHANGE',1,'Pricing Manager Review','PRICING_MANAGER',0,NULL,NULL,NULL,NULL,NULL,24,TRUE,TRUE),
('WF_PRICE','PRICE_CHANGE',2,'Finance Manager Review','FINANCE_MANAGER',500000,NULL,NULL,NULL,NULL,NULL,48,TRUE,TRUE),
-- DISCOUNT_EXCEPTION
('WF_DISC','DISCOUNT_EXCEPTION',1,'Pricing Manager Review','PRICING_MANAGER',0,NULL,0,15,NULL,NULL,24,TRUE,TRUE),
('WF_DISC','DISCOUNT_EXCEPTION',2,'Finance Manager Review','FINANCE_MANAGER',0,NULL,15,NULL,NULL,NULL,48,TRUE,TRUE),
-- MARGIN_EXCEPTION
('WF_MARG','MARGIN_EXCEPTION',1,'Pricing Manager Review','PRICING_MANAGER',0,NULL,NULL,NULL,NULL,NULL,24,TRUE,TRUE),
('WF_MARG','MARGIN_EXCEPTION',2,'Finance Director Review','FINANCE_DIRECTOR',0,NULL,NULL,NULL,NULL,10,48,TRUE,TRUE),
('WF_MARG','MARGIN_EXCEPTION',3,'CFO Approval','CFO',1000000,NULL,NULL,NULL,NULL,5,72,TRUE,TRUE),
-- CONTRACT_APPROVAL
('WF_CONT','CONTRACT_APPROVAL',1,'Sales Manager Review','SALES_MANAGER',0,NULL,NULL,NULL,NULL,NULL,24,TRUE,TRUE),
('WF_CONT','CONTRACT_APPROVAL',2,'Legal Review','LEGAL',0,NULL,NULL,NULL,NULL,NULL,48,TRUE,TRUE),
('WF_CONT','CONTRACT_APPROVAL',3,'Finance Director Approval','FINANCE_DIRECTOR',0,NULL,NULL,NULL,NULL,NULL,72,TRUE,TRUE),
-- CONTRACT_RENEWAL
('WF_CREN','CONTRACT_RENEWAL',1,'Sales Manager Review','SALES_MANAGER',0,NULL,NULL,NULL,NULL,NULL,24,TRUE,TRUE),
('WF_CREN','CONTRACT_RENEWAL',2,'Finance Manager Approval','FINANCE_MANAGER',0,NULL,NULL,NULL,NULL,NULL,48,TRUE,TRUE),
-- SIMULATION_RECOMMENDATION
('WF_SIM','SIMULATION_RECOMMENDATION',1,'Pricing Manager Review','PRICING_MANAGER',0,NULL,NULL,NULL,NULL,NULL,24,TRUE,TRUE),
('WF_SIM','SIMULATION_RECOMMENDATION',2,'Finance Director Review','FINANCE_DIRECTOR',0,NULL,NULL,NULL,NULL,NULL,48,TRUE,TRUE),
-- MANUAL_REQUEST
('WF_MAN','MANUAL_REQUEST',1,'Pricing Manager Review','PRICING_MANAGER',0,NULL,NULL,NULL,NULL,NULL,24,TRUE,TRUE);