CREATE SCHEMA IF NOT EXISTS
DISCRETE_MFG_COST_MODEL.CORE_INPUT;
CREATE SCHEMA IF NOT EXISTS
DISCRETE_MFG_COST_MODEL.CORE_OUTPUT;

CREATE SCHEMA IF NOT EXISTS
DISCRETE_MFG_COST_MODEL.CORE_INTERNAL;

CREATE SCHEMA IF NOT EXISTS
DISCRETE_MFG_COST_MODEL.CORE_FEATURES;

CREATE SCHEMA IF NOT EXISTS
DISCRETE_MFG_COST_MODEL.CORE_ML;