// ITEM_MASTER TABLE
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.ITEM_MASTER (
    ITEM_ID STRING NOT NULL,
    ITEM_NAME STRING,
    ITEM_TYPE STRING,
    UOM STRING,
    PRODUCT_FAMILY STRING,
    COMMODITY_GROUP STRING,
    STATUS STRING,
    REVISION STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.ITEM_MASTER
ADD COLUMN PREFERRED_SUPPLIER STRING;

// BOM_STRUCTURE
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.BOM_STRUCTURE (
    BOM_ID STRING,
    PARENT_ID STRING NOT NULL,
    COMPONENT_ID STRING NOT NULL,
    QUANTITY NUMBER(18,4),
    UOM STRING,
    REVISION STRING,
    PLANT_ID STRING,
    EFFECTIVE_FROM DATE,
    EFFECTIVE_TO DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

// MATERITAL_COST
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.MATERIAL_COSTS (
    COST_ID STRING,
    ITEM_ID STRING NOT NULL,
    STANDARD_COST NUMBER(18,4),
    CURRENCY_CODE STRING,
    COST_TYPE STRING,
    EFFECTIVE_FROM DATE,
    EFFECTIVE_TO DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

// ROUTING_OPERATIONS
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.ROUTING_OPERATIONS (
    ROUTING_ID STRING,
    ITEM_ID STRING,
    OPERATION_SEQ NUMBER,
    OPERATION_ID STRING,
    WORK_CENTER STRING,
    SETUP_HOURS NUMBER(18,4),
    RUN_HOURS NUMBER(18,4),
    LABOR_RATE NUMBER(18,4),
    MACHINE_RATE NUMBER(18,4),
    PLANT_ID STRING,
    REVISION STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

// SUPPLIER_MASTER
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.SUPPLIER_MASTER (
    SUPPLIER_ID STRING,
    SUPPLIER_NAME STRING,
    COUNTRY STRING,
    STATUS STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


// SUPPLIER_COST
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.SUPPLIER_COSTS (
    ITEM_ID STRING,
    SUPPLIER_ID STRING,
    UNIT_COST NUMBER(18,4),
    CURRENCY_CODE STRING,
    EFFECTIVE_FROM DATE,
    EFFECTIVE_TO DATE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


// SIMULATION_SCENARIOS
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INTERNAL.SIMULATION_SCENARIOS (
    SCENARIO_ID STRING,
    SCENARIO_NAME STRING,
    PRODUCT_ID STRING,
    MATERIAL_MULTIPLIER FLOAT,
    LABOR_MULTIPLIER FLOAT,
    MACHINE_MULTIPLIER FLOAT,
    SIMULATED_TOTAL_COST FLOAT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


// PRODUCT_COST_SNAPSHOT
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_OUTPUT.PRODUCT_COST_SNAPSHOT (
    SNAPSHOT_DATE DATE,
    ITEM_ID STRING,
    PLANT_ID STRING,
    REVISION STRING,
    MATERIAL_COST NUMBER(18,4),
    LABOR_COST NUMBER(18,4),
    MACHINE_COST NUMBER(18,4),
    TOTAL_COST NUMBER(18,4),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


// PLANT_MASTER
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.PLANT_MASTER (
    PLANT_ID STRING,
    PLANT_NAME STRING,
    COUNTRY STRING,
    CURRENCY_CODE STRING
);

// DATA_LOAD_AUDIT
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.DATA_LOAD_AUDIT
(
    LOAD_ID STRING,
    TABLE_NAME STRING,
    RECORD_COUNT NUMBER,
    LOAD_TIME TIMESTAMP,
    STATUS STRING,
    FILE_NAME STRING,
    REVISION STRING
);
ALTER TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.DATA_LOAD_AUDIT
ADD COLUMN EFFECTIVE_FROM DATE;
ALTER TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.DATA_LOAD_AUDIT
ADD COLUMN EFFECTIVE_TO DATE;


// QUALITY HISTORY
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.QUALITY_HISTORY (

    BATCH_ID STRING,
    ITEM_ID STRING,
    PLANT_ID STRING,

    PRODUCTION_DATE DATE,

    UNITS_PRODUCED NUMBER,
    UNITS_PASSED NUMBER,
    UNITS_REWORKED NUMBER,
    UNITS_REJECTED NUMBER,

    SCRAP_RATE FLOAT,
    DEFECT_RATE FLOAT,
    FIRST_PASS_YIELD FLOAT,

    DEFECT_CATEGORY STRING,

    CREATED_AT TIMESTAMP
);

// MACHINE HEALTH
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.MACHINE_HEALTH (

    MACHINE_ID STRING,

    WORK_CENTER STRING,

    PLANT_ID STRING,

    UTILIZATION_PERCENT FLOAT,

    TEMPERATURE FLOAT,

    VIBRATION_LEVEL FLOAT,

    LAST_MAINTENANCE DATE,

    BREAKDOWN_COUNT NUMBER,

    HEALTH_SCORE FLOAT,

    CREATED_AT TIMESTAMP
);

// PRODUCTION_HISTORY
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.PRODUCTION_HISTORY (

    RUN_ID STRING,

    ITEM_ID STRING,

    PLANT_ID STRING,

    ROUTING_ID STRING,

    START_TIME TIMESTAMP,

    END_TIME TIMESTAMP,

    PRODUCED_QTY NUMBER,

    GOOD_QTY NUMBER,

    SCRAP_QTY NUMBER,

    OPERATOR_ID STRING
);

// SUPPLIER_PERFORMANCE
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.SUPPLIER_PERFORMANCE (

    SUPPLIER_ID STRING,

    DELIVERY_DATE DATE,

    ON_TIME_PERCENT FLOAT,

    DEFECT_RATE FLOAT,

    LOT_ACCEPTANCE_RATE FLOAT,

    QUALITY_SCORE FLOAT
);

// MATERIAL_CHARACTERISTICS
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.MATERIAL_PROPERTIES (

    ITEM_ID STRING,

    MATERIAL_TYPE STRING,

    DENSITY FLOAT,

    HARDNESS FLOAT,

    TOLERANCE_CLASS STRING,

    CRITICALITY STRING,

    FRAGILITY_SCORE FLOAT
);

// ENGINEERING_CHANGE
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.ENGINEERING_CHANGE (

    ECN_ID STRING,

    ITEM_ID STRING,

    REVISION STRING,

    CHANGE_DATE DATE,

    CHANGE_REASON STRING,

    AFFECTED_COMPONENTS NUMBER
);

// CUSTOMER_RFQ
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.CUSTOMER_RFQ (

    RFQ_ID STRING,

    CUSTOMER_NAME STRING,

    ITEM_ID STRING,

    RFQ_TEXT STRING,

    RECEIVED_DATE DATE
);

ALTER TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.CUSTOMER_RFQ
ADD COLUMN REVISION STRING;

// QUALITY_INSPECTION
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.QUALITY_INSPECTION (

    INSPECTION_ID STRING,

    ITEM_ID STRING,

    OPERATION_ID STRING,

    INSPECTION_STAGE STRING,

    RESULT STRING,

    DEFECT_TYPE STRING,

    INSPECTOR STRING,

    CREATED_AT TIMESTAMP
);

// INVENTORY_HISTORY
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.INVENTORY_HISTORY (

    ITEM_ID STRING,

    PLANT_ID STRING,

    STOCK_QTY NUMBER,

    SAFETY_STOCK NUMBER,

    DAYS_OF_COVER FLOAT,

    CREATED_AT TIMESTAMP
);

// COMMODITY_PRICE_HISTORY
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INPUT.COMMODITY_PRICE_HISTORY (

    COMMODITY_GROUP STRING,

    PRICE_DATE DATE,

    MARKET_PRICE FLOAT,

    CURRENCY STRING
);

// COST_RUN_HISTORY
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_OUTPUT.COST_RUN_HISTORY
(
    RUN_ID STRING,
    ITEM_ID STRING,
    REVISION STRING,

    MATERIAL_COST NUMBER(18,2),
    LABOR_COST NUMBER(18,2),
    MACHINE_COST NUMBER(18,2),

    TOTAL_COST NUMBER(18,2),

    RUN_TIMESTAMP TIMESTAMP,
    RUN_BY STRING
);

// COLUMN_MAPPING
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INTERNAL.COLUMN_MAPPING (
	SOURCE_TABLE VARCHAR(16777216),
	CANONICAL_FIELD VARCHAR(16777216),
	SOURCE_FIELD VARCHAR(16777216)
);


// MAPPING_AUDIT
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_INTERNAL.MAPPING_AUDIT (
	LOAD_TIME TIMESTAMP_NTZ(9),
	SOURCE_TABLE VARCHAR(16777216),
	STATUS VARCHAR(16777216),
	MESSAGE VARCHAR(16777216)
);

// SYNTHETIC_DATA
CREATE OR REPLACE TABLE
DISCRETE_MFG_COST_MODEL.CORE_ML.CSS_SYNTHETIC_DATA
AS

SELECT *

FROM DISCRETE_MFG_COST_MODEL.CORE_FEATURES.CSS_TRAINING_DATA_V

WHERE 1=0;

// PREDICTION TABLE
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_ML.CSS_PREDICTIONS AS
SELECT
    *,
    DISCRETE_MFG_COST_MODEL.CORE_ML.CSS_MODEL!PREDICT(
        INPUT_DATA => {*}
    ) AS PREDICTION
FROM DISCRETE_MFG_COST_MODEL.CORE_ML.CSS_PREDICTION_INPUT_V;

SELECT *
FROM DISCRETE_MFG_COST_MODEL.CORE_ML.CSS_PREDICTIONS
LIMIT 10;

SELECT
    PREDICTION
FROM DISCRETE_MFG_COST_MODEL.CORE_ML.CSS_PREDICTIONS
LIMIT 5;

// FMIS TRAINING DATA
CREATE OR REPLACE TABLE
DISCRETE_MFG_COST_MODEL.CORE_ML.FMIS_TRAINING_DATA
AS
SELECT *
FROM DISCRETE_MFG_COST_MODEL.CORE_FEATURES.FMIS_TRAINING_DATA_V
WHERE 1=0;

// FMIS_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST
DISCRETE_MFG_COST_MODEL.CORE_ML.FMIS_MODEL
(
    INPUT_DATA => SYSTEM$QUERY_REFERENCE($$

        SELECT
            COMMODITY_GROUP,
            PRICE_DATE,
            MARKET_PRICE
        FROM DISCRETE_MFG_COST_MODEL.CORE_ML.FMIS_TRAINING_DATA

    $$),

    SERIES_COLNAME => 'COMMODITY_GROUP',

    TIMESTAMP_COLNAME => 'PRICE_DATE',

    TARGET_COLNAME => 'MARKET_PRICE',

    CONFIG_OBJECT => {
        'evaluate': TRUE,
        'on_error': 'SKIP'
    }
);

// FORECAST
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_OUTPUT.FMIS_FORECAST AS
SELECT *
FROM TABLE(
DISCRETE_MFG_COST_MODEL.CORE_ML.FMIS_MODEL!FORECAST(
FORECASTING_PERIODS => 30
)
);

// TDS TRAINING
CREATE OR REPLACE TABLE
DISCRETE_MFG_COST_MODEL.CORE_ML.TDS_TRAINING_DATA
AS
SELECT *
FROM DISCRETE_MFG_COST_MODEL.CORE_FEATURES.TDS_TRAINING_DATA_V
WHERE 1=0;

CREATE OR REPLACE SNOWFLAKE.ML.REGRESSION
DISCRETE_MFG_COST_MODEL.CORE_ML.TDS_MODEL
(
    INPUT_DATA => SYSTEM$QUERY_REFERENCE($$

        SELECT

            COMPONENT_COUNT,
            ASSEMBLY_COUNT,
            BOM_RELATIONSHIPS,
            AVG_BRANCH_FACTOR,
            ASSEMBLY_DENSITY,

            TOTAL_MATERIAL_COST,
            LABOR_COST,
            MACHINE_COST,
            TOTAL_COST,

            TOTAL_OPERATIONS,
            TOTAL_PROCESS_TIME,
            AVG_SETUP,
            AVG_RUN,

            AVG_MACHINE_HEALTH,
            AVG_UTILIZATION,
            AVG_BREAKDOWNS,
            WEIGHTED_RUNTIME,

            CHANGE_COUNT,
            ENGINEERING_STABILITY,

            WEIGHTED_SCRAP_RATIO,
            WEIGHTED_YIELD,

            WEIGHTED_PRICE_VOLATILITY,

            TARGET_TDS

        FROM DISCRETE_MFG_COST_MODEL.CORE_ML.TDS_TRAINING_DATA

    $$),

    TARGET_COLNAME => 'TARGET_TDS',

    CONFIG_OBJECT => {
        'evaluate': TRUE,
        'on_error': 'SKIP'
    }
);

//BMCS_RESULTS
CREATE OR REPLACE TABLE DISCRETE_MFG_COST_MODEL.CORE_OUTPUT.BMCS_RESULTS AS

SELECT

    RFQ_ID,

    ITEM_ID,

    REVISION,

    TRY_PARSE_JSON(
        REGEXP_SUBSTR(BMCS_RESPONSE,'\\{.*\\}',1,1,'s')
    ):bmcs::FLOAT AS BMCS,

    TRY_PARSE_JSON(
        REGEXP_SUBSTR(BMCS_RESPONSE,'\\{.*\\}',1,1,'s')
    ):match_status::STRING AS MATCH_STATUS,

    TRY_PARSE_JSON(
        REGEXP_SUBSTR(BMCS_RESPONSE,'\\{.*\\}',1,1,'s')
    ):missing_requirements::STRING AS MISSING_REQUIREMENTS,

    TRY_PARSE_JSON(
        REGEXP_SUBSTR(BMCS_RESPONSE,'\\{.*\\}',1,1,'s')
    ):suggested_components::STRING AS SUGGESTED_COMPONENTS,

    TRY_PARSE_JSON(
        REGEXP_SUBSTR(BMCS_RESPONSE,'\\{.*\\}',1,1,'s')
    ):review_required::BOOLEAN AS REVIEW_REQUIRED,

    TRY_PARSE_JSON(
        REGEXP_SUBSTR(BMCS_RESPONSE,'\\{.*\\}',1,1,'s')
    ):summary::STRING AS AI_SUMMARY,

    CURRENT_TIMESTAMP AS CREATED_AT

FROM DISCRETE_MFG_COST_MODEL.CORE_OUTPUT.BMCS_AI_RESPONSE_V;

SELECT

RFQ_ID,

ITEM_ID,

SNOWFLAKE.CORTEX.AI_COMPLETE(

'llama3.1-70b',

CONCAT(

'You are a senior manufacturing engineer.

Compare the customer RFQ with the internal manufacturing context.

Return ONLY a JSON object.

Schema:

{
"bmcs": number,
"match_status": "HIGH|MEDIUM|LOW",
"missing_requirements": "...",
"suggested_components": "...",
"review_required": true,
"summary": "..."
}

RFQ Requirements:
',

TO_JSON(EXTRACTED_REQUIREMENTS),

'

Product:
',

ITEM_NAME,

'

Product Family:
',

PRODUCT_FAMILY,

'

Commodity:
',

COMMODITY_GROUP,

'

Manufacturing Summary:

Component Count: ',TO_VARCHAR(COMPONENT_COUNT),

'
Assembly Count: ',TO_VARCHAR(ASSEMBLY_COUNT),

'
Material Cost: ',TO_VARCHAR(TOTAL_MATERIAL_COST),

'
Labor Cost: ',TO_VARCHAR(LABOR_COST),

'
Machine Cost: ',TO_VARCHAR(MACHINE_COST),

'
Machine Health: ',TO_VARCHAR(AVG_MACHINE_HEALTH),

'
Supplier Quality: ',TO_VARCHAR(AVG_SUPPLIER_QUALITY),

'
Engineering Stability: ',TO_VARCHAR(ENGINEERING_STABILITY),

'
Tooling Degradation Score: ',TO_VARCHAR(TDS)

)

) AS BMCS_RESPONSE

FROM DISCRETE_MFG_COST_MODEL.CORE_FEATURES.BMCS_CONTEXT_V;