// ITEM_MASTER
INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.ITEM_MASTER
(
    ITEM_ID,
    ITEM_NAME,
    ITEM_TYPE,
    UOM,
    PRODUCT_FAMILY,
    COMMODITY_GROUP,
    STATUS,
    REVISION,
    CREATED_AT,
    PREFERRED_SUPPLIER
)
VALUES
('BIKE',     'Mountain Bike',   'FG',  'EA', 'BICYCLES', 'FINISHED_GOODS', 'ACTIVE', 'REV_A', CURRENT_TIMESTAMP, NULL),
('FRAME_A',  'Steel Frame',     'RM',  'EA', 'BICYCLES', 'STEEL',          'ACTIVE', 'REV_A', CURRENT_TIMESTAMP, 'STEEL_SUPPLIER'),
('FRAME_B',  'Aluminum Frame',  'RM',  'EA', 'BICYCLES', 'ALUMINUM',       'ACTIVE', 'REV_B', CURRENT_TIMESTAMP, 'ALUMINUM_SUPPLIER'),
('WHEEL',    'Wheel Assembly',  'ASM', 'EA', 'BICYCLES', 'ASSEMBLY',       'ACTIVE', 'REV_A', CURRENT_TIMESTAMP, NULL),
('TIRE',     'Rubber Tire',     'RM',  'EA', 'BICYCLES', 'RUBBER',         'ACTIVE', 'REV_A', CURRENT_TIMESTAMP, 'RUBBER_SUPPLIER'),
('RIM',      'Alloy Rim',       'RM',  'EA', 'BICYCLES', 'ALUMINUM',       'ACTIVE', 'REV_A', CURRENT_TIMESTAMP, 'ALUMINUM_SUPPLIER'),
('HANDLE',   'Handle Bar',      'RM',  'EA', 'BICYCLES', 'STEEL',          'ACTIVE', 'REV_A', CURRENT_TIMESTAMP, 'STEEL_SUPPLIER');

UPDATE DISCRETE_MFG_COST_MODEL.CORE_INPUT.ITEM_MASTER
SET PREFERRED_SUPPLIER =
    CASE ITEM_ID
        WHEN 'FRAME_A' THEN 'SUP001'
        WHEN 'HANDLE'  THEN 'SUP001'
        WHEN 'FRAME_B' THEN 'SUP002'
        WHEN 'RIM'     THEN 'SUP002'
        WHEN 'TIRE'    THEN 'SUP003'
        ELSE PREFERRED_SUPPLIER
    END
WHERE ITEM_ID IN
(
    'FRAME_A',
    'HANDLE',
    'FRAME_B',
    'RIM',
    'TIRE'
);


UPDATE DISCRETE_MFG_COST_MODEL.CORE_INPUT.ITEM_MASTER
SET PREFERRED_SUPPLIER='SUPP001'
WHERE ITEM_ID='CPU';

UPDATE DISCRETE_MFG_COST_MODEL.CORE_INPUT.ITEM_MASTER
SET PREFERRED_SUPPLIER='SUPP002'
WHERE ITEM_ID='MEMORY';

UPDATE DISCRETE_MFG_COST_MODEL.CORE_INPUT.ITEM_MASTER
SET PREFERRED_SUPPLIER='SUPP003'
WHERE ITEM_ID='DISPLAY_ASSEMBLY';

UPDATE DISCRETE_MFG_COST_MODEL.CORE_INPUT.ITEM_MASTER
SET PREFERRED_SUPPLIER='SUPP004'
WHERE ITEM_ID='CHASSIS';

UPDATE DISCRETE_MFG_COST_MODEL.CORE_INPUT.ITEM_MASTER
SET PREFERRED_SUPPLIER='SUPP005'
WHERE ITEM_ID='BATTERY_CELL';

UPDATE DISCRETE_MFG_COST_MODEL.CORE_INPUT.ITEM_MASTER
SET PREFERRED_SUPPLIER='SUPP006'
WHERE ITEM_ID='MOTHERBOARD';

UPDATE DISCRETE_MFG_COST_MODEL.CORE_INPUT.ITEM_MASTER
SET PREFERRED_SUPPLIER='SUPP007'
WHERE ITEM_ID='KEYBOARD';

UPDATE DISCRETE_MFG_COST_MODEL.CORE_INPUT.ITEM_MASTER
SET PREFERRED_SUPPLIER='SUPP008'
WHERE ITEM_ID='TOUCHPAD';

// PLANT_MASTER
INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.PLANT_MASTER
VALUES
('PLANT_A','Pune Manufacturing','India','INR'),
('PLANT_B','Chennai Manufacturing','India','INR');


// BOM_STRUCTUTRE
INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.BOM_STRUCTURE
(
    BOM_ID,
    PARENT_ID,
    COMPONENT_ID,
    QUANTITY,
    UOM,
    REVISION,
    PLANT_ID,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    CREATED_AT
)
VALUES
(
    'BOM001',
    'BIKE',
    'FRAME_A',
    1,
    'EA',
    'REV_A',
    'PLANT_A',
    '2025-01-01',
    NULL,
    CURRENT_TIMESTAMP
),
(
    'BOM001',
    'BIKE',
    'WHEEL',
    2,
    'EA',
    'REV_A',
    'PLANT_A',
    '2025-01-01',
    NULL,
    CURRENT_TIMESTAMP
),
(
    'BOM001',
    'BIKE',
    'HANDLE',
    1,
    'EA',
    'REV_A',
    'PLANT_A',
    '2025-01-01',
    NULL,
    CURRENT_TIMESTAMP
),
(
    'BOM002',
    'WHEEL',
    'TIRE',
    1,
    'EA',
    'REV_A',
    'PLANT_A',
    '2025-01-01',
    NULL,
    CURRENT_TIMESTAMP
),
(
    'BOM002',
    'WHEEL',
    'RIM',
    1,
    'EA',
    'REV_A',
    'PLANT_A',
    '2025-01-01',
    NULL,
    CURRENT_TIMESTAMP
);


INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.BOM_STRUCTURE
(
    BOM_ID,
    PARENT_ID,
    COMPONENT_ID,
    QUANTITY,
    UOM,
    REVISION,
    PLANT_ID,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    CREATED_AT
)
VALUES
(
    'BOM003',
    'BIKE',
    'FRAME_B',
    1,
    'EA',
    'REV_B',
    'PLANT_A',
    '2025-07-01',
    NULL,
    CURRENT_TIMESTAMP
),
(
    'BOM003',
    'BIKE',
    'WHEEL',
    2,
    'EA',
    'REV_B',
    'PLANT_A',
    '2025-07-01',
    NULL,
    CURRENT_TIMESTAMP
),
(
    'BOM003',
    'BIKE',
    'HANDLE',
    1,
    'EA',
    'REV_B',
    'PLANT_A',
    '2025-07-01',
    NULL,
    CURRENT_TIMESTAMP
);


// MATERITAL_COST
INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.MATERIAL_COSTS
(
    COST_ID,
    ITEM_ID,
    STANDARD_COST,
    CURRENCY_CODE,
    COST_TYPE,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    CREATED_AT
)
VALUES
(
    'COST001',
    'FRAME_A',
    100,
    'INR',
    'STANDARD',
    '2025-01-01',
    NULL,
    CURRENT_TIMESTAMP
),
(
    'COST002',
    'FRAME_B',
    140,
    'INR',
    'STANDARD',
    '2025-07-01',
    NULL,
    CURRENT_TIMESTAMP
),
(
    'COST003',
    'TIRE',
    30,
    'INR',
    'STANDARD',
    '2025-01-01',
    NULL,
    CURRENT_TIMESTAMP
),
(
    'COST004',
    'RIM',
    40,
    'INR',
    'STANDARD',
    '2025-01-01',
    NULL,
    CURRENT_TIMESTAMP
),
(
    'COST005',
    'HANDLE',
    20,
    'INR',
    'STANDARD',
    '2025-01-01',
    NULL,
    CURRENT_TIMESTAMP
);


// SUPPLIER_MASTER
INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.SUPPLIER_MASTER
VALUES
('SUP001','SteelWorks Ltd','India','ACTIVE',CURRENT_TIMESTAMP),
('SUP002','AlloyTech Industries','India','ACTIVE',CURRENT_TIMESTAMP),
('SUP003','Global Rubber Corp','Thailand','ACTIVE',CURRENT_TIMESTAMP);


// SUPPLIER_COST
INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.SUPPLIER_COSTS
(
    ITEM_ID,
    SUPPLIER_ID,
    UNIT_COST,
    CURRENCY_CODE,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    CREATED_AT
)
VALUES
(
    'FRAME_A',
    'SUP001',
    100,
    'INR',
    '2025-01-01',
    NULL,
    CURRENT_TIMESTAMP
),
(
    'FRAME_A',
    'SUP002',
    95,
    'INR',
    '2025-01-01',
    NULL,
    CURRENT_TIMESTAMP
),
(
    'FRAME_B',
    'SUP002',
    140,
    'INR',
    '2025-07-01',
    NULL,
    CURRENT_TIMESTAMP
),
(
    'TIRE',
    'SUP003',
    30,
    'INR',
    '2025-01-01',
    NULL,
    CURRENT_TIMESTAMP
);


// ROUTING_OPERATIONS
INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.ROUTING_OPERATIONS
VALUES

(
'ROUTE001',
'BIKE',
10,
'FRAME_ASSEMBLY',
'WC_FRAME',

1.5,
0.5,

25,
20,

'PLANT_A',
'REV_A',
CURRENT_TIMESTAMP
),

(
'ROUTE001',
'BIKE',
20,
'FINAL_ASSEMBLY',
'WC_FINAL',

1.0,
1.0,

25,
20,

'PLANT_A',
'REV_A',
CURRENT_TIMESTAMP
),

(
'ROUTE002',
'WHEEL',
10,
'WHEEL_BUILD',
'WC_WHEEL',

0.5,
0.2,

25,
20,

'PLANT_A',
'REV_A',
CURRENT_TIMESTAMP
);


//SUPPLIER
INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.SUPPLIER_MASTER
(
SUPPLIER_ID,
SUPPLIER_NAME,
COUNTRY,
STATUS
)
VALUES

('SUPP004','Intel Components Ltd','USA','ACTIVE'),
('SUPP005','Samsung Electronics','South Korea','ACTIVE'),
('SUPP006','LG Display','South Korea','ACTIVE'),
('SUPP007','Foxconn Manufacturing','China','ACTIVE'),
('SUPP008','Panasonic Energy','Japan','ACTIVE'),
('SUPP009','Bosch Industrial','Germany','ACTIVE'),
('SUPP010','Tata Electronics','India','ACTIVE'),
('SUPP011','Delta Manufacturing','Singapore','ACTIVE');

INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.SUPPLIER_MASTER
VALUES
('SUP0012','Premium Metals','Germany','ACTIVE',CURRENT_TIMESTAMP);

INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.SUPPLIER_MASTER
VALUES
('SUP0013','Budget Steel','India','ACTIVE',CURRENT_TIMESTAMP);

INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.SUPPLIER_COSTS
(
    ITEM_ID,
    SUPPLIER_ID,
    UNIT_COST,
    CURRENCY_CODE,
    EFFECTIVE_FROM,
    EFFECTIVE_TO
)
VALUES
(
    'CPU',
    'SUPP001',
    295.00,
    'USD',
    '2025-01-01',
    NULL
),
(
    'MEMORY',
    'SUPP002',
    72.00,
    'USD',
    '2025-01-01',
    NULL
),
(
    'DISPLAY_ASSEMBLY',
    'SUPP003',
    168.00,
    'USD',
    '2025-01-01',
    NULL
),
(
    'CHASSIS',
    'SUPP004',
    49.00,
    'USD',
    '2025-01-01',
    NULL
),
(
    'BATTERY_CELL',
    'SUPP005',
    32.00,
    'USD',
    '2025-01-01',
    NULL
),
(
    'MOTHERBOARD',
    'SUPP006',
    182.00,
    'USD',
    '2025-01-01',
    NULL
),
(
    'KEYBOARD',
    'SUPP007',
    18.00,
    'USD',
    '2025-01-01',
    NULL
),
(
    'TOUCHPAD',
    'SUPP008',
    11.00,
    'USD',
    '2025-01-01',
    NULL
);

INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.SUPPLIER_COSTS
VALUES
(
'FRAME_A',
'SUP0012',
118,
'INR',
'2026-01-01',
NULL,
CURRENT_TIMESTAMP
);

INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.SUPPLIER_COSTS
VALUES
(
'FRAME_A',
'SUP0013',
89,
'INR',
'2026-01-01',
NULL,
CURRENT_TIMESTAMP
);

//QUALITY_HISOTRY
INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.QUALITY_HISTORY
(
    BATCH_ID,
    ITEM_ID,
    PLANT_ID,
    PRODUCTION_DATE,
    UNITS_PRODUCED,
    UNITS_PASSED,
    UNITS_REWORKED,
    UNITS_REJECTED,
    SCRAP_RATE,
    DEFECT_RATE,
    FIRST_PASS_YIELD,
    DEFECT_CATEGORY,
    CREATED_AT
)
VALUES
('B001','BIKE','PLANT_A','2026-01-10',100,95,3,2,2.0,3.0,95.0,'Assembly',CURRENT_TIMESTAMP),
('B002','BIKE','PLANT_A','2026-01-20',120,113,4,3,2.5,3.5,94.2,'Wheel Alignment',CURRENT_TIMESTAMP),
('B003','BIKE','PLANT_A','2026-02-02',90,83,4,3,3.3,4.0,92.2,'Frame Weld',CURRENT_TIMESTAMP),
('B004','WHEEL','PLANT_A','2026-02-15',300,292,5,3,1.0,1.8,97.3,'Balancing',CURRENT_TIMESTAMP),
('B005','FRAME_A','PLANT_A','2026-02-18',200,190,5,5,2.5,2.7,95.0,'Surface Finish',CURRENT_TIMESTAMP);

INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.QUALITY_HISTORY
(
    BATCH_ID,
    ITEM_ID,
    PLANT_ID,
    PRODUCTION_DATE,
    UNITS_PRODUCED,
    UNITS_PASSED,
    UNITS_REWORKED,
    UNITS_REJECTED,
    SCRAP_RATE,
    DEFECT_RATE,
    FIRST_PASS_YIELD,
    DEFECT_CATEGORY,
    CREATED_AT
)
VALUES
('B006','BIKE','PLANT_B','2026-03-05',100,87,7,6,6.0,8.0,87.0,'Frame Crack',CURRENT_TIMESTAMP),
('B007','BIKE','PLANT_B','2026-03-10',120,108,6,6,5.0,7.0,90.0,'Wheel Misalignment',CURRENT_TIMESTAMP),
('B008','FRAME_A','PLANT_B','2026-03-15',180,166,7,7,3.9,5.0,92.2,'Surface Finish',CURRENT_TIMESTAMP);

//MACHINE_HEALTH
INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.MACHINE_HEALTH
VALUES
('M001','WC_FRAME','PLANT_A',82,42,0.30,'2026-01-01',1,92,CURRENT_TIMESTAMP),
('M002','WC_FINAL','PLANT_A',88,46,0.45,'2025-12-20',2,85,CURRENT_TIMESTAMP),
('M003','WC_WHEEL','PLANT_A',74,39,0.18,'2026-02-01',0,97,CURRENT_TIMESTAMP);

INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.MACHINE_HEALTH
VALUES
('M004','WC_FRAME','PLANT_B',96,58,1.25,'2025-08-01',11,61,CURRENT_TIMESTAMP),
('M005','WC_FINAL','PLANT_B',93,56,0.92,'2025-07-15',9,68,CURRENT_TIMESTAMP),
('M006','WC_WHEEL','PLANT_B',89,53,0.75,'2025-09-01',6,74,CURRENT_TIMESTAMP);

//PRODUCTION_HISTORY
INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.PRODUCTION_HISTORY
VALUES
('RUN001','BIKE','PLANT_A','ROUTE001','2026-01-10 08:00','2026-01-10 13:30',100,95,5,'EMP001'),
('RUN002','BIKE','PLANT_A','ROUTE001','2026-01-20 08:00','2026-01-20 14:00',120,116,4,'EMP002'),
('RUN003','WHEEL','PLANT_A','ROUTE002','2026-01-25 09:00','2026-01-25 12:00',300,294,6,'EMP003');

//SUPPLIER_PERFORMANCE
INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.SUPPLIER_PERFORMANCE
VALUES
('SUP001','2026-01-01',97,1.2,99,96),
('SUP001','2026-02-01',96,1.4,98,95),

('SUP002','2026-01-01',94,2.6,97,91),
('SUP002','2026-02-01',93,2.9,96,90),

('SUP003','2026-01-01',90,4.5,93,84),
('SUP003','2026-02-01',91,4.0,94,86);

INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.SUPPLIER_PERFORMANCE
VALUES
('SUP0012','2026-03-01',99.2,0.30,99.8,99.5);

INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.SUPPLIER_PERFORMANCE
VALUES
('SUP0013','2026-03-01',86,6.5,89,73);

//MATERIAL_PROPERTIES
INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.MATERIAL_PROPERTIES
VALUES
('FRAME_A','Steel',7.8,180,'T1','HIGH',0.20),
('FRAME_B','Aluminum',2.7,95,'T2','HIGH',0.35),
('TIRE','Rubber',1.2,45,'T3','MEDIUM',0.10),
('RIM','Aluminum',2.7,120,'T2','HIGH',0.25),
('HANDLE','Steel',7.8,170,'T2','MEDIUM',0.15);

//ENGINEERING_CHANGE
INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.ENGINEERING_CHANGE
VALUES
('ECN001','BIKE','REV_A','2026-01-15','Frame redesign',2),
('ECN002','BIKE','REV_A','2026-02-10','Wheel tolerance update',1),
('ECN003','FRAME_A','REV_A','2026-02-20','Material grade improvement',1);

INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.ENGINEERING_CHANGE
VALUES
('ECN004','BIKE','REV_B','2026-04-01','Material optimization',3),
('ECN005','BIKE','REV_B','2026-04-18','Brake mounting update',2),
('ECN006','BIKE','REV_B','2026-05-02','Frame reinforcement',4),
('ECN007','BIKE','REV_B','2026-05-28','Cable routing redesign',1);

//CUSTOMER_RFQ
INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.CUSTOMER_RFQ
(
    RFQ_ID,
    CUSTOMER_NAME,
    ITEM_ID,
    REVISION,
    RFQ_TEXT,
    RECEIVED_DATE
)
VALUES
(
    'RFQ001',
    'Trek Bicycles',
    'BIKE',
    'REV_A',
    'Lightweight mountain bike with reinforced frame and alloy wheels.',
    '2026-01-15'
),
(
    'RFQ002',
    'Decathlon',
    'BIKE',
    'REV_A',
    'Cost optimized bicycle with standard wheel assembly.',
    '2026-02-01'
),
(
    'RFQ003',
    'Decathlon',
    'BIKE',
    'REV_A',
    'Low-cost commuter bicycle prioritizing affordability over premium materials.',
    '2026-03-10'
),
(
    'RFQ004',
    'Trek',
    'BIKE',
    'REV_B',
    'High-performance mountain bike requiring lightweight frame and premium components.',
    '2026-03-18'
),
(
    'RFQ005',
    'Giant',
    'BIKE',
    'REV_B',
    'Export-ready bicycle with enhanced durability and corrosion resistance.',
    '2026-03-28'
);

//QUALITY_INSPECTION
INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.QUALITY_INSPECTION
VALUES
('QI001','BIKE','FINAL_ASSEMBLY','Final','PASS',NULL,'Inspector_A',CURRENT_TIMESTAMP),
('QI002','BIKE','FRAME_ASSEMBLY','Incoming','FAIL','Frame Alignment','Inspector_B',CURRENT_TIMESTAMP),
('QI003','WHEEL','WHEEL_BUILD','Final','PASS',NULL,'Inspector_C',CURRENT_TIMESTAMP);

//INVENTORY_HISTORY
INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.INVENTORY_HISTORY
VALUES
('FRAME_A','PLANT_A',250,80,18,CURRENT_TIMESTAMP),
('FRAME_B','PLANT_A',120,60,9,CURRENT_TIMESTAMP),
('TIRE','PLANT_A',450,150,25,CURRENT_TIMESTAMP),
('RIM','PLANT_A',320,120,21,CURRENT_TIMESTAMP),
('HANDLE','PLANT_A',280,100,17,CURRENT_TIMESTAMP);

INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.INVENTORY_HISTORY
VALUES
('FRAME_A','PLANT_B',55,80,4,CURRENT_TIMESTAMP),
('FRAME_B','PLANT_B',25,60,2,CURRENT_TIMESTAMP),
('TIRE','PLANT_B',90,150,5,CURRENT_TIMESTAMP),
('RIM','PLANT_B',60,120,4,CURRENT_TIMESTAMP),
('HANDLE','PLANT_B',48,100,3,CURRENT_TIMESTAMP);

//COMMODITY_PRICE_HISTORY
INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.COMMODITY_PRICE_HISTORY
VALUES
('STEEL','2026-01-01',100,'USD'),
('STEEL','2026-02-01',102,'USD'),
('STEEL','2026-03-01',105,'USD'),

('ALUMINUM','2026-01-01',140,'USD'),
('ALUMINUM','2026-02-01',145,'USD'),
('ALUMINUM','2026-03-01',150,'USD'),

('RUBBER','2026-01-01',30,'USD'),
('RUBBER','2026-02-01',31,'USD'),
('RUBBER','2026-03-01',32,'USD');

INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.COMMODITY_PRICE_HISTORY
VALUES
('STEEL','2026-04-01',109,'USD'),
('STEEL','2026-05-01',104,'USD'),
('STEEL','2026-06-01',111,'USD'),

('ALUMINUM','2026-04-01',152,'USD'),
('ALUMINUM','2026-05-01',149,'USD'),
('ALUMINUM','2026-06-01',156,'USD'),

('RUBBER','2026-04-01',33,'USD'),
('RUBBER','2026-05-01',31,'USD'),
('RUBBER','2026-06-01',34,'USD');

INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.ENGINEERING_CHANGE
(
    ECN_ID,
    ITEM_ID,
    REVISION,
    CHANGE_DATE,
    CHANGE_REASON,
    AFFECTED_COMPONENTS
)
VALUES
(
    'ECN_WHEEL_001',
    'WHEEL',
    'REV_A',
    CURRENT_DATE - 120,
    'Initial Design Release',
    0
);

INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_INPUT.PRODUCTION_HISTORY
(
    RUN_ID,
    ITEM_ID,
    PLANT_ID,
    ROUTING_ID,
    START_TIME,
    END_TIME,
    PRODUCED_QTY,
    GOOD_QTY,
    SCRAP_QTY,
    OPERATOR_ID
)
VALUES
(
    'RUN_WHEEL_001',
    'WHEEL',
    'PLANT_A',
    'ROUTE_WHEEL',
    CURRENT_TIMESTAMP - INTERVAL '2' HOUR,
    CURRENT_TIMESTAMP,
    500,
    495,
    5,
    'OP001'
);

INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_ML.CSS_SYNTHETIC_DATA
SELECT *
FROM DISCRETE_MFG_COST_MODEL.CORE_FEATURES.CSS_TRAINING_DATA_V;

SELECT COUNT(*)
FROM DISCRETE_MFG_COST_MODEL.CORE_ML.CSS_SYNTHETIC_DATA;

INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_ML.CSS_SYNTHETIC_DATA

SELECT

TOP_LEVEL_ITEM,

REVISION,

COMPONENT_COUNT,

ASSEMBLY_COUNT,

BOM_RELATIONSHIPS,

ROUND(AVG_BRANCH_FACTOR + UNIFORM(-0.4,0.4,RANDOM()),2),

ROUND(ASSEMBLY_DENSITY + UNIFORM(-0.3,0.3,RANDOM()),2),

ROUND(TOTAL_MATERIAL_COST * UNIFORM(0.92,1.08,RANDOM()),2),

ROUND(LABOR_COST * UNIFORM(0.90,1.10,RANDOM()),2),

ROUND(MACHINE_COST * UNIFORM(0.90,1.10,RANDOM()),2),

ROUND(TOTAL_COST * UNIFORM(0.92,1.08,RANDOM()),2),

SUPPLIER_COUNT,

LEAST(100,
GREATEST(55,
AVG_SUPPLIER_QUALITY + UNIFORM(-12,12,RANDOM())
)),

LEAST(100,
GREATEST(45,
AVG_MACHINE_HEALTH + UNIFORM(-15,15,RANDOM())
)),

LEAST(100,
GREATEST(40,
AVG_UTILIZATION + UNIFORM(-18,18,RANDOM())
)),

CHANGE_COUNT,

LEAST(100,
GREATEST(20,
ENGINEERING_STABILITY + UNIFORM(-20,20,RANDOM())
)),

LEAST(20,
GREATEST(0,
WEIGHTED_PRICE_VOLATILITY + UNIFORM(-2,2,RANDOM())
)),

LEAST(1,
GREATEST(0,
LOW_STOCK_RATIO + UNIFORM(-0.15,0.15,RANDOM())
)),

AVG_SCRAP_RATE,

AVG_DEFECT_RATE,

AVG_FIRST_PASS_YIELD,

CASE

WHEN

AVG_SUPPLIER_QUALITY < 80

OR AVG_MACHINE_HEALTH < 70

OR AVG_UTILIZATION > 90

OR ENGINEERING_STABILITY < 60

THEN 1

ELSE 0

END

FROM DISCRETE_MFG_COST_MODEL.CORE_FEATURES.CSS_TRAINING_DATA_V,

TABLE(GENERATOR(ROWCOUNT=>500));


INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_ML.FMIS_TRAINING_DATA
SELECT *
FROM DISCRETE_MFG_COST_MODEL.CORE_FEATURES.FMIS_TRAINING_DATA_V;


INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_ML.FMIS_TRAINING_DATA
WITH BASE AS (
SELECT
COMMODITY_GROUP,
MIN(PRICE_DATE) AS START_DATE,
AVG(MARKET_PRICE) AS BASE_PRICE,
ANY_VALUE(CURRENCY) AS CURRENCY
FROM DISCRETE_MFG_COST_MODEL.CORE_INPUT.COMMODITY_PRICE_HISTORY
GROUP BY COMMODITY_GROUP
),
DATES AS (
SELECT
ROW_NUMBER() OVER(ORDER BY SEQ4())-1 AS DAY_NUM
FROM TABLE(GENERATOR(ROWCOUNT=>180))
)
SELECT
b.COMMODITY_GROUP,
DATEADD(DAY,d.DAY_NUM,b.START_DATE) AS PRICE_DATE,
ROUND(
b.BASE_PRICE
*
(
1
+
0.0008*d.DAY_NUM
+
UNIFORM(-25,25,RANDOM())/1000
)
,2)
AS MARKET_PRICE,
b.CURRENCY,
NULL,
NULL,
NULL
FROM BASE b
CROSS JOIN DATES d;

SELECT
COMMODITY_GROUP,
COUNT(*)
FROM DISCRETE_MFG_COST_MODEL.CORE_ML.FMIS_TRAINING_DATA
GROUP BY COMMODITY_GROUP;

SELECT
COMMODITY_GROUP,
MIN(PRICE_DATE),
MAX(PRICE_DATE),
MIN(MARKET_PRICE),
MAX(MARKET_PRICE),
AVG(MARKET_PRICE)
FROM DISCRETE_MFG_COST_MODEL.CORE_ML.FMIS_TRAINING_DATA
GROUP BY COMMODITY_GROUP;

CALL DISCRETE_MFG_COST_MODEL.CORE_ML.FMIS_MODEL!FORECAST(
    FORECASTING_PERIODS => 30
);

CALL DISCRETE_MFG_COST_MODEL.CORE_ML.FMIS_MODEL!FORECAST(
    FORECASTING_PERIODS => 30,
    CONFIG_OBJECT => {
        'prediction_interval': 0.95
    }
);

INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_ML.TDS_TRAINING_DATA
SELECT *
FROM DISCRETE_MFG_COST_MODEL.CORE_FEATURES.TDS_TRAINING_DATA_V;

INSERT INTO DISCRETE_MFG_COST_MODEL.CORE_ML.TDS_TRAINING_DATA

SELECT

TOP_LEVEL_ITEM,

REVISION,

COMPONENT_COUNT,

ASSEMBLY_COUNT,

BOM_RELATIONSHIPS,

ROUND(COALESCE(AVG_BRANCH_FACTOR,1) + UNIFORM(-0.30,0.30,RANDOM()),2),

ROUND(COALESCE(ASSEMBLY_DENSITY,1) + UNIFORM(-0.20,0.20,RANDOM()),2),

ROUND(COALESCE(TOTAL_MATERIAL_COST,0) * UNIFORM(0.94,1.06,RANDOM()),2),

ROUND(COALESCE(LABOR_COST,0) * UNIFORM(0.93,1.07,RANDOM()),2),

ROUND(COALESCE(MACHINE_COST,0) * UNIFORM(0.92,1.08,RANDOM()),2),

ROUND(COALESCE(TOTAL_COST,0) * UNIFORM(0.94,1.06,RANDOM()),2),

COALESCE(TOTAL_OPERATIONS,0),

ROUND(COALESCE(TOTAL_PROCESS_TIME,0) * UNIFORM(0.90,1.10,RANDOM()),2),

ROUND(COALESCE(AVG_SETUP,0) * UNIFORM(0.90,1.10,RANDOM()),2),

ROUND(COALESCE(AVG_RUN,0) * UNIFORM(0.90,1.10,RANDOM()),2),

LEAST(
100,
GREATEST(
50,
COALESCE(AVG_MACHINE_HEALTH,80) + UNIFORM(-10,10,RANDOM())
)
),

LEAST(
100,
GREATEST(
40,
COALESCE(AVG_UTILIZATION,50) + UNIFORM(-15,15,RANDOM())
)
),

LEAST(
10,
GREATEST(
0,
COALESCE(AVG_BREAKDOWNS,0) + UNIFORM(-2,2,RANDOM())
)
),

ROUND(COALESCE(WEIGHTED_RUNTIME,0) * UNIFORM(0.90,1.10,RANDOM()),2),

COALESCE(CHANGE_COUNT,0),

LEAST(
100,
GREATEST(
20,
COALESCE(ENGINEERING_STABILITY,100) + UNIFORM(-15,15,RANDOM())
)
),

LEAST(
1,
GREATEST(
0,
COALESCE(WEIGHTED_SCRAP_RATIO,0) + UNIFORM(-0.03,0.03,RANDOM())
)
),

LEAST(
1,
GREATEST(
0,
COALESCE(WEIGHTED_YIELD,1) + UNIFORM(-0.03,0.03,RANDOM())
)
),

LEAST(
20,
GREATEST(
0,
COALESCE(WEIGHTED_PRICE_VOLATILITY,0) + UNIFORM(-2,2,RANDOM())
)
),

ROUND(

LEAST(

3.5,

GREATEST(

1.0,

COALESCE(TARGET_TDS,2.5) + UNIFORM(-0.20,0.20,RANDOM())

)

)

,2)

FROM DISCRETE_MFG_COST_MODEL.CORE_FEATURES.TDS_TRAINING_DATA_V,

TABLE(GENERATOR(ROWCOUNT=>500));

TRUNCATE TABLE DISCRETE_MFG_COST_MODEL.CORE_OUTPUT.BMCS_RESULTS;

SELECT *
FROM DISCRETE_MFG_COST_MODEL.CORE_OUTPUT.BMCS_RESULTS;