create or replace view KMAT_PRICING.CORE_INPUT.VW_COMPONENT_COSTS(
SIMULATION_ID,
KMAT_ID,
COMPONENT_ID,
COMPONENT_DESCRIPTION,
QUANTITY,
UOM,
RULE_ID,
IS_BULK_MATERIAL,
COST_COMPONENT_GROUP,
STANDARD_COST_USD,
LINE_MATERIAL_COST_USD,
COST_MISSING_FLAG,
CALCULATED_AT
) as
SELECT
 SIMULATION_ID,
 KMAT_ID,
 COMPONENT_ID,
 COMPONENT_DESCRIPTION,
 QUANTITY,
 UOM,
 RULE_ID,
 IS_BULK_MATERIAL,
 COST_COMPONENT_GROUP,
 STANDARD_COST_USD,
 LINE_MATERIAL_COST_USD,
 COST_MISSING_FLAG,
 CALCULATED_AT
FROM
KMAT_COST_MODEL_DB.CORE_OUTPUT.KMAT_CONFIGURED_COMPONENT_COSTS;


create or replace view KMAT_PRICING.CORE_INPUT.VW_COST_SUMMARY(
SIMULATION_ID,
KMAT_ID,
MATERIAL_COST_USD,
LABOR_COST_USD,
MACHINE_COST_USD,
OVERHEAD_COST_USD,
TOTAL_CONFIGURED_COST_USD,
FLOOR_PRICE_USD,
TARGET_PRICE_USD,
CEILING_PRICE_USD,
CALCULATED_AT
) as
SELECT
 SIMULATION_ID,
 KMAT_ID,
 MATERIAL_COST_USD,
 LABOR_COST_USD,
 MACHINE_COST_USD,
  OVERHEAD_COST_USD,
 TOTAL_CONFIGURED_COST_USD,
 FLOOR_PRICE_USD,
 TARGET_PRICE_USD,
 CEILING_PRICE_USD,
 CALCULATED_AT
FROM
KMAT_COST_MODEL_DB.CORE_OUTPUT.KMAT_CONFIGURED_COST_SUMMARY;
create or replace view KMAT_PRICING.CORE_INPUT.VW_OPERATION_COSTS(
SIMULATION_ID,
KMAT_ID,
OPERATION_ID,
OPERATION_DESCRIPTION,
WORK_CENTER_ID,
LABOR_HOURS,
MACHINE_HOURS,
LABOR_RATE_USD_PER_HOUR,
MACHINE_RATE_USD_PER_HOUR,
LABOR_COST_USD,
MACHINE_COST_USD,
RULE_ID,
CALCULATED_AT
) as
SELECT
 SIMULATION_ID,
 KMAT_ID,
  OPERATION_ID,
 OPERATION_DESCRIPTION,
 WORK_CENTER_ID,
 LABOR_HOURS,
 MACHINE_HOURS,
 LABOR_RATE_USD_PER_HOUR,
 MACHINE_RATE_USD_PER_HOUR,
 LABOR_COST_USD,
 MACHINE_COST_USD,
 RULE_ID,
 CALCULATED_AT
FROM
KMAT_COST_MODEL_DB.CORE_OUTPUT.KMAT_CONFIGURED_OPERATION_COSTS;

create or replace view KMAT_PRICING.CORE_INPUT.VW_OVERHEAD_COSTS(
SIMULATION_ID,
KMAT_ID,
OVERHEAD_ID,
OVERHEAD_DESCRIPTION,
BASIS,
RATE_VALUE,
OVERHEAD_COST_USD,
RULE_ID,
CALCULATED_AT
) as
SELECT
 SIMULATION_ID,
 KMAT_ID,
 OVERHEAD_ID,
 OVERHEAD_DESCRIPTION,
 BASIS,
 RATE_VALUE,
 OVERHEAD_COST_USD,
 RULE_ID,
 CALCULATED_AT
FROM
KMAT_COST_MODEL_DB.CORE_OUTPUT.KMAT_CONFIGURED_OVERHEAD_COSTS;

create or replace view KMAT_PRICING.CORE_INPUT.VW_PRICING_INPUT(
SIMULATION_ID,
SCENARIO_NAME,
STATUS,
CREATED_AT,
CUSTOMER_ID,
CUSTOMER_NAME,
INDUSTRY,
REGION,
KMAT_ID,
PRODUCT_NAME,
PRODUCT_FAMILY,
TARGET_MARGIN_PCT,
FLOOR_MARKUP_PCT,
CEILING_MARKUP_PCT,
PRICE_ELASTICITY,
COMPETITOR_FACTOR,
ORDER_QTY,
MATERIAL_COST_USD,
LABOR_COST_USD,
MACHINE_COST_USD,
OVERHEAD_COST_USD,
TOTAL_CONFIGURED_COST_USD,
FLOOR_PRICE_USD,
TARGET_PRICE_USD,
CEILING_PRICE_USD
) as
SELECT
 SH.SIMULATION_ID,
 SH.SCENARIO_NAME,
 SH.STATUS,
 SH.CREATED_AT,
 CM.CUSTOMER_ID,
 CM.CUSTOMER_NAME,
 CM.INDUSTRY,
 CM.REGION,
 PM.KMAT_ID,
 PM.PRODUCT_NAME,
 PM.PRODUCT_FAMILY,
 SP.TARGET_MARGIN_PCT,
 SP.FLOOR_MARKUP_PCT,
 SP.CEILING_MARKUP_PCT,
 SP.PRICE_ELASTICITY,
 SP.COMPETITOR_FACTOR,
 SP.ORDER_QTY,
 CS.MATERIAL_COST_USD,
 CS.LABOR_COST_USD,
 CS.MACHINE_COST_USD,
 CS.OVERHEAD_COST_USD,
 CS.TOTAL_CONFIGURED_COST_USD,
 CS.FLOOR_PRICE_USD,
 CS.TARGET_PRICE_USD,
 CS.CEILING_PRICE_USD
FROM CORE_INPUT.SIMULATION_HEADER SH
INNER JOIN CORE_INPUT.CUSTOMER_MASTER CM
ON SH.CUSTOMER_ID = CM.CUSTOMER_ID
INNER JOIN CORE_INPUT.KMAT_PRODUCT_MASTER PM
ON SH.KMAT_ID = PM.KMAT_ID
INNER JOIN CORE_INPUT.SIMULATION_PARAMETERS SP
ON SH.SIMULATION_ID = SP.SIMULATION_ID
INNER JOIN CORE_INPUT.VW_COST_SUMMARY CS
ON SH.SIMULATION_ID = CS.SIMULATION_ID;


create or replace view
KMAT_PRICING.CORE_INPUT.VW_SIMULATION_CONFIGURATION(
SIMULATION_ID,
KMAT_ID,
ENGINE,
CAB,
COLOR,
WHEEL
) as
SELECT
 SIMULATION_ID,
 KMAT_ID,
 MAX(CASE
 WHEN CHARACTERISTIC_NAME='ENGINE'
 THEN SELECTED_VALUE
 END) AS ENGINE,
 MAX(CASE
 WHEN CHARACTERISTIC_NAME='CAB'
 THEN SELECTED_VALUE
 END) AS CAB,
 MAX(CASE
 WHEN CHARACTERISTIC_NAME='COLOR'
 THEN SELECTED_VALUE
 END) AS COLOR,
  MAX(CASE
 WHEN CHARACTERISTIC_NAME='WHEEL'
 THEN SELECTED_VALUE
 END) AS WHEEL
FROM CORE_INPUT.CHARACTERISTIC_VALUES
GROUP BY
 SIMULATION_ID,
 KMAT_ID;
