CREATE OR REPLACE TABLE KMAT_COST_MODEL_DB.CORE_INPUT.KMAT_PRODUCT_MASTER
(
    KMAT_ID VARCHAR,
    DESCRIPTION VARCHAR,
    PRODUCT_FAMILY VARCHAR,
    ACTIVE_FLAG BOOLEAN
);

INSERT INTO KMAT_COST_MODEL_DB.CORE_INPUT.KMAT_PRODUCT_MASTER VALUES
('KMAT001','Industrial Pump','PUMPS',TRUE),
('KMAT002','Industrial Motor','MOTORS',TRUE),
('KMAT003','Gearbox','TRANSMISSION',TRUE),
('KMAT004','Compressor','COMPRESSORS',TRUE),
('KMAT005','Hydraulic Unit','HYDRAULICS',TRUE);

CREATE OR REPLACE TABLE KMAT_COST_MODEL_DB.CORE_INPUT.CHARACTERISTIC_MASTER
(
    KMAT_ID VARCHAR,
    CHARACTERISTIC_NAME VARCHAR,
    ALLOWED_VALUE VARCHAR,
    DISPLAY_ORDER NUMBER,
    ACTIVE_FLAG BOOLEAN
);

INSERT INTO KMAT_COST_MODEL_DB.CORE_INPUT.CHARACTERISTIC_MASTER VALUES
('KMAT001','Color','Red',1,TRUE),
('KMAT001','Color','Blue',1,TRUE),
('KMAT001','Voltage','220V',2,TRUE),
('KMAT001','Voltage','440V',2,TRUE),

('KMAT002','Power','5 HP',1,TRUE),
('KMAT002','Power','10 HP',1,TRUE),

('KMAT003','Gear Ratio','10:1',1,TRUE),
('KMAT003','Gear Ratio','20:1',1,TRUE),

('KMAT004','Cooling','Air',1,TRUE),
('KMAT004','Cooling','Water',1,TRUE),

('KMAT005','Pressure','100 Bar',1,TRUE),
('KMAT005','Pressure','200 Bar',1,TRUE);

CREATE OR REPLACE TABLE KMAT_COST_MODEL_DB.CORE_INPUT.CHARACTERISTIC_VALUES
(
    SIMULATION_ID VARCHAR,
    KMAT_ID VARCHAR,
    CHARACTERISTIC_NAME VARCHAR,
    SELECTED_VALUE VARCHAR
);

INSERT INTO KMAT_COST_MODEL_DB.CORE_INPUT.CHARACTERISTIC_VALUES VALUES
('SIM001','KMAT001','Color','Blue'),
('SIM001','KMAT001','Voltage','440V'),

('SIM002','KMAT002','Power','10 HP'),

('SIM003','KMAT003','Gear Ratio','20:1'),

('SIM004','KMAT004','Cooling','Water'),

('SIM005','KMAT005','Pressure','200 Bar');

CREATE OR REPLACE TABLE KMAT_COST_MODEL_DB.CORE_INPUT.SIMULATION_HEADER
(
    SIMULATION_ID VARCHAR,
    KMAT_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    SCENARIO_NAME VARCHAR,
    CREATED_DATE TIMESTAMP_NTZ
);

INSERT INTO KMAT_COST_MODEL_DB.CORE_INPUT.SIMULATION_HEADER VALUES
('SIM001','KMAT001','CUST001','Standard Configuration',CURRENT_TIMESTAMP()),
('SIM002','KMAT002','CUST002','High Performance',CURRENT_TIMESTAMP()),
('SIM003','KMAT003','CUST003','Export Variant',CURRENT_TIMESTAMP()),
('SIM004','KMAT004','CUST004','Premium Model',CURRENT_TIMESTAMP()),
('SIM005','KMAT005','CUST005','Heavy Duty',CURRENT_TIMESTAMP());

CREATE OR REPLACE TABLE KMAT_COST_MODEL_DB.CORE_INPUT.SIMULATION_PARAMETERS
(
    SIMULATION_ID VARCHAR,
    TARGET_MARGIN_PCT NUMBER(5,2),
    FLOOR_MARKUP_PCT NUMBER(5,2),
    CEILING_MARKUP_PCT NUMBER(5,2)
);

INSERT INTO KMAT_COST_MODEL_DB.CORE_INPUT.SIMULATION_PARAMETERS VALUES
('SIM001',30,15,10),
('SIM002',32,15,10),
('SIM003',28,15,12),
('SIM004',35,20,15),
('SIM005',25,10,8);